Repository axelor/axelor-mobile, pull requests merged in 2023-09, with the labels that each got.

#130 fix: refresh issue on Stopwatch when app is inactive
  packages/apps/helpdesk/src/components/templates/TicketStopwatch/TicketStopwatch.js
  packages/apps/helpdesk/src/components/templates/index.js
  packages/apps/helpdesk/src/screens/TicketDetailsScreen.js
  packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js
  packages/core/src/components/external/Stopwatch/Stopwatch.tsx
  packages/core/src/components/external/Timer/Timer.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#129 feat: add expense details view
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/expense-line-api.js
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
  packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.js
  packages/apps/hr/src/components/molecules/index.js
  packages/apps/hr/src/components/templates/ExpenseHeader/ExpenseHeader.tsx
  packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx
  packages/apps/hr/src/components/templates/index.js
  packages/apps/hr/src/features/expenseLineSlice.js
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/ExpenseDetailsScreen.js
  packages/apps/hr/src/screens/ExpenseLinesListScreen.js
  packages/apps/hr/src/screens/ExpenseListScreen.js
  packages/apps/hr/src/screens/index.js
  packages/apps/hr/src/types/expense.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#131 fix: improve logic of session with camera
  packages/core/src/features/cameraScannerSlice.ts
  packages/core/src/features/scannerSlice.ts
  packages/core/src/screens/SessionManagementScreen.js
  packages/core/src/sessions/components/alerts/PopupCreateSession.js
  packages/core/src/sessions/components/alerts/PopupEditSession.js
  packages/core/src/sessions/components/display/SessionListCard.js
  packages/core/src/sessions/components/inputs/SessionInputs.js
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#132 feat: add props on ScrollView to manage pull to refresh
  packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx
  packages/ui/src/components/atoms/ScrollView/ScrollView.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done

#134 feat: improve fields props with FormView
  packages/core/src/components/pages/FormView/Components/Field.tsx
  packages/core/src/components/pages/FormView/FormView.tsx
  packages/core/src/forms/display.helpers.ts
  packages/core/src/forms/types.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done

#135 fix: block user from saving if stock correction reason is empty
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionButtons/StockCorrectionButtons.js
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#137 feat: add network links component
  packages/core/src/components/templates/SocialNetworkLinks/SocialNetworkLinks.tsx
  packages/core/src/components/templates/index.js
  packages/core/src/tools/LinkingProvider.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done

#140 feat: improve upload input with camera option
  packages/core/src/api/metafile-api.ts
  packages/core/src/components/external/Camera/Camera.js
  packages/core/src/components/external/Camera/CaptureButton.tsx
  packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx
  packages/core/src/features/cameraSlice.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done

#141 feat: add API request on buttons
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/components/atoms/ExpenseCard/ExpenseCard.tsx
  packages/apps/hr/src/components/molecules/ExpenseAddPopup/ExpenseAddPopup.js
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/ExpenseDetailsScreen.js
  packages/apps/hr/src/screens/ExpenseLinesListScreen.js
  packages/apps/hr/src/screens/ExpenseListScreen.js
  packages/apps/hr/src/types/expense.tsx
Labels: 🌟 Feature, Approved 🌟

#143 feat: add the possibility the reject an expense waiting validation
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
  packages/apps/hr/src/components/molecules/ExpenseRefusalPopup/ExpenseRefusalPopup.js
  packages/apps/hr/src/components/molecules/index.js
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#148 feat: add RadioSelect component
  packages/ui/package.json
  packages/ui/src/components/atoms/RadioButton/RadioButton.tsx
  packages/ui/src/components/atoms/index.tsx
  packages/ui/src/components/molecules/RadioSelect/RadioSelect.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/stories/atoms/RadioButton.stories.tsx
  packages/ui/stories/molecules/RadioSelect.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#146 feat: replace toggle mode component
  packages/apps/hr/src/components/templates/ToggleSwitchMode/ToggleSwitchMode.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#152 feat: add refresh on user screen
  packages/core/src/auth/screens/UserScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#139 refactor: add pull to refresh on stock package
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryCard/CustomerDeliveryCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCard/InternalMoveCard.tsx
  packages/apps/stock/src/components/templates/product/ProductCardInfo/ProductCardInfo.tsx
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveDetailsGeneralScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js
  packages/apps/stock/src/screens/inventories/InventoryPlannedDetailsScreen.js
  packages/apps/stock/src/screens/inventories/InventoryStartedDetailsScreen.js
  packages/apps/stock/src/screens/products/ProductDetailsScreen.js
  packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionDetailsScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalDetailsScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#153 feat: improve UploadFileInput
  packages/core/src/api/metafile-api.ts
  packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done

#154 feat: add branch name in artifact
  .github/workflows/gradle.yml
Labels: 🌟 Feature, ✅ Done

#155 feat: add action menu for refresh
  packages/apps/hr/src/hooks/use-hr-header-actions.js
  packages/apps/hr/src/index.ts
  packages/apps/hr/src/screens/index.js
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#158 feat: add pull to refresh for crm details screen
  packages/apps/crm/src/screens/client/ClientDetailsScreen.js
  packages/apps/crm/src/screens/contact/ContactDetailsScreen.js
  packages/apps/crm/src/screens/event/EventDetailsScreen.js
  packages/apps/crm/src/screens/lead/LeadDetailsScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityDetailsScreen.js
  packages/apps/crm/src/screens/prospect/ProspectDetailsScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#159 feat: add pull to refresh on Helpdesk details screen
  packages/apps/helpdesk/src/screens/TicketDetailsScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟
