Repository axelor/axelor-mobile, pull requests merged in 2023-03, with the labels that each got.

#18 fix: manage screen position when keyboard is open
  packages/apps/stock/src/components/organisms/InternalMoveLineCard/InternalMoveLineCard.tsx
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/core/src/screens/LoginScreen.js
  yarn.lock
Labels: 🐛 Bug, ✅ Done

#24 feat: add border color on input focus
  packages/core/src/components/molecules/InputBarCodeCard/InputBarCodeCard.js
  packages/core/src/components/organisms/DateInput/DateInput.tsx
  packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
  packages/ui/src/components/molecules/FormHtmlInput/FormHtmlInput.tsx
  packages/ui/src/components/molecules/FormIncrementInput/FormIncrementInput.tsx
  packages/ui/src/components/molecules/FormInput/FormInput.tsx
  packages/ui/src/components/molecules/IconInput/IconInput.tsx
  packages/ui/src/components/molecules/Increment/Increment.tsx
  packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
  packages/ui/src/utils/commons-styles.js
  packages/ui/src/utils/commons-utlis.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#26 fix: manage url without http / https prefix
  packages/core/src/features/authSlice.js
  packages/core/src/utils/api.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#12 feat: hide header icon actions for small screen
  packages/core/src/components/molecules/HeaderOptionsMenuItem/HeaderOptionMenuItem.tsx
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/ui/src/components/molecules/DropdownMenu/DropdownMenu.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/src/components/organisms/DropdownMenuItem/DropdownMenuItem.tsx
  packages/ui/src/components/organisms/index.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#28 fix: remove axios config on log out
  packages/core/src/api/login-api.ts
  packages/core/src/features/authSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#27 fix: should not check product if tracking number is defined
  packages/apps/stock/src/components/organisms/ProductCardInfo/ProductCardInfo.tsx
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveDetailsGeneralScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryStartedDetailsScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalDetailsScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/apps/stock/src/utils/line-navigation.ts
  packages/core/src/utils/string.ts
  yarn.lock
Labels: 🐛 Bug, ✅ Done

#31 feat: show first 5 items when user focus on the AutocompleteSearch
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
  packages/ui/src/components/organisms/SearchBar/SearchBar.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#38 fix: remove unwanted regexes from the url
  packages/core/src/features/authSlice.js
  packages/core/src/utils/api.ts
  packages/core/src/utils/formatters.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#39 feat: display instance url to which user is connected
  packages/core/src/auth/screens/SettingsScreen.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🌟 Feature, ✅ Done
