Repository axelor/axelor-mobile, pull requests merged in 2023-06, with the labels that each got.

#67 fix: manage no update link provided on force update popup
  packages/core/src/components/templates/PopupMinimalRequiredVersion/PopupMinimalRequiredVersion.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  src/app.config.js
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#71 refactor: use standard function to generate infinite scroll states
  packages/apps/crm/src/features/catalogSlice.js
  packages/apps/crm/src/features/clientSlice.js
  packages/apps/crm/src/features/contactSlice.js
  packages/apps/crm/src/features/eventSlice.js
  packages/apps/crm/src/features/leadSlice.js
  packages/apps/crm/src/features/opportunitySlice.js
  packages/apps/crm/src/features/partnerSlice.js
  packages/apps/crm/src/features/prospectSlice.js
  packages/apps/manufacturing/src/features/machinesSlice.js
  packages/apps/manufacturing/src/features/manufacturingOrderSlice.js
  packages/apps/manufacturing/src/features/operationOrderSlice.js
  packages/apps/manufacturing/src/features/productionFileSlice.js
  packages/apps/manufacturing/src/features/wasteProductsSlice.js
  packages/apps/manufacturing/src/features/workCentersSlice.js
  packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js
  packages/apps/stock/src/features/customerDeliveryLineSlice.js
  packages/apps/stock/src/features/customerDeliverySlice.js
  packages/apps/stock/src/features/internalMoveLineSlice.js
  packages/apps/stock/src/features/internalMoveSlice.js
  packages/apps/stock/src/features/inventoryLineSlice.js
  packages/apps/stock/src/features/inventorySlice.js
  packages/apps/stock/src/features/partnerSlice.js
  packages/apps/stock/src/features/productSlice.js
  packages/apps/stock/src/features/productTrackingNumberSlice.js
  packages/apps/stock/src/features/productVariantSlice.js
  packages/apps/stock/src/features/stockCorrectionSlice.js
  packages/apps/stock/src/features/stockLocationLineSlice.js
  packages/apps/stock/src/features/stockLocationSlice.js
  packages/apps/stock/src/features/supplierArrivalLineSlice.js
  packages/apps/stock/src/features/supplierArrivalSlice.js
  packages/apps/stock/src/features/trackingNumberSlice.js
  packages/core/src/apiProviders/index.js
  packages/core/src/apiProviders/utils.ts
  yarn.lock
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#76 feat: add upload tool
  android/app/src/main/java/com/aosmobile/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  package.json
  packages/core/package.json
  packages/core/src/api/metafile-api.ts
  packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx
  packages/core/src/components/molecules/index.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/index.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#79 fix: add meaningful message for iOS on camera permission
  ios/AosMobile/Info.plist
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#83 fix: ignore isRealQtyModifiedByUser on realized StockMove
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveSearchLineContainer/InternalMoveSearchLineContainer.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js
  packages/apps/stock/src/features/customerDeliveryLineSlice.js
  packages/apps/stock/src/features/internalMoveLineSlice.js
  packages/apps/stock/src/features/supplierArrivalLineSlice.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/apps/stock/src/types/index.ts
  packages/apps/stock/src/types/stock-move-line.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#85 fix: filter product stocks with user active stock location
  packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js
  packages/apps/stock/src/screens/auth/UserScreen.js
  packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js
  packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#86 fix: internal move create screen fields visibilty
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineCreationScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#82 feat: add catalogs form
  packages/apps/crm/src/api/catalog-api.js
  packages/apps/crm/src/features/catalogSlice.js
  packages/apps/crm/src/hooks/use-crm-header-actions.ts
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
  packages/apps/crm/src/screens/catalog/CatalogFormScreen.js
  packages/apps/crm/src/screens/catalog/CatalogListScreen.js
  packages/apps/crm/src/screens/catalog/index.js
  packages/core/src/api/metafile-api.ts
  packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx
  packages/ui/src/components/atoms/Input/Input.tsx
  packages/ui/src/components/molecules/FormInput/FormInput.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟
