Repository axelor/axelor-mobile, pull requests merged in 2023-04, with the labels that each got.

#43 fix: manage isRealQtyModifiedByUser and use generic API request for internal move line
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/api/internal-move-api.js
  packages/apps/stock/src/api/internal-move-line-api.js
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryViewAllContainer/CustomerDeliveryViewAllContainer.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineButtons/InternalMoveLineButtons.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveRealizeButton/InternalMoveRealizeButton.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveViewAllContainer/InternalMoveViewAllContainer.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalViewAllContainer/SupplierArrivalViewAllContainer.js
  packages/apps/stock/src/features/asyncFunctions-index.ts
  packages/apps/stock/src/features/internalMoveLineSlice.js
  packages/apps/stock/src/features/internalMoveSlice.js
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
Labels: 🐛 Bug, ✅ Done

#44 feat: manage partially done stock move lines
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/core/src/utils/filter.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done

#46 feat: display line verification depending on config
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveSearchLineContainer/InternalMoveSearchLineContainer.js
  packages/apps/stock/src/components/templates/inventory/InventorySearchLineContainer/InventorySearchLineContainer.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/core/src/auth/api/config-api.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#47 feat: add copy to clipboard manufOrderSeq
  packages/apps/manufacturing/src/components/organisms/LinkedManufacturingOrderCard/LinkedManufacturingOrderCard.tsx
  packages/apps/manufacturing/src/components/organisms/index.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListProductionOrderScreen.js
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#49 feat: use new stock configs from mobile settings
  packages/apps/crm/src/hooks/use-crm-header-actions.ts
  packages/apps/manufacturing/src/hooks/use-manufacturing-headers.js
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js
  packages/apps/stock/src/components/templates/inventory/InventoryButtons/InventoryButtons.js
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionButtons/StockCorrectionButtons.js
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionCreationButton/StockCorrectionCreationButton.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js
  packages/apps/stock/src/hooks/use-stock-header-actions.js
  packages/core/src/auth/api/config-api.js
  packages/core/src/navigator/module.helper.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#48 feat: add translations and remove success code in toast message
  packages/apps/crm/src/features/catalogSlice.js
  packages/apps/crm/src/features/clientSlice.js
  packages/apps/crm/src/features/contactSlice.js
  packages/apps/crm/src/features/crmConfigSlice.js
  packages/apps/crm/src/features/eventSlice.js
  packages/apps/crm/src/features/functionSlice.js
  packages/apps/crm/src/features/leadSlice.js
  packages/apps/crm/src/features/opportunitySlice.js
  packages/apps/crm/src/features/partnerSlice.js
  packages/apps/crm/src/features/prospectSlice.js
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
  packages/apps/manufacturing/src/features/machinesSlice.js
  packages/apps/manufacturing/src/features/manufacturingOrderSlice.js
  packages/apps/manufacturing/src/features/operationOrderSlice.js
  packages/apps/manufacturing/src/features/prodProductSlice.js
  packages/apps/manufacturing/src/features/productionFileSlice.js
  packages/apps/manufacturing/src/features/wasteProductsSlice.js
  packages/apps/manufacturing/src/features/workCentersSlice.js
  packages/apps/manufacturing/src/i18n/en.json
  packages/apps/manufacturing/src/i18n/fr.json
  packages/apps/stock/src/features/customerDeliveryLineSlice.js
  packages/apps/stock/src/features/customerDeliverySlice.js
  packages/apps/stock/src/features/internalMoveLineSlice.js
  packages/apps/stock/src/features/internalMoveSlice.js
  packages/apps/stock/src/features/inventoryLineSlice.js
  packages/apps/stock/src/features/inventorySlice.js
  packages/apps/stock/src/features/partnerSlice.js
  packages/apps/stock/src/features/productIndicatorsSlice.js
  packages/apps/stock/src/features/productSlice.js
  packages/apps/stock/src/features/productVariantSlice.js
  packages/apps/stock/src/features/racksListSlice.js
  packages/apps/stock/src/features/stockAppConfigSlice.js
  packages/apps/stock/src/features/stockCorrectionReasonSlice.js
  packages/apps/stock/src/features/stockCorrectionSlice.js
  packages/apps/stock/src/features/stockLocationLineSlice.js
  packages/apps/stock/src/features/stockLocationSlice.js
  packages/apps/stock/src/features/supplierArrivalLineSlice.js
  packages/apps/stock/src/features/supplierArrivalSlice.js
  packages/apps/stock/src/features/supplierCatalogSlice.js
  packages/apps/stock/src/features/trackingNumberSlice.js
  packages/apps/stock/src/features/unitSlice.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/core/src/apiProviders/utils.ts
  packages/core/src/auth/features/companySlice.js
  packages/core/src/auth/features/configSlice.js
  packages/core/src/auth/features/languageSlice.js
  packages/core/src/auth/features/userSlice.js
  packages/core/src/auth/i18n/en.json
  packages/core/src/auth/i18n/fr.json
  packages/core/src/features/attachedFilesSlice.js
  packages/core/src/features/mailMessageSlice.js
  packages/core/src/features/menuConfigSlice.js
  packages/core/src/features/metafileSlice.js
  packages/core/src/features/mobileConfigSlice.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#41 feat: improve config file
  example/app.config.js
  packages/core/src/app/Application.tsx
  packages/core/src/app/ContextsProvider.tsx
  packages/ui/src/theme/ThemeContext.tsx
  packages/ui/src/theme/WritingThemeContext.tsx
  packages/ui/src/theme/theme-context.helper.ts
  packages/ui/src/theme/writing-theme-context.helper.ts
  packages/ui/src/utils/objects.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#42 feat: replace status ChipSelect by MultiValuePicker for CRM screens
  packages/apps/crm/src/screens/catalog/CatalogListScreen.js
  packages/apps/crm/src/screens/event/EventPlanningScreen.js
  packages/apps/crm/src/screens/lead/LeadListScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/src/components/molecules/MultiValuePickerButton/MultiValuePickerButton.tsx
  packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
  packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
Labels: 🌟 Feature, ✅ Done
