Repository axelor/axelor-mobile, pull requests merged in 2023-10, with the labels that each got.

#11 fix: application test ci
  .github/workflows/gradle.yml
  __tests__/App-test.js
  __tests__/App.test.js
  axelor-module-name-mapper.js
  babel.config.js
  jest.config.js
  jest/setup-env.js
  jest/setup-mocks.js
  jest/setup.js
  package.json
  yarn.lock
Labels: 🪄 Test, ✅ Done, Approved 🌟

#168 feat: add coloredBubble props on InfoBubble
  packages/ui/src/components/molecules/InfoBubble/InfoBubble.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#169 fix: modify category on prospect dropdown
  packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#170 fix: modify display condition in DropdownContactView
  packages/apps/crm/src/components/organisms/DropdownContactView/DropdownContactView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#172 fix: changing nx configuration to match all computers
  nx.json
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#165 fix: translation issue on userScreen
  packages/core/src/auth/features/userSlice.js
  packages/core/src/i18n/hooks/use-translator.ts
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#173 fix: modification of arrow icon position
  packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#171 feat: add icon to Button and modify style
  packages/ui/src/components/atoms/Screen/Screen.tsx
  packages/ui/src/components/molecules/Button/Button.tsx
  packages/ui/src/utils/commons-styles.js
  packages/ui/stories/molecules/Button.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#174 feat: remove IconButton from core, error and ui packages
  packages/core/src/components/pages/FormView/FormView.tsx
  packages/core/src/screens/ErrorScreen.js
  packages/core/src/sessions/components/buttons/DisabledButton.tsx
  packages/core/src/sessions/components/buttons/LoginButton.js
  packages/core/src/sessions/components/buttons/UpdateButton.js
  packages/core/src/sessions/components/buttons/index.ts
  packages/core/src/sessions/components/index.ts
  packages/core/src/sessions/components/inputs/SessionInputs.js
  packages/ui/src/components/molecules/BlockInteractionMessage/BlockInteractionMessage.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#156 refactor: simplify helpdesk form
  packages/apps/helpdesk/src/api/customer-api.js
  packages/apps/helpdesk/src/components/molecules/DurationFormInput/DurationFormInput.tsx
  packages/apps/helpdesk/src/components/molecules/ProgressFormInput/ProgressFormInput.tsx
  packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js
  packages/apps/helpdesk/src/components/templates/CustomerSearchBar/CustomerSearchBar.js
  packages/apps/helpdesk/src/components/templates/ProjectSearchBar/ProjectSearchBar.js
  packages/apps/helpdesk/src/components/templates/TicketPriorityPicker/TicketPriorityPicker.js
  packages/apps/helpdesk/src/components/templates/TicketTypeSearchBar/TicketTypeSearchBar.js
  packages/apps/helpdesk/src/components/templates/UserSearchBar/UserSearchBar.js
  packages/apps/helpdesk/src/components/templates/index.js
  packages/apps/helpdesk/src/features/customerSlice.js
  packages/apps/helpdesk/src/index.ts
  packages/apps/helpdesk/src/models/forms.ts
  packages/apps/helpdesk/src/models/index.ts
  packages/apps/helpdesk/src/screens/TicketFormScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#175 refactor: check uses of Button in stock package
  packages/apps/stock/src/components/templates/inventory/InventoryButtons/InventoryButtons.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#177 refactor: check uses of Button in helpdesk package
  packages/apps/helpdesk/src/components/templates/TicketStopwatch/TicketStopwatch.js
  packages/apps/helpdesk/src/components/templates/TicketsStatusButton/TicketsStatusButton.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#179 feat: add expense date in store when oppening form
  packages/apps/hr/src/screens/ExpenseLineFormScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#145 feat: display last opportunity on prospect
  packages/apps/crm/src/api/opportunities-api.js
  packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js
  packages/apps/crm/src/components/organisms/DropdownOpportunityView/DropdownOpportunityView.tsx
  packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js
  packages/apps/crm/src/components/organisms/index.js
  packages/apps/crm/src/features/opportunitySlice.js
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
  packages/apps/crm/src/utils/dateEvent.js
  packages/apps/crm/src/utils/list.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#180 fix: Switch refresh when default value changes
  packages/ui/src/components/atoms/Switch/Switch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#176 refactor: check uses of Button in manufacturing package
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderButtons/ManufacturingOrderButtons.js
  packages/apps/manufacturing/src/components/organisms/index.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderDetailsScreen.js
  packages/ui/src/utils/commons-styles.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#182 refactor: improve CircleButton to match new design of Button
  packages/ui/src/components/molecules/Button/Button.tsx
  packages/ui/src/components/molecules/CircleButton/CircleButton.tsx
  packages/ui/src/components/organisms/FloatingButton/FloatingButton.tsx
  packages/ui/src/utils/commons-styles.js
  packages/ui/stories/molecules/CircleButton.stories.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#186 refactor: replace PopUp on manufacturing package by Alert
  packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductListScreen.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#194 fix: modify disabled props of SmallPropertyCard
  packages/apps/stock/src/components/organisms/SmallPropertyCard/SmallPropertyCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#185 refactor: replace PopUp on stock package by Alert
  packages/apps/stock/src/components/organisms/CardStockIndicator/CardStockIndicator.tsx
  packages/apps/stock/src/components/organisms/SmallPropertyCard/SmallPropertyCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryMovementIndicationCard/CustomerDeliveryMovementIndicationCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalMovementIndicationCard/SupplierArrivalMovementIndicationCard.tsx
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectProductScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectTrackingScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveSelectProductScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveSelectTrackingScreen.js
  packages/apps/stock/src/screens/inventories/InventorySelectProductScreen.js
  packages/apps/stock/src/screens/inventories/InventorySelectTrackingScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectProductScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectTrackingScreen.js
  packages/ui/src/components/molecules/Alert/Alert.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#199 feat: add helper to create Criteria depdending on selected chips
  packages/core/src/utils/filter.ts
  packages/core/src/utils/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#198 fix: reset tax input when selecting type which block tax amount
  packages/apps/hr/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#196 fix: export content of stock package to allow external package to use it
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/features/asyncFunctions-index.ts
  packages/apps/stock/src/features/index.js
  packages/apps/stock/src/index.ts
  packages/apps/stock/src/screens/customerDeliveries/index.js
  packages/apps/stock/src/screens/internalMoves/index.js
  packages/apps/stock/src/screens/inventories/index.js
  packages/apps/stock/src/screens/products/index.js
  packages/apps/stock/src/screens/stockCorrections/index.js
  packages/apps/stock/src/screens/supplierArrivals/index.js
  packages/apps/stock/src/utils/filters.ts
  packages/apps/stock/src/utils/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#206 refactor: remove PopUp, PopUpOneButton and PopUpTwoButton components
  packages/ui/src/components/molecules/PopUp/PopUp.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/src/components/organisms/PopUpOneButton/PopUpOneButton.tsx
  packages/ui/src/components/organisms/PopUpTwoButton/PopUpTwoButton.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/molecules/PopUp.stories.tsx
  packages/ui/stories/organisms/PopUpOneButton.stories.tsx
  packages/ui/stories/organisms/PopUpTwoButton.stories.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#204 fix: fix yarn dev
  nx.json
  package.json
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#202 fix: export content of helpdesk package to allow external package to …
  packages/apps/helpdesk/src/api/index.ts
  packages/apps/helpdesk/src/features/asyncFunctions-index.ts
  packages/apps/helpdesk/src/index.ts
  packages/apps/helpdesk/src/screens/index.js
  packages/apps/helpdesk/src/utils/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#205 fix: remove white bar which appears on some screens
  packages/ui/src/components/atoms/Screen/Screen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#162 test: add test cases for UI atoms components
  __mocks__/react-native-vector-icons/FontAwesome.js
  __mocks__/react-native-vector-icons/FontAwesome5.js
  jest/setup-mocks.js
  packages/ui/__tests__/components/atoms/BlockInteractionScreen.test.js
  packages/ui/__tests__/components/atoms/Card.test.js
  packages/ui/__tests__/components/atoms/DottedLine.test.js
  packages/ui/__tests__/components/atoms/HorizontalRule.test.js
  packages/ui/__tests__/components/atoms/HtmlInput.test.js
  packages/ui/__tests__/components/atoms/Icon.test.js
  packages/ui/__tests__/components/atoms/Input.test.js
  packages/ui/__tests__/components/atoms/KeyboardAvoidingScrollView.test.js
  packages/ui/__tests__/components/atoms/RadioButton.test.js
  packages/ui/__tests__/components/atoms/Screen.test.js
  packages/ui/__tests__/components/atoms/ScrollView.test.js
  packages/ui/__tests__/components/atoms/Switch.test.js
  packages/ui/__tests__/components/atoms/Text.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟

#212 refactor: deletion of disabled props from Icon component
  packages/core/src/components/external/Stopwatch/Stopwatch.tsx
  packages/ui/src/components/atoms/Icon/Icon.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#213 fix: long titles exceed on SearchDetailsPopUp
  packages/ui/src/components/organisms/AutoCompleteSearch/ItemCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#207 refactor: simplification of ChipSelect to use only one state for both…
  packages/ui/src/components/organisms/ChipSelect/ChipSelect.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#163 feat: add unit test for the molecules components [package: ui]
  jest.config.js
  packages/ui/__tests__/components/molecules/AttachmentCard.test.js
  packages/ui/__tests__/components/molecules/Badge.test.js
  packages/ui/__tests__/components/molecules/BlockInteractionMessage.test.js
  packages/ui/__tests__/components/molecules/Button.test.js
  packages/ui/__tests__/components/molecules/CardIconButton.test.js
  packages/ui/__tests__/components/molecules/Checkbox.test.js
  packages/ui/__tests__/components/molecules/Chip.test.js
  packages/ui/__tests__/components/molecules/CircleButton.test.js
  packages/ui/__tests__/components/molecules/ClearableCard.test.js
  packages/ui/__tests__/components/molecules/DropdownCard.test.js
  packages/ui/__tests__/components/molecules/DropdownMenu.test.js
  packages/ui/__tests__/components/molecules/EditableInput.test.js
  packages/ui/__tests__/components/molecules/FormHtmlInput.test.js
  packages/ui/__tests__/components/molecules/FormIncrementInput.test.js
  packages/ui/__tests__/components/molecules/FormInput.test.js
  packages/ui/__tests__/components/molecules/FromTo.test.js
  packages/ui/__tests__/components/molecules/HalfLabelCard.test.js
  packages/ui/__tests__/components/molecules/IconButton.test.js
  packages/ui/__tests__/components/molecules/IconInput.test.js
  packages/ui/__tests__/components/molecules/Image.test.js
  packages/ui/__tests__/components/molecules/InfoBubble.test.js
  packages/ui/__tests__/components/molecules/Label.test.js
  packages/ui/__tests__/components/molecules/LabelText.test.js
  packages/ui/__tests__/components/molecules/LoadingIndicator.test.js
  packages/ui/__tests__/components/molecules/MessageBox.test.js
  packages/ui/__tests__/components/molecules/MovementIndicationCard.test.js
  packages/ui/__tests__/components/molecules/MultiValuePickerButton.test.js
  packages/ui/__tests__/tools/index.ts
  packages/ui/__tests__/tools/styles.ts
  yarn.lock
Labels: 🪄 Test, 🚧 Doing
