Repository axelor/axelor-mobile, pull requests merged in 2023-12, with the labels that each got.

#284 feat: add custom component props in header Options
  packages/core/src/components/molecules/HeaderOptionsMenuItem/HeaderOptionMenuItem.tsx
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/core/src/header/types.ts
  packages/ui/__tests__/components/organisms/DropdownMenuItem.test.js
  packages/ui/src/components/organisms/DropdownMenuItem/DropdownMenuItem.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#285 feat: add DoubleIcon in ExpenseLine header to open selection mode
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/ExpenseLinesListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#288 feat: add ToggleButton Component
  packages/ui/__tests__/components/organisms/ToggleButton.test.js
  packages/ui/src/components/organisms/ToggleButton/ToggleButton.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/organisms/ToggleButton.stories.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#277 feat: add possibility to create line from expense details
  packages/apps/hr/src/components/templates/ExpenseLineSwitchAdd/ExpenseLineSwitchAdd.tsx
  packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx
  packages/apps/hr/src/components/templates/index.js
  packages/apps/hr/src/features/expenseLineSlice.js
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/screens/ExpenseDetailsScreen.js
  packages/apps/hr/src/screens/ExpenseLineFormScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#294 fix: invalid url error appears when typing
  packages/core/src/sessions/components/inputs/SessionInputs.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#293 fix: concurrency issue on click outside
  packages/core/src/components/organisms/DateInput/DateInput.tsx
  packages/ui/src/components/molecules/DropdownMenu/DropdownMenu.tsx
  packages/ui/src/components/molecules/InfoBubble/InfoBubble.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
  packages/ui/src/components/organisms/FloatingButton/FloatingButton.tsx
  packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
  packages/ui/src/hooks/use-click-outside.helper.ts
  packages/ui/src/hooks/use-click-outside.js
Labels: 🐛 Bug, ✅ Done

#290 fix: improve ManufacturingOrderCard and OperationOrderDetailsCard
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderCard/ManufacturingOrderCard.tsx
  packages/apps/manufacturing/src/components/organisms/OperationOrderDetailsCard/OperationOrderDetailsCard.tsx
  packages/apps/manufacturing/src/i18n/en.json
  packages/apps/manufacturing/src/i18n/fr.json
  packages/apps/manufacturing/src/types/manufacturing-order.tsx
  packages/apps/manufacturing/src/types/operation-order.tsx
  packages/apps/manufacturing/src/utils/dates.ts
  packages/apps/manufacturing/src/utils/index.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#300 fix: inventory update when return error
  packages/apps/stock/src/features/inventorySlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#308 fix: manage refresh on page after reaching end of list
  packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
Labels: 🐛 Bug, ✅ Done

#306 feat: disabled close button of Alert when login
  packages/core/src/sessions/components/alerts/PopupCreateSession.js
  packages/core/src/sessions/components/alerts/PopupSession.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#310 fix: error message when going on StockCorrection menu entry
  packages/apps/stock/src/components/molecules/StockCorrectionCard/StockCorrectionCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#311 fix: reverse order of expense list view
  packages/apps/hr/src/models/sortFields.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#304 fix: Selection container when content is null
  packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#301 fix: update invotory line when updated
  packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js
  packages/apps/stock/src/features/inventoryLineSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#302 feat: add management of js formula on studio form
  packages/core/src/forms/studio/display.helpers.ts
  packages/core/src/forms/studio/formula.helpers.ts
  packages/core/src/forms/studio/index.ts
  packages/core/src/screens/JsonFieldScreen.tsx
  packages/core/src/utils/object.ts
  packages/ui/src/components/atoms/Input/Input.tsx
Labels: 🌟 Feature, ✅ Done

#295 feat: improve TimesheetCard
  packages/apps/hr/src/components/atoms/DatesInterval/DatesInterval.tsx
  packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx
  packages/apps/hr/src/components/atoms/index.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#266 feat: add possibility to delete a draft expense
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/expense/ExpenseListScreen.js
  packages/core/src/components/organisms/AnomalyBubble/AnomalyBubble.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#315 feat: add possibility to get all values of object form from view fields
  packages/core/src/components/pages/FormView/Components/Field.tsx
  packages/core/src/forms/types.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#325 fix: refresh issue on consumedProduct tracking number update
  packages/apps/manufacturing/src/features/prodProductSlice.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js
Labels: 🐛 Bug, ✅ Done

#305 feat: add CheckboxScrollList component
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/__tests__/components/molecules/Checkbox.test.js
  packages/ui/__tests__/components/organisms/CheckboxScrollList.test.js
  packages/ui/src/components/molecules/Checkbox/Checkbox.tsx
  packages/ui/src/components/organisms/CheckboxScrollList/CheckboxScrollList.tsx
  packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/molecules/Checkbox.stories.tsx
  packages/ui/stories/organisms/CheckboxScrollList.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#317 feat: adapt Icon component for BootstrapIcon
  packages/ui/__tests__/components/atoms/Icon.test.js
  packages/ui/src/components/atoms/Icon/Icon.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#326 feat: block access to the application if user cannot be fetched
  packages/core/src/auth/features/userSlice.js
  packages/core/src/auth/i18n/en.json
  packages/core/src/auth/i18n/fr.json
  packages/core/src/auth/screens/UserScreen.js
  packages/core/src/components/templates/PopupApplicationInformation/PopupApplicationInformation.tsx
  packages/core/src/components/templates/index.js
  packages/core/src/navigator/drawer/DrawerContent.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#314 feat: add test cases for Dashboard components
  packages/ui/__tests__/components/templates/BarChart.test.js
  packages/ui/__tests__/components/templates/Dashboard.test.js
  packages/ui/__tests__/components/templates/LineChart.test.js
  packages/ui/__tests__/components/templates/PieChart.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#318 fix: add condition before dispatch to prevent undefined fetch
  packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js
  packages/apps/crm/src/components/organisms/Lead/LeadDropdownCards/LeadDropdownCards.js
  packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#303 feat : improve toggle when one of the expense type has no lines
  packages/apps/hr/src/components/templates/ExpenseLineSwitchAdd/ExpenseLineSwitchAdd.tsx
  packages/apps/hr/src/components/templates/ExpenseLineTypeDisplay/ExpenseLineTypeDisplay.tsx
  packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx
  packages/apps/hr/src/components/templates/index.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/ExpenseDetailsScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#328 fix: npe when null
  packages/apps/helpdesk/src/components/molecules/DurationFormInput/duration.helpers.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#329 refactor: improve ToggleSwitch styles
  packages/apps/crm/src/screens/catalog/CatalogListScreen.js
  packages/apps/crm/src/screens/client/ClientsListScreen.js
  packages/apps/crm/src/screens/contact/ContactListScreen.js
  packages/apps/crm/src/screens/event/EventPlanningScreen.js
  packages/apps/crm/src/screens/lead/LeadListScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js
  packages/apps/crm/src/screens/prospect/ProspectsListScreen.js
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
  packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx
  packages/apps/hr/src/screens/ExpenseListScreen.js
  packages/ui/src/components/molecules/ToggleSwitch/ToggleSwitch.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟
