Repository axelor/axelor-mobile, pull requests merged in 2023-11, with the labels that each got.

#211 refactor: simplification of Picker and SearchBar to match FormInput
  packages/apps/crm/src/components/templates/ClientProspectSearchBar/ClientProspectSearchBar.js
  packages/apps/crm/src/components/templates/ContactSearchBar/ContactSearchBar.js
  packages/apps/crm/src/screens/catalog/CatalogFormScreen.js
  packages/apps/crm/src/screens/contact/ContactFormScreen.js
  packages/apps/crm/src/screens/lead/LeadFormScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityFormScreen.js
  packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js
  packages/apps/helpdesk/src/components/templates/CustomerSearchBar/CustomerSearchBar.js
  packages/apps/helpdesk/src/components/templates/ProjectSearchBar/ProjectSearchBar.js
  packages/apps/helpdesk/src/components/templates/TicketTypeSearchBar/TicketTypeSearchBar.js
  packages/apps/helpdesk/src/components/templates/UserSearchBar/UserSearchBar.js
  packages/apps/helpdesk/src/screens/TicketFormScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductDetailsScreen.js
  packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLinePicker/InternalMoveLinePicker.js
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionReasonPicker/StockCorrectionReasonPicker.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionCreationScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineCreationScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/core/src/auth/screens/UserScreen.js
  packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx
  packages/ui/src/components/molecules/FormInput/FormInput.tsx
  packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/SearchDetailsPopUp.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
  packages/ui/src/components/organisms/SearchBar/SearchBar.tsx
  packages/ui/stories/organisms/AutoCompleteSearch.stories.tsx
  packages/ui/stories/organisms/Picker.stories.tsx
  packages/ui/stories/organisms/SearchBar.stories.tsx
  yarn.lock
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#222 fix: modification of ObjectCard to allow more flexibility
  packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Urgent ⚠️

#216 test: add test cases for Increment component
  packages/ui/__tests__/components/molecules/Increment.test.js
  packages/ui/src/components/molecules/Increment/Increment.tsx
  yarn.lock
Labels: 🪄 Test, ✅ Done, Approved 🌟

#223 fix: some API request error was shown as success
  packages/core/src/apiProviders/utils.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#225 fix: simplification of MultiValuePicker based on Picker refactor
  packages/ui/__tests__/components/molecules/MultiValuePickerButton.test.js
  packages/ui/src/components/molecules/MultiValuePickerButton/MultiValuePickerButton.tsx
  packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
  packages/ui/src/components/organisms/MultiSelectValue/MultiSelectValue.tsx
  packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/molecules/MultiValuePickerButton.stories.tsx
  packages/ui/stories/molecules/MultieValuePickerButton.stories.tsx
  packages/ui/stories/organisms/MultiSelectValue.stories.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#224 test: add test cases for NotesCard component
  packages/ui/__tests__/components/molecules/NotesCard.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#228 feat: add test cases for PanelTabs component
  packages/ui/__tests__/components/molecules/PanelTabs.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#241 fix: undefined color in darkMode
  packages/ui/src/components/atoms/Icon/Icon.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟, Urgent ⚠️

#243 refactor: add hideIfNull props to FormHtmlInput and set default width…
  packages/apps/crm/src/screens/client/ClientFormScreen.js
  packages/apps/crm/src/screens/contact/ContactFormScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityFormScreen.js
  packages/apps/crm/src/screens/prospect/ProspectFormScreen.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineNotes/InternalMoveLineNotes.js
  packages/ui/__tests__/components/molecules/FormHtmlInput.test.js
  packages/ui/src/components/molecules/FormHtmlInput/FormHtmlInput.tsx
  yarn.lock
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#234 feat: add test for popUp
  packages/ui/__tests__/components/molecules/PopUp.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#236 feat: add test for RightIconButton
  packages/ui/__tests__/components/molecules/RightIconButton.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#242 feat: add test for titledValue
  packages/ui/__tests__/components/molecules/TitledValue.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#245 fix: manage AOP errors on API request
  packages/core/src/api/mobile-config-api.ts
  packages/core/src/apiProviders/utils.ts
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Urgent ⚠️

#221 feat: creation of TimeSheetLineCard
  packages/apps/hr/src/components/atoms/DateDisplay/DateDisplay.tsx
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/atoms/TextUnit/TextUnit.tsx
  packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx
  packages/apps/hr/src/components/atoms/index.js
  packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx
  packages/apps/hr/src/components/molecules/index.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/types/index.ts
  packages/apps/hr/src/types/time.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#235 test: add cases for RadioSelect component
  packages/ui/__tests__/components/molecules/RadioSelect.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#246 test: add test for ViewAllContainer component
  packages/ui/__tests__/components/molecules/ViewAllContainer.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#247 test: add cases for WarningCard component
  packages/ui/__tests__/components/molecules/WarningCard.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#248 test: add cases for UnorderedList component
  packages/ui/__tests__/components/molecules/UnorderedList.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#254 fix: remove arrow icon on non clickable card
  packages/apps/stock/src/components/templates/product/ProductStockLocationCard/ProductStockLocationCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#227 fix: adapt stock screen for low resolution
  packages/apps/stock/src/components/templates/ProductTrackingNumberSearchBar/ProductTrackingNumberSearchBar.js
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryMovementIndicationCard/CustomerDeliveryMovementIndicationCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveMovementIndicationCard/InternalMoveMovementIndicationCard.tsx
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionReasonPicker/StockCorrectionReasonPicker.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalMovementIndicationCard/SupplierArrivalMovementIndicationCard.tsx
  packages/apps/stock/src/features/productIndicatorsSlice.js
  packages/apps/stock/src/hooks/index.js
  packages/apps/stock/src/hooks/stock-location-lines-availability.js
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineCreationScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveDetailsGeneralScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineCreationScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryPlannedDetailsScreen.js
  packages/apps/stock/src/screens/inventories/InventoryStartedDetailsScreen.js
  packages/apps/stock/src/screens/products/ProductDetailsScreen.js
  packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js
  packages/apps/stock/src/screens/products/ProductStockLocationDetailsScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionCreationScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionDetailsScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalDetailsScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineCreationScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/core/src/auth/screens/UserScreen.js
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#249 feat: add test for DropdownCardSwitch
  packages/ui/__tests__/components/organisms/DropdownCardSwitch.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟

#237 test: add cases for SelectionContainer component
  packages/ui/__tests__/components/molecules/SelectionContainer.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟

#259 feat: add test cases for FloatingButton component
  packages/ui/__tests__/components/organisms/FloatingButton.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟, Pair approved 🌟

#262 fix: add flexDirection props to collapsible pannel in forms
  docs/doc/en/Application/Creation_d_un_ecran.md
  docs/doc/fr/Application/Creation_d_un_ecran.md
  packages/core/src/components/pages/FormView/Components/Panel.tsx
  packages/core/src/forms/studio/display.helpers.ts
  packages/core/src/forms/types.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#251 feat: add test cases for ChipSelect component
  packages/ui/__tests__/components/organisms/ChipSelect.test.js
  packages/ui/src/components/organisms/ChipSelect/ChipSelect.tsx
Labels: 🪄 Test, ✅ Done, Approved 🌟

#258 feat: add test cases for DropdownMenuItem component
  packages/ui/__tests__/components/organisms/DropdownMenuItem.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟

#253 fix: manage FontAwesome icon display on storybook
  .storybook/preview.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#260 feat: add test cases for HeaderContainer component
  packages/ui/__tests__/components/organisms/HeaderContainer.test.js
  packages/ui/src/components/organisms/HeaderContainer/HeaderContainer.tsx
Labels: 🪄 Test, ✅ Done, Approved 🌟

#261 feat: add test cases for ImageBubble component
  packages/ui/__tests__/components/organisms/ImageBubble.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟

#250 feat: add test cases for AutoCompleteSearch component
  packages/ui/__tests__/components/organisms/AutoCompleteSearch.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟

#274 fix: refresh issue on distanceInput
  packages/apps/hr/src/features/distanceSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#270 fix: refresh issue on expense details when editing expense line
  packages/apps/hr/src/features/expenseLineSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#272 fix: invalid url error stay on all popup
  packages/core/src/sessions/components/inputs/SessionInputs.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#268 feat: add icon Expense buttons
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#271 fix: SelectionContainer can't be open again after clearing value on A…
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#267 feat: add label for groundForRefusal
  packages/apps/hr/src/components/templates/ExpenseHeader/ExpenseHeader.tsx
  packages/apps/hr/src/components/templates/ExpenseLineTypeSwitch/ExpenseLineTypeSwitch.tsx
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/models/objectFields.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#279 fix: session expired after 2minutes on AOP7
  packages/core/src/api/net-info-utils.ts
  packages/core/src/sessions/components/error/ErrorText.js
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#264 feat: add Icon stories
  packages/ui/stories/atoms/Icon.stories.tsx
Labels: 📚 Documentation, ✅ Done, Approved 🌟, Pair approved 🌟

#276 fix: add missing exports in HR
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/features/asyncFunctions-index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#278 fix: refresh issue on KilometricAllowParamSearchBar
  packages/apps/hr/src/components/templates/KilometricAllowParamSearchBar/KilometricAllowParamSearchBar.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#269 feat: add city, and distance on kilometric expense line card
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#263 feat: add DoubleIcon component
  packages/ui/__tests__/components/molecules/DoubleIcon.test.js
  packages/ui/src/components/molecules/DoubleIcon/DoubleIcon.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/stories/molecules/DoubleIcon.stories.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟, Urgent ⚠️

#286 feat: feat npe in Manufacturing PlanningView
  packages/apps/manufacturing/src/components/organisms/OperationOrderHeader/OperationOrderHeader.tsx
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderPlanningScreen.js
  packages/apps/manufacturing/src/types/operation-order.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟, Urgent ⚠️

#281 fix: Helpdesk change default selected chip
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
  packages/apps/helpdesk/src/types/ticket.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟
