Repository axelor/axelor-mobile, pull requests merged in 2023-05, with the labels that each got.

#33 fix: manage no tracking number configured
  packages/apps/stock/src/api/customer-delivery-line-api.js
  packages/apps/stock/src/api/internal-move-line-api.js
  packages/apps/stock/src/api/inventory-line-api.js
  packages/apps/stock/src/api/supplier-arrival-line-api.js
  packages/apps/stock/src/components/organisms/QuantityCard/QuantityCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryHeader/CustomerDeliveryHeader.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineButtons/CustomerDeliveryLineButtons.js
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineTrackingNumberSelect/CustomerDeliveryLineTrackingNumberSelect.js
  packages/apps/stock/src/components/templates/customerDelivery/index.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineButtons/InternalMoveLineButtons.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineTrackingNumberSelect/InternalMoveLineTrackingNumberSelect.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveViewAllContainer/InternalMoveViewAllContainer.js
  packages/apps/stock/src/components/templates/internalMove/index.js
  packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js
  packages/apps/stock/src/components/templates/inventory/InventoryLineQuantityCard/InventoryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/inventory/InventoryLineTrackingNumberSelect/InventoryLineTrackingNumberSelect.js
  packages/apps/stock/src/components/templates/inventory/index.js
  packages/apps/stock/src/components/templates/product/ProductTrackingNumberSelect/ProductTrackingNumberSelect.jsx
  packages/apps/stock/src/components/templates/product/index.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalHeader/SupplierArrivalHeader.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineButtons/SupplierArrivalLineButtons.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalTrackingNumberSelect/SupplierArrivalTrackingNumberSelect.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalViewAllContainer/SupplierArrivalViewAllContainer.js
  packages/apps/stock/src/features/customerDeliveryLineSlice.js
  packages/apps/stock/src/features/internalMoveLineSlice.js
  packages/apps/stock/src/features/inventoryLineSlice.js
  packages/apps/stock/src/features/supplierArrivalLineSlice.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectProductScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectTrackingScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveDetailsGeneralScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveSelectProductScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveSelectTrackingScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js
  packages/apps/stock/src/screens/inventories/InventorySelectProductScreen.js
  packages/apps/stock/src/screens/inventories/InventorySelectTrackingScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalAddTrackingScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectProductScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectTrackingScreen.js
  packages/apps/stock/src/types/inventory.tsx
  packages/apps/stock/src/types/stock-move.tsx
  packages/apps/stock/src/utils/line-navigation.ts
  packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#56 feat: save url in storage
  packages/core/src/features/authSlice.js
  packages/core/src/screens/LoginScreen.js
  packages/core/src/utils/storage-keys.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#59 feat: manage drawer subtitles dynamically
  packages/core/src/app/Application.tsx
  packages/core/src/app/ContextedApplication.tsx
  packages/core/src/app/ContextsProvider.tsx
  packages/core/src/app/RootNavigator.js
  packages/core/src/auth/i18n/en.json
  packages/core/src/auth/i18n/fr.json
  packages/core/src/auth/screens/SettingsScreen.js
  packages/core/src/navigator/Navigator.js
  packages/core/src/navigator/drawer/DrawerContent.js
  packages/ui/src/config/ConfigContext.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#60 chore: add check license job on pipeline
  .github/workflows/gradle.yml
  .licenserc.json
Labels: 🌟 Feature, ✅ Done

#62 chore: add storybook in read me
  README.md
Labels: 📚 Documentation, ✅ Done, Approved 🌟

#61 chore: add create release with apk on tag job in pipeline
  .github/workflows/gradle.yml
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#54 feat: enable to define list of headband to display above header
  packages/core/src/app/ContextedApplication.tsx
  packages/core/src/app/ContextsProvider.tsx
  packages/core/src/components/molecules/HeaderBand/HeaderBand.tsx
  packages/core/src/components/molecules/index.js
  packages/core/src/components/organisms/HeaderBandList/HeaderBandList.tsx
  packages/core/src/components/organisms/index.js
  packages/core/src/header/HeaderBandContext.tsx
  packages/core/src/header/header-band-context.helper.ts
  packages/core/src/header/index.ts
  packages/core/src/header/types.ts
  packages/core/src/navigator/Navigator.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#55 feat: add banner on header when user is connected on test instance
  packages/core/src/api/login-api.ts
  packages/core/src/app/ContextedApplication.tsx
  packages/core/src/auth/hooks/use-auth-headers.js
  packages/core/src/auth/i18n/en.json
  packages/core/src/auth/i18n/fr.json
  packages/core/src/features/authSlice.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟
