Repository axelor/axelor-mobile, pull requests merged in 2023-08, with the labels that each got.

#105 refactor: simplify crm object cards
  packages/apps/crm/src/components/molecules/CatalogCard/CatalogCard.tsx
  packages/apps/crm/src/components/molecules/LeadsCard/LeadsCard.tsx
  packages/apps/crm/src/components/molecules/LiteContactCard/LiteContactCard.tsx
  packages/apps/crm/src/components/molecules/OpportunityCard/OpportunityCard.tsx
  packages/apps/crm/src/components/molecules/PartnerCard/PartnerCard.tsx
  packages/apps/crm/src/components/molecules/PartnerInfoCard/PartnerInfoCard.tsx
  packages/apps/crm/src/components/molecules/PlanningEventCard/PlanningEventCard.tsx
  packages/apps/crm/src/components/organisms/DropdownEmployeeView/DropdownEmployeeView.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#106 refactor: simplify helpdesk object cards
  packages/apps/helpdesk/src/components/molecules/TicketCard/TicketCard.tsx
  packages/ui/src/theme/writingTheme.ts
  yarn.lock
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#117 feat: manage max size and preview on UploadFileInput
  packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx
  packages/core/src/i18n/hooks/use-translator.ts
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#118 fix: improve refresh logic of header actions
  packages/core/src/header/HeaderActionsProvider.ts
  packages/core/src/header/index.ts
  packages/core/src/navigator/drawer/Header.js
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#112 feat: manage compatibility override
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/navigator/drawer/DrawerContent.js
  packages/core/src/navigator/drawer/Menu.js
  packages/core/src/navigator/module.helper.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#113 feat: add contact provider to register phone contact
  android/app/src/main/AndroidManifest.xml
  ios/AosMobile/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package.json
  packages/core/package.json
  packages/core/src/tools/ContactProvider.ts
  packages/core/src/tools/contact.helper.ts
  packages/core/src/tools/index.js
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#121 feat: add TabsScreen component
  packages/ui/src/components/templates/TabsScreen/IndicatorBadge.tsx
  packages/ui/src/components/templates/TabsScreen/Tab.tsx
  packages/ui/src/components/templates/TabsScreen/TabsScreen.tsx
  packages/ui/src/components/templates/TabsScreen/tabs.helper.ts
  packages/ui/src/components/templates/index.js
  packages/ui/stories/templates/TabsScreen.stories.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#123 feat: add module default menu mangement
  packages/core/src/app/Module.ts
  packages/core/src/auth/index.ts
  packages/core/src/navigator/drawer/DrawerContent.js
  packages/core/src/navigator/drawer/SubMenuItemList.js
  packages/core/src/navigator/menu.helper.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#115 feat: add orphan expense lines menu entry in HR
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/expense-line-api.js
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/atoms/index.js
  packages/apps/hr/src/components/index.js
  packages/apps/hr/src/components/molecules/ExpenseAddPopup/ExpenseAddPopup.js
  packages/apps/hr/src/components/molecules/ExpenseLineValidationButton/ExpenseLineValidationButton.js
  packages/apps/hr/src/components/molecules/index.js
  packages/apps/hr/src/features/expenseLineSlice.js
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/features/index.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/index.ts
  packages/apps/hr/src/models/index.ts
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/models/searchFields.ts
  packages/apps/hr/src/models/sortFields.ts
  packages/apps/hr/src/screens/ExpenseLinesListScreen.js
  packages/apps/hr/src/screens/index.js
  packages/apps/hr/src/types/expense.tsx
  packages/apps/hr/src/types/expenseLine.tsx
  packages/apps/hr/src/types/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#126 feat: individualization of the operation order stopwatch
  packages/apps/manufacturing/src/api/operation-order-api.js
  packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js
  packages/apps/manufacturing/src/features/operationOrderSlice.js
  packages/apps/manufacturing/src/types/operation-order.tsx
  packages/core/src/apiProviders/utils.ts
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟
