Repository axelor/axelor-mobile, pull requests merged in 2023-07, with the labels that each got.

#90 fix: add scrollView in InternalMoveLineCreationScreen
  packages/apps/stock/src/components/templates/AvailableProductsSearchBar/AvailableProductsSearchBar.js
  packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineCreationScreen.js
  packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx
  packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#94 feat: create component to block screen depending on config
  packages/core/src/app/ContextedApplication.tsx
  packages/ui/src/components/molecules/BlockInteractionMessage/BlockInteractionMessage.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/src/config/ConfigContext.tsx
  packages/ui/stories/molecules/BlockInteractionMessage.stories.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#99 fix: display issue in AutoCompleteSearch component
  packages/ui/src/components/atoms/Input/Input.tsx
  packages/ui/src/components/molecules/IconInput/IconInput.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
  packages/ui/src/components/organisms/SearchBar/SearchBar.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#97 feat: Improve qty selector
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductDetailsScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductDetailsScreen.js
  packages/apps/stock/src/components/organisms/QuantityCard/QuantityCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineQuantityCard/InternalMoveLineQuantityCard.js
  packages/apps/stock/src/components/templates/inventory/InventoryLineQuantityCard/InventoryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionQuantityCard/StockCorrectionQuantityCard.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalAddTrackingScreen.js
  packages/ui/src/components/atoms/Icon/Icon.tsx
  packages/ui/src/components/molecules/FormIncrementInput/FormIncrementInput.tsx
  packages/ui/src/components/molecules/Increment/Increment.tsx
  packages/ui/src/components/molecules/Increment/IncrementButton.tsx
  packages/ui/stories/molecules/FormIncrementInput.stories.tsx
  packages/ui/stories/molecules/Increment.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#103 feat: add menu create ticket
  packages/apps/helpdesk/src/api/customer-api.js
  packages/apps/helpdesk/src/api/ticket-api.js
  packages/apps/helpdesk/src/components/molecules/DurationFormInput/DurationFormInput.tsx
  packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js
  packages/apps/helpdesk/src/components/templates/TicketTypeSearchBar/TicketTypeSearchBar.js
  packages/apps/helpdesk/src/components/templates/UserSearchBar/UserSearchBar.js
  packages/apps/helpdesk/src/features/customerSlice.js
  packages/apps/helpdesk/src/features/ticketSlice.js
  packages/apps/helpdesk/src/i18n/en.json
  packages/apps/helpdesk/src/i18n/fr.json
  packages/apps/helpdesk/src/index.ts
  packages/apps/helpdesk/src/models/objectFields.ts
  packages/apps/helpdesk/src/models/searchFields.ts
  packages/apps/helpdesk/src/models/sortFields.ts
  packages/apps/helpdesk/src/screens/TicketFormScreen.js
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#104 fix: alignment on form views
  packages/apps/crm/src/components/organisms/Opportunity/OpportunityUpdateStatusPicker/OpportunityUpdateStatusPicker.js
  packages/apps/crm/src/screens/client/ClientFormScreen.js
  packages/apps/crm/src/screens/contact/ContactFormScreen.js
  packages/apps/crm/src/screens/lead/LeadFormScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityFormScreen.js
  packages/apps/crm/src/screens/prospect/ProspectFormScreen.js
  packages/apps/stock/src/components/organisms/QuantityCard/QuantityCard.tsx
  packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineNotes/InternalMoveLineNotes.js
  packages/apps/stock/src/components/templates/product/ProductCardInfo/ProductCardInfo.tsx
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionReasonPicker/StockCorrectionReasonPicker.js
  packages/apps/stock/src/screens/auth/UserScreen.js
  packages/core/src/auth/screens/UserScreen.js
  packages/ui/src/components/molecules/FormHtmlInput/FormHtmlInput.tsx
  packages/ui/src/components/molecules/NotesCard/NotesCard.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
  yarn.lock
Labels: 🐛 Bug, ✅ Done

#98 refactor: simplify stock object cards
  packages/apps/stock/src/components/molecules/StockCorrectionCard/StockCorrectionCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryCard/CustomerDeliveryCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCard/InternalMoveCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx
  packages/apps/stock/src/components/templates/inventory/InventoryCard/InventoryCard.tsx
  packages/apps/stock/src/components/templates/inventory/InventoryLineCard/InventoryLineCard.tsx
  packages/apps/stock/src/components/templates/product/ProductCard/ProductCard.tsx
  packages/apps/stock/src/components/templates/product/ProductStockLocationCard/ProductStockLocationCard.tsx
  packages/apps/stock/src/components/templates/product/ProductVariantCard/ProductVariantCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalCard/SupplierArrivalCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryListScreen.js
  packages/apps/stock/src/screens/products/ProductListScreen.js
  packages/apps/stock/src/screens/products/ProductListVariantScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js
  yarn.lock
Labels: 🔧 Refactor, ✅ Done, Approved 🌟
