Repository axelor/axelor-mobile, pull requests merged in 2024-07, with the labels that each got.

#608 feat: create SaleOrderLineDetailsScreen
  packages/apps/sales/src/api/index.ts
  packages/apps/sales/src/api/sale-order-line-api.js
  packages/apps/sales/src/components/atoms/DropdownSOLConfigurationView/DropdownSOLConfigurationView.tsx
  packages/apps/sales/src/components/atoms/DropdownSOLMarginView/DropdownSOLMarginView.tsx
  packages/apps/sales/src/components/atoms/ProductCard/ProductCard.tsx
  packages/apps/sales/src/components/atoms/index.ts
  packages/apps/sales/src/components/molecules/SaleOrderLineDropdownCards/SaleOrderLineDropdownCards.tsx
  packages/apps/sales/src/components/molecules/SaleOrderLinePriceDetails/SaleOrderLinePriceDetails.tsx
  packages/apps/sales/src/components/molecules/index.ts
  packages/apps/sales/src/features/asyncFunctions-index.ts
  packages/apps/sales/src/features/saleOrderLineSlice.js
  packages/apps/sales/src/hooks/use-sales-header-actions.ts
  packages/apps/sales/src/i18n/en.json
  packages/apps/sales/src/i18n/fr.json
  packages/apps/sales/src/models/objectFields.ts
  packages/apps/sales/src/models/typeObjects.ts
  packages/apps/sales/src/screens/saleOrder/SaleOrderLineDetailsScreen.tsx
  packages/apps/sales/src/screens/saleOrder/SaleOrderLineListScreen.tsx
  packages/apps/sales/src/screens/saleOrder/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#620 feat: create client details screen
  packages/apps/crm/src/components/organisms/Client/ClientHeader/ClientHeader.js
  packages/apps/sales/src/api/customer-api.js
  packages/apps/sales/src/api/index.ts
  packages/apps/sales/src/components/molecules/ClientHeader/ClientHeader.tsx
  packages/apps/sales/src/components/molecules/index.ts
  packages/apps/sales/src/features/asyncFunctions-index.ts
  packages/apps/sales/src/features/customerSlice.js
  packages/apps/sales/src/hooks/use-sales-header-actions.ts
  packages/apps/sales/src/i18n/en.json
  packages/apps/sales/src/i18n/fr.json
  packages/apps/sales/src/index.ts
  packages/apps/sales/src/models/objectFields.ts
  packages/apps/sales/src/screens/client/ClientSaleDetailsScreen.tsx
  packages/apps/sales/src/screens/client/ClientSaleListScreen.tsx
  packages/apps/sales/src/screens/client/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#624 fix: refresh issue in useTypes function
  changelogs/unreleased/80710.json
  packages/core/src/selections/SelectionProvider.tsx
  packages/core/src/selections/format.helpers.ts
  packages/core/src/selections/hooks.ts
Labels: 🐛 Bug, ✅ Done

#625 feat: add order edited icon, delivery and invoicing badges on SaleOrder details
  packages/apps/sale/src/components/molecules/SaleOrderHeader/SaleOrderHeader.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#632 fix: wrong content when opening selection mode from header
  changelogs/unreleased/81306.json
  packages/apps/hr/src/screens/expense/ExpenseLinesListScreen.js
Labels: 🐛 Bug, ✅ Done

#634 fix: add header actions of hr screens
  changelogs/unreleased/81324_header.json
  changelogs/unreleased/81324_type.json
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/hooks/use-hr-header-actions.js
  packages/apps/hr/src/models/typeObjects.ts
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
  packages/apps/hr/src/screens/expense/index.js
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js
  packages/apps/hr/src/screens/timesheet/index.ts
Labels: 🐛 Bug, ✅ Done

#637 feat: manage drawing widget on custom form
  changelogs/unreleased/81364.json
  packages/core/src/forms/studio/display.helpers.ts
Labels: 🌟 Feature, ✅ Done

#630 feat: create complementary products screen
  packages/apps/sale/src/api/complementary-product-api.js
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/components/atoms/ComplementaryProductCard/ComplementaryProductCard.tsx
  packages/apps/sale/src/components/atoms/index.ts
  packages/apps/sale/src/components/molecules/ProductFloatingButton/ProductFloatingButton.tsx
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/complementaryProductSlice.js
  packages/apps/sale/src/features/index.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/models/objectFields.ts
  packages/apps/sale/src/models/searchFields.ts
  packages/apps/sale/src/models/sortFields.ts
  packages/apps/sale/src/screens/product/ComplementaryProductsScreen.tsx
  packages/apps/sale/src/screens/product/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#627 feat: create product price lists screen
  changelogs/unreleased/80369.json
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/api/price-list-line-api.js
  packages/apps/sale/src/components/atoms/PriceListCard/PriceListCard.tsx
  packages/apps/sale/src/components/atoms/index.ts
  packages/apps/sale/src/components/molecules/ProductFloatingButton/ProductFloatingButton.tsx
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/index.js
  packages/apps/sale/src/features/priceListLineSlice.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/models/objectFields.ts
  packages/apps/sale/src/models/searchFields.ts
  packages/apps/sale/src/models/sortFields.ts
  packages/apps/sale/src/models/typeObjects.ts
  packages/apps/sale/src/screens/product/ProductSalePriceListsScreen.tsx
  packages/apps/sale/src/screens/product/index.ts
  packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#641 feat: add default session for demo app
  changelogs/unreleased/70291.json
  packages/core/src/app/Application.tsx
  packages/core/src/sessions/SessionStorage.ts
  src/app.config.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#635 fix: trad in manufacturing order
  changelogs/unreleased/75975.json
  packages/apps/manufacturing/src/i18n/en.json
  packages/apps/manufacturing/src/i18n/fr.json
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#628 fix: margin when title is to long in FloattingButton component
  changelogs/unreleased/81147.json
  packages/ui/src/components/organisms/FloatingButton/FloatingActionButton.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#622 fix: make props not required in MailMessageNotificationCard
  changelogs/unreleased/81223.json
  packages/core/src/components/organisms/MailMessageNotificationCard/MailMessageNotificationCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#629 fix: margin issue when smallscreen
  changelogs/unreleased/80714.json
  packages/apps/stock/src/components/templates/product/ProductSeeStockLocationDistribution/ProductSeeStockLocationDistribution.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#626 feat: add placeholder on picker
  changelogs/unreleased/81199.json
  packages/ui/__tests__/components/molecules/MultiValuePickerButton.test.js
  packages/ui/__tests__/components/organisms/MultiValuePicker.test.js
  packages/ui/__tests__/components/organisms/Picker.test.js
  packages/ui/src/components/molecules/MultiValuePickerButton/MultiValuePickerButton.tsx
  packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
  packages/ui/stories/organisms/MultiValuePicker.stories.tsx
  packages/ui/stories/organisms/Picker.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#588 feat: add reportingView
  changelogs/unreleased/78177_dateDisplay.json
  changelogs/unreleased/78177_labelText.json
  changelogs/unreleased/78177_mailMessage.json
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/project-api.js
  packages/apps/project/src/components/molecules/ActivityCard/ActivityCard.tsx
  packages/apps/project/src/components/molecules/index.ts
  packages/apps/project/src/components/pages/ReportingView/ReportingView.tsx
  packages/apps/project/src/components/pages/index.ts
  packages/apps/project/src/components/templates/ActivityListView/ActivityListView.tsx
  packages/apps/project/src/components/templates/index.ts
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
  packages/core/src/components/molecules/DateDisplay/DateDisplay.tsx
  packages/core/src/components/organisms/MailMessageNotificationCard/MailMessageNotificationCard.tsx
  packages/core/src/utils/image.ts
  packages/ui/src/components/molecules/LabelText/LabelText.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#643 fix: add null check on mobileSettings in hr form conditions
  changelogs/unreleased/81627.json
  packages/apps/hr/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#640 feat: create new component ActionCard
  changelogs/unreleased/81256.json
  changelogs/unreleased/81256_buttons.json
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/__tests__/components/organisms/ActionCard.test.js
  packages/ui/src/components/molecules/CardIconButton/CardIconButton.tsx
  packages/ui/src/components/organisms/ActionCard/ActionCard.tsx
  packages/ui/src/components/organisms/InfoButton/InfoButton.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/organisms/ActionCard.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#644 fix: display issue for date time inputs on CustomFieldForm
  changelogs/unreleased/80811.json
  packages/core/src/forms/studio/display.helpers.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#645 fix: remove bottom buttons on CustomFieldForm
  changelogs/unreleased/81739.json
  packages/core/src/components/pages/FormView/FormView.tsx
  packages/core/src/screens/JsonFieldScreen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#599 feat: add details on click on chart
  changelogs/unreleased/79352.json
  packages/core/src/dashboards/component/AOPChart/AOPChart.tsx
  packages/core/src/dashboards/component/RefreshChart/RefreshChart.tsx
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/src/components/templates/Dashboard/Chart/BarChart.tsx
  packages/ui/src/components/templates/Dashboard/Chart/ChartRender.tsx
  packages/ui/src/components/templates/Dashboard/Chart/DetailsPopup.tsx
  packages/ui/src/components/templates/Dashboard/Chart/IndicatorChart/IndicatorChart.tsx
  packages/ui/src/components/templates/Dashboard/Chart/IndicatorChart/IndicatorItem.tsx
  packages/ui/src/components/templates/Dashboard/Chart/IndicatorChart/SimpleIndicator.tsx
  packages/ui/src/components/templates/Dashboard/Chart/LineChart.tsx
  packages/ui/src/components/templates/Dashboard/Dashboard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#647 fix: display issue on TaskCard
  packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#649 feat: replace cards with new actionCard component in manufacturing screens
  changelogs/unreleased/81859.json
  packages/apps/manufacturing/src/components/organisms/ConsumedProductCard/ConsumedProductCard.tsx
  packages/apps/manufacturing/src/components/organisms/ConsumedProductGlobalCard/ConsumedProductGlobalCard.tsx
  packages/apps/manufacturing/src/i18n/en.json
  packages/apps/manufacturing/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#656 feat: add props ActionCard to force actions display
  packages/apps/manufacturing/src/components/organisms/ConsumedProductGlobalCard/ConsumedProductGlobalCard.tsx
  packages/ui/src/components/organisms/ActionCard/ActionCard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#621 feat: always leave information of current group on GroupByScrollList
  changelogs/unreleased/73774.json
  packages/ui/__tests__/components/organisms/GroupByScrollList.test.js
  packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx
  packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#652 feat: replace cards with actions by ActionCard in intervention
  changelogs/unreleased/81791.json
  packages/apps/intervention/src/components/atoms/EquipmentCard/EquipmentCard.tsx
  packages/apps/intervention/src/components/atoms/InterventionCard/InterventionCard.tsx
  packages/apps/intervention/src/components/atoms/NoteCard/NoteCard.tsx
  packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx
  packages/apps/intervention/src/components/molecules/InterventionDetailCard/InterventionDetailCard.tsx
  packages/apps/intervention/src/components/molecules/NoteDetailCard/NoteDetailCard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#653 feat: replace cards with actions by ActionCard in hr
  changelogs/unreleased/81789.json
  packages/apps/hr/src/components/atoms/ExpenseCard/ExpenseCard.tsx
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx
  packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx
  packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#658 fix: issue when title to long on project header
  packages/apps/project/src/components/molecules/ProjectHeader/ProjectHeader.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#659 refactor: use Action ActionCard Project
  packages/apps/project/src/components/atoms/PartnerCard/PartnerCard.tsx
  packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx
  packages/apps/project/src/components/molecules/PartnerActionCard/PartnerActionCard.tsx
  packages/apps/project/src/components/molecules/TaskActionCard/TaskActionCard.tsx
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#660 fix: Indicator datasets type
  packages/ui/src/components/templates/Dashboard/Chart/IndicatorChart/IndicatorChart.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#651 feat: replace cards with actions by ActionCard in crm
  changelogs/unreleased/81788.json
  packages/apps/crm/src/components/molecules/TourLineCard/TourLineCard.tsx
  packages/apps/crm/src/components/organisms/TourLineActionCard/TourLineActionCard.tsx
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
  packages/ui/__tests__/components/organisms/ActionCard.test.js
  packages/ui/src/components/organisms/ActionCard/ActionCard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#650 feat: add print template
  changelogs/unreleased/78046.json
  packages/core/src/api/print-template-api.js
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/core/src/components/organisms/PopupPrintTemplate/PopupPrintTemplate.tsx
  packages/core/src/components/organisms/index.js
  packages/core/src/components/templates/PrintTemplateSearchBar/PrintTemplateSearchBar.tsx
  packages/core/src/components/templates/index.js
  packages/core/src/features/index.js
  packages/core/src/features/printTemplateSlice.js
  packages/core/src/header/hooks.js
  packages/core/src/header/types.ts
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/models/objectFields.ts
  packages/core/src/models/searchFields.ts
  packages/core/src/navigator/drawer/Header.js
  packages/core/src/tools/FileViewer.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#648 fix: impossible to use signature widget with a scrollview
  changelogs/unreleased/81450.json
  packages/core/src/components/organisms/SignatureInput/SignatureInput.tsx
  packages/core/src/forms/studio/display.helpers.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#661 refactor: use Action Card on Sales module
  packages/apps/sale/src/components/atoms/ClientCard/ClientCard.tsx
  packages/apps/sale/src/components/atoms/PartnerCard/PartnerCard.tsx
  packages/apps/sale/src/components/molecules/ClientActionCard/ClientActionCard.tsx
  packages/apps/sale/src/components/molecules/PartnerActionCard/PartnerActionCard.tsx
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#667 fix: modify menu icon of products
  packages/apps/sale/src/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟
