Repository axelor/axelor-mobile, pull requests merged in 2024-05, with the labels that each got.

#546 fix: display issue on supplier arrival line details view
  changelogs/unreleased/78347.json
  packages/apps/stock/src/components/templates/supplierArrival/SupplierProductInfo/SupplierProductInfo.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#525 fix: add missings props in expense form components
  changelogs/unreleased/78315.json
  changelogs/unreleased/78315_RadioSelect.json
  changelogs/unreleased/78315_Switch.json
  packages/apps/hr/src/components/templates/BillableSwitchCard/BillableSwitchCard.tsx
  packages/apps/hr/src/components/templates/DistanceIncrement/DistanceIncrement.js
  packages/apps/hr/src/components/templates/ExpenseTypeSearchBar/ExpenseTypeSearchBar.js
  packages/apps/hr/src/components/templates/ToggleSwitchMode/ToggleSwitchMode.js
  packages/ui/src/components/atoms/RadioButton/RadioButton.tsx
  packages/ui/src/components/atoms/Switch/Switch.tsx
  packages/ui/src/components/molecules/RadioSelect/RadioSelect.tsx
  packages/ui/src/components/molecules/SwitchCard/SwitchCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#549 fix: reverse icon password order
  changelogs/unreleased/78631.json
  packages/core/src/sessions/components/inputs/PasswordInput.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#520 fix: add indicator when no Data on picker
  changelogs/unreleased/78121.json
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/__tests__/components/molecules/SelectionContainer.test.js
  packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
  packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#544 fix: add header actions in active intervention screen
  packages/apps/intervention/src/hooks/use-intervention-header-actions.ts
  packages/apps/intervention/src/screens/intervention/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#550 fix: custom field form do not consider value when field type does not contain attrs
  changelogs/unreleased/78043.json
  packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx
  packages/core/src/forms/studio/formula.helpers.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#554 feat: use new selections system on manufacturing
  changelogs/unreleased/78691.json
  packages/apps/manufacturing/src/api/manufacturing-order-api.js
  packages/apps/manufacturing/src/api/operation-order-api.js
  packages/apps/manufacturing/src/components/molecules/ManufacturingOrderDatesCard/ManufacturingOrderDatesCard.tsx
  packages/apps/manufacturing/src/components/molecules/OperationOrderDatesCard/OperationOrderDatesCard.tsx
  packages/apps/manufacturing/src/components/organisms/LinkedManufacturingOrderCard/LinkedManufacturingOrderCard.tsx
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderButtons/ManufacturingOrderButtons.js
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderCard/ManufacturingOrderCard.tsx
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderHeader/ManufacturingOrderHeader.tsx
  packages/apps/manufacturing/src/components/organisms/OperationOrderCard/OperationOrderCard.tsx
  packages/apps/manufacturing/src/components/organisms/OperationOrderDetailsCard/OperationOrderDetailsCard.tsx
  packages/apps/manufacturing/src/components/organisms/OperationOrderHeader/OperationOrderHeader.tsx
  packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js
  packages/apps/manufacturing/src/index.ts
  packages/apps/manufacturing/src/models/index.ts
  packages/apps/manufacturing/src/models/typeObjects.ts
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderOperationListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ChildrenManufOrderListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductDetailsScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductDetailsScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductListScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderPlanningScreen.js
  packages/apps/manufacturing/src/types/manufacturing-order.tsx
  packages/apps/manufacturing/src/types/operation-order.tsx
  packages/apps/manufacturing/src/utils/dates.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#555 refactor: use new selections system on crm
  changelogs/unreleased/78686.json
  packages/apps/crm/src/components/molecules/CatalogCard/CatalogCard.tsx
  packages/apps/crm/src/components/molecules/EventCard/EventCard.tsx
  packages/apps/crm/src/components/molecules/LeadsCard/LeadsCard.tsx
  packages/apps/crm/src/components/molecules/OpportunityCard/OpportunityCard.tsx
  packages/apps/crm/src/components/molecules/PartnerCard/PartnerCard.tsx
  packages/apps/crm/src/components/molecules/PlanningEventCard/PlanningEventCard.tsx
  packages/apps/crm/src/components/organisms/Event/EventHeader/EventHeader.js
  packages/apps/crm/src/components/organisms/Event/EventLeadCard/EventLeadCard.js
  packages/apps/crm/src/components/organisms/Lead/LeadHeader/LeadHeader.js
  packages/apps/crm/src/components/organisms/Opportunity/OpportunityHeader/OpportunityHeader.js
  packages/apps/crm/src/components/organisms/Prospect/ProspectHeader/ProspectHeader.js
  packages/apps/crm/src/components/templates/CivilityPicker/CivilityPicker.tsx
  packages/apps/crm/src/components/templates/EventStatusPicker/EventStatusPicker.js
  packages/apps/crm/src/components/templates/EventTypePicker/EventTypePicker.js
  packages/apps/crm/src/hooks/index.ts
  packages/apps/crm/src/hooks/use-civility-list.ts
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
  packages/apps/crm/src/index.ts
  packages/apps/crm/src/models/index.ts
  packages/apps/crm/src/models/typeObjects.ts
  packages/apps/crm/src/screens/catalog/CatalogListScreen.js
  packages/apps/crm/src/screens/event/EventFormScreen.js
  packages/apps/crm/src/screens/event/EventPlanningScreen.js
  packages/apps/crm/src/screens/lead/LeadDetailsScreen.js
  packages/apps/crm/src/screens/lead/LeadFormScreen.js
  packages/apps/crm/src/screens/lead/LeadListScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js
  packages/apps/crm/src/screens/prospect/ProspectDetailsScreen.js
  packages/apps/crm/src/screens/prospect/ProspectsListScreen.js
  packages/apps/crm/src/types/catalog.tsx
  packages/apps/crm/src/types/event-type.ts
  packages/apps/crm/src/types/index.ts
  packages/apps/crm/src/types/lead.tsx
  packages/apps/crm/src/types/opportunity.ts
  packages/apps/crm/src/types/prospect.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#556 refactor: use new selections system on helpdesk
  changelogs/unreleased/78689.json
  packages/apps/helpdesk/src/components/molecules/TicketCard/TicketCard.tsx
  packages/apps/helpdesk/src/components/templates/TicketHeader/TicketHeader.js
  packages/apps/helpdesk/src/components/templates/TicketPriorityPicker/TicketPriorityPicker.js
  packages/apps/helpdesk/src/index.ts
  packages/apps/helpdesk/src/models/index.ts
  packages/apps/helpdesk/src/models/typeObjects.ts
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
  packages/apps/helpdesk/src/types/ticket.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#557 refactor: use new selections system on hr
  changelogs/unreleased/78687.json
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/api/timesheet-api.js
  packages/apps/hr/src/components/atoms/ExpenseCard/ExpenseCard.tsx
  packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx
  packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
  packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx
  packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx
  packages/apps/hr/src/components/templates/ExpenseHeader/ExpenseHeader.tsx
  packages/apps/hr/src/components/templates/ExpenseLineSwitchAdd/ExpenseLineSwitchAdd.tsx
  packages/apps/hr/src/components/templates/KilometricTypeSelectPicker/KilometricTypeSelectPicker.js
  packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx
  packages/apps/hr/src/components/templates/TimesheetFilters/TimesheetFilters.js
  packages/apps/hr/src/index.ts
  packages/apps/hr/src/models/forms.ts
  packages/apps/hr/src/models/index.ts
  packages/apps/hr/src/models/typeObjects.ts
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
  packages/apps/hr/src/screens/expense/ExpenseListScreen.js
  packages/apps/hr/src/screens/timesheet/TimerListScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js
  packages/apps/hr/src/types/expense.tsx
  packages/apps/hr/src/types/expenseLine.tsx
  packages/apps/hr/src/types/time.ts
  packages/apps/hr/src/types/timesheet.ts
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#560 fix: disable stop button when timer is paused
  changelogs/unreleased/79177.json
  packages/apps/manufacturing/src/components/organisms/OperationOrderStopwatch/OperationOrderStopwatch.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#559 fix: in progress chip displayed in two lines
  changelogs/unreleased/78932.json
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#564 fix: date input crash after emptying
  changelogs/unreleased/79224.json
  packages/core/src/components/pages/FormView/Components/Field.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#563 fix: increment input issue when null value
  changelogs/unreleased/79211.json
  packages/ui/src/components/molecules/Increment/Increment.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#566 fix: hide keyboard when click outside of inputs in KeyboardAvoidingScrollView
  changelogs/unreleased/79225.json
  packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#547 feat: create projects list view
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/project-api.js
  packages/apps/project/src/components/atoms/ProjectCard/ProjectCard.tsx
  packages/apps/project/src/components/atoms/index.ts
  packages/apps/project/src/components/index.ts
  packages/apps/project/src/components/templates/ProjectListView/ProjectListView.tsx
  packages/apps/project/src/components/templates/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/index.js
  packages/apps/project/src/features/projectSlice.js
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/index.ts
  packages/apps/project/src/models/index.ts
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/models/searchFields.ts
  packages/apps/project/src/models/sortFields.ts
  packages/apps/project/src/screens/BuisnessProjectScreen.tsx
  packages/apps/project/src/screens/ProjectScreen.tsx
  packages/apps/project/src/screens/index.ts
  packages/core/src/auth/models/objectFields.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#569 fix: prevent display of empty badge when priority doesn't exist
  changelogs/unreleased/78935.json
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderCard/ManufacturingOrderCard.tsx
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderHeader/ManufacturingOrderHeader.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#543 refactor: remove loading on ScrollList
  changelogs/unreleased/75768.json
  packages/ui/__tests__/components/organisms/ScrollList.test.js
  packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#577 fix: infinite loading after deleting an expense line
  changelogs/unreleased/79535.json
  packages/apps/hr/src/features/expenseLineSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#578 fix: on iOS HeaderBandList is on the status bar
  changelogs/unreleased/79670.json
  packages/core/src/components/organisms/HeaderBandList/HeaderBandList.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#576 fix: Contact DropdownCard cannot be open in ContactDetailsScreen
  packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#575 fix: sometimes address is write with only one d
  changelogs/unreleased/79586.json
  packages/apps/crm/src/components/molecules/PartnerCard/PartnerCard.tsx
  packages/apps/crm/src/components/organisms/Contact/ContactPartnerCard/ContactPartnerCard.js
  packages/apps/crm/src/components/organisms/DropdownContactPartnerView/DropdownContactPartnerView.js
  packages/apps/crm/src/components/organisms/DropdownContactView/DropdownContactView.tsx
  packages/apps/crm/src/components/organisms/Event/EventPartnerCard/EventPartnerCard.js
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
  packages/apps/crm/src/models/forms.ts
  packages/apps/crm/src/screens/client/ClientsListScreen.js
  packages/apps/crm/src/screens/contact/ContactListScreen.js
  packages/apps/crm/src/screens/prospect/ProspectsListScreen.js
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryMovementIndicationCard/CustomerDeliveryMovementIndicationCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalMovementIndicationCard/SupplierArrivalMovementIndicationCard.tsx
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#571 fix: refresh issue on NotesCard component
  changelogs/unreleased/79427.json
  packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#561 feat: add task view on ProjectDetailsScreen
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/project-task-api.js
  packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx
  packages/apps/project/src/components/atoms/index.ts
  packages/apps/project/src/components/molecules/TaskActionCard/TaskActionCard.tsx
  packages/apps/project/src/components/molecules/TaskFilters/TaskFilters.tsx
  packages/apps/project/src/components/molecules/index.ts
  packages/apps/project/src/components/pages/TaskView/TaskView.tsx
  packages/apps/project/src/components/pages/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/index.js
  packages/apps/project/src/features/projectTaskSlice.js
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/models/searchFields.ts
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟
