Repository axelor/axelor-mobile, pull requests merged in 2024-01, with the labels that each got.

#319 fix : add new slice for myTeamTicket to avoid refresh issue
  packages/apps/helpdesk/src/components/templates/MyTeamTicketSearchBar/MyTeamTicketSearchBar.js
  packages/apps/helpdesk/src/components/templates/MyTicketSearchBar/MyTicketSearchBar.js
  packages/apps/helpdesk/src/components/templates/index.js
  packages/apps/helpdesk/src/features/asyncFunctions-index.ts
  packages/apps/helpdesk/src/features/ticketSlice.js
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#316 feat: match input display to AOPv7 design
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/ui/__tests__/components/molecules/CircleButton.test.js
  packages/ui/src/components/molecules/CircleButton/CircleButton.tsx
  packages/ui/src/components/molecules/IconInput/IconInput.tsx
  packages/ui/src/components/molecules/Label/Label.tsx
  packages/ui/src/components/molecules/MessageBox/MessageBox.tsx
  packages/ui/src/components/molecules/NotesCard/NotesCard.tsx
  packages/ui/src/components/molecules/RightIconButton/RightIconButton.tsx
  packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
  packages/ui/src/utils/commons-styles.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#340 refactor: delete unused component CarrierCard
  packages/apps/stock/src/components/molecules/CarrierCard/CarrierCard.tsx
  packages/apps/stock/src/components/molecules/index.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#339 fix: display issue on ToggleSwitch due to new input design
  packages/ui/src/components/molecules/ToggleSwitch/ToggleSwitch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#335 feat: add test cases for MultiValuePicker component
  packages/ui/__tests__/components/organisms/MultiValuePicker.test.js
  packages/ui/src/utils/list.tsx
  packages/ui/stories/organisms/MultiValuePicker.stories.tsx
Labels: 🪄 Test, ✅ Done, Approved 🌟

#341 fix: avoid page reset when the next is loading
  packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
Labels: 🐛 Bug, ✅ Done

#348 fix: change icons of stock correction buttons
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionButtons/StockCorrectionButtons.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#352 fix: customized menu props name and issue on subMenus generation
  packages/core/src/api/menu-config-api.ts
  packages/core/src/navigator/Navigator.js
  packages/core/src/navigator/module.helper.ts
Labels: 🐛 Bug, ✅ Done

#350 refactor: remove FontAwesome5 props
  docs/doc/en/Application/Creation_d_un_ecran.md
  docs/doc/en/Application/Creation_d_un_module.md
  docs/doc/en/Application/Gestion_des_composants.md
  docs/doc/en/Outil/Gestion_des_headers.md
  docs/doc/fr/Application/Creation_d_un_ecran.md
  docs/doc/fr/Application/Creation_d_un_module.md
  docs/doc/fr/Application/Gestion_des_composants.md
  docs/doc/fr/Outil/Gestion_des_headers.md
  packages/ui/__tests__/components/atoms/Icon.test.js
  packages/ui/src/components/atoms/Icon/Icon.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#346 feat: apply default configurations on ChipSelect uses
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderOperationListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ChildrenManufOrderListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/core/src/components/templates/AttachedFilesView/AttachedFilesView.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#336 feat: create DurationInput component
  packages/ui/__tests__/components/molecules/NumberChevronInput.test.js
  packages/ui/__tests__/components/organisms/DurationInput.test.js
  packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/src/components/organisms/DurationInput/DurationInput.tsx
  packages/ui/src/components/organisms/DurationInput/duration.helpers.ts
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/molecules/NumberChevronInput.stories.tsx
  packages/ui/stories/organisms/DurationInput.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#338 fix: transform primaryColor to successColor
  packages/apps/crm/src/types/event-type.ts
  packages/apps/helpdesk/src/components/templates/TicketsStatusButton/TicketsStatusButton.js
  packages/apps/helpdesk/src/types/ticket.tsx
  packages/apps/hr/src/types/expense.tsx
  packages/apps/manufacturing/src/components/organisms/ConsumedProductCard/ConsumedProductCard.tsx
  packages/apps/manufacturing/src/components/organisms/ProducedProductCard/ProducedProductCard.tsx
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductListScreen.js
  packages/apps/manufacturing/src/types/manufacturing-order.tsx
  packages/apps/manufacturing/src/types/operation-order.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx
  packages/apps/stock/src/components/templates/inventory/InventoryLineCard/InventoryLineCard.tsx
  packages/apps/stock/src/components/templates/product/ProductCard/ProductCard.tsx
  packages/apps/stock/src/components/templates/product/ProductStockLocationCard/ProductStockLocationCard.tsx
  packages/apps/stock/src/components/templates/product/ProductVariantCard/ProductVariantCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/products/ProductStockLocationDetailsScreen.js
  packages/apps/stock/src/types/inventory.tsx
  packages/apps/stock/src/types/stock-corrrection.tsx
  packages/apps/stock/src/types/stock-move-line.tsx
  packages/apps/stock/src/types/stock-move.tsx
  packages/core/src/components/molecules/MailMessageReadIcon/MailMessageReadIcon.js
  packages/core/src/types/stopwatch-type.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#357 feat: add buttonsContainerStyle props to Alert component
  packages/ui/src/components/molecules/Alert/Alert.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#351 feat: manage new request to get user authorizations
  packages/core/src/api/menu-config-api.ts
  packages/core/src/api/mobile-config-api.ts
  packages/core/src/config/routes.js
  packages/core/src/features/index.js
  packages/core/src/features/menuConfigSlice.js
  packages/core/src/features/mobileConfigSlice.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/navigator/Navigator.js
  packages/core/src/navigator/menu.helper.js
  packages/core/src/navigator/module.helper.ts
  packages/core/src/navigator/roles.helper.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#363 fix: refresh issue on form fields when multiple uses of associated hook
  packages/core/src/forms/FormConfigsProvider.ts
Labels: 🐛 Bug, ✅ Done

#347 feat: add MenuSeparator
  packages/core/src/app/Module.ts
  packages/core/src/navigator/drawer/MenuItem.js
  packages/core/src/navigator/drawer/MenuSeparator.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#358 fix: refactor NumberChevronInput to avoid duplicate code
  packages/ui/__tests__/components/molecules/NumberChevronInput.test.js
  packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx
  packages/ui/stories/molecules/NumberChevronInput.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#360 fix: make the labelField props not required on Picker component
  packages/ui/src/components/organisms/Picker/Picker.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#353 feat: manage new configuration for default stock location
  packages/apps/stock/src/screens/auth/UserScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#355 fix: internet connection issue
  packages/core/src/app/RootNavigator.js
  packages/core/src/header/hooks.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#365 feat: add props on DateInput to put selection container on full screen
  packages/core/src/components/organisms/DateInput/DateInput.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#373 refactor : move DateDisplay in core module
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx
  packages/apps/hr/src/components/atoms/index.js
  packages/core/src/components/molecules/DateDisplay/DateDisplay.tsx
  packages/core/src/components/molecules/index.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#349 feat: add assignation filter on calendar
  packages/core/src/components/external/PlanningView/PlanningView.tsx
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#359 refactor: use DurationInput in DurationFormInput
  packages/apps/helpdesk/src/components/molecules/DurationFormInput/DurationFormInput.tsx
  packages/apps/helpdesk/src/components/molecules/DurationFormInput/duration.helpers.ts
  packages/apps/helpdesk/src/components/molecules/index.js
  packages/apps/helpdesk/src/models/forms.ts
  packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx
  packages/ui/src/components/organisms/DurationInput/DurationInput.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#375 feat: fetch active timer when coming from menu entry
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/timerSlice.js
  packages/apps/hr/src/hooks/use-hr-header-actions.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/models/sortFields.ts
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
  packages/apps/hr/src/screens/timesheet/TimerListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#362 feat: add ControlEntryListScreen
  packages/apps/quality/src/api/control-entry-api.js
  packages/apps/quality/src/api/control-entry-sample-api.js
  packages/apps/quality/src/api/index.ts
  packages/apps/quality/src/components/atoms/ControlEntryCard/ControlEntryCard.tsx
  packages/apps/quality/src/components/atoms/index.js
  packages/apps/quality/src/components/index.js
  packages/apps/quality/src/features/asyncFunctions-index.ts
  packages/apps/quality/src/features/controlEntrySlice.js
  packages/apps/quality/src/features/index.js
  packages/apps/quality/src/hooks/use-quality-header-actions.ts
  packages/apps/quality/src/i18n/en.json
  packages/apps/quality/src/i18n/fr.json
  packages/apps/quality/src/index.ts
  packages/apps/quality/src/models/index.ts
  packages/apps/quality/src/models/objectFields.ts
  packages/apps/quality/src/models/searchFields.ts
  packages/apps/quality/src/models/sortFields.ts
  packages/apps/quality/src/screens/ControlEntryListScreen.js
  packages/apps/quality/src/screens/index.js
  packages/apps/quality/src/types/controlEntry.tsx
  packages/apps/quality/src/types/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#371 feat: link TimesheeLine to form view
  packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx
  packages/apps/hr/src/models/forms.ts
  packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#381 feat: automatically fill timer activity with employee configuration
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#380 feat: manage custom status on Ticket
  packages/apps/helpdesk/src/api/index.ts
  packages/apps/helpdesk/src/api/ticket-api.js
  packages/apps/helpdesk/src/components/molecules/TicketCard/TicketCard.tsx
  packages/apps/helpdesk/src/components/templates/TicketHeader/TicketHeader.js
  packages/apps/helpdesk/src/components/templates/TicketStatusButton/TicketStatusButton.js
  packages/apps/helpdesk/src/components/templates/TicketStatusSearchBar/TicketStatusSearchBar.tsx
  packages/apps/helpdesk/src/components/templates/TicketStopwatch/TicketStopwatch.js
  packages/apps/helpdesk/src/components/templates/index.js
  packages/apps/helpdesk/src/features/asyncFunctions-index.ts
  packages/apps/helpdesk/src/features/ticketSlice.js
  packages/apps/helpdesk/src/i18n/en.json
  packages/apps/helpdesk/src/i18n/fr.json
  packages/apps/helpdesk/src/models/forms.ts
  packages/apps/helpdesk/src/models/objectFields.ts
  packages/apps/helpdesk/src/models/searchFields.ts
  packages/apps/helpdesk/src/models/sortFields.ts
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
  packages/apps/helpdesk/src/screens/TicketDetailsScreen.js
  packages/apps/helpdesk/src/screens/TicketFormScreen.js
  packages/apps/helpdesk/src/types/ticket.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#383 feat: add managament of time and status on TimerStopwtach
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/components/molecules/TimerStopwatch/TimerStopwatch.tsx
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/timerSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/models/forms.ts
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
  packages/apps/hr/src/screens/timesheet/TimerListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#384 feat: take into account configuration for timer and timesheet line fi…
  packages/apps/hr/src/models/forms.ts
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js
  packages/apps/hr/src/types/timesheet.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟
