Repository axelor/axelor-mobile, pull requests merged in 2024-11, with the labels that each got.

#784 fix: display mail messages chips on one line
  changelogs/unreleased/86450.json
  changelogs/unreleased/86450_chips.json
  packages/core/src/components/templates/MailMessageView/MailMessageView.js
  packages/ui/src/components/molecules/Chip/Chip.tsx
  packages/ui/src/components/organisms/ChipSelect/ChipSelect.tsx
Labels: 🐛 Bug, ✅ Done

#786 fix: trigger period computation on Timesheet update
  changelogs/unreleased/86455.json
  packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx
Labels: 🐛 Bug, ✅ Done

#787 fix: Session export
  changelogs/unreleased/86477.json
  packages/core/src/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#785 fix: improve style on creation screen
  changelogs/unreleased/86448.json
  packages/apps/stock/src/screens/internalMoves/InternalMoveCreationScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionCreationScreen.js
  packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#789 fix: cannot delete expense and expense line
  changelogs/unreleased/86499.json
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
  packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#791 feat: add possibility to define generic header actions
  changelogs/unreleased/86253.json
  docs/doc/en/Outil/Gestion_des_headers.md
  docs/doc/fr/Outil/Gestion_des_headers.md
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/core/src/header/HeaderActionsProvider.ts
  packages/core/src/header/types.ts
  packages/core/src/navigator/drawer/Header.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#783 fix: hide navigation bar when keyboard disappear
  changelogs/unreleased/86451.json
  packages/ui/src/components/atoms/Screen/Screen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#799 feat: create package @axelor/aos-mobile-dms
  package.json
  packages/apps/dms/.eslintrc.js
  packages/apps/dms/.gitignore
  packages/apps/dms/.prettierrc.js
  packages/apps/dms/README.md
  packages/apps/dms/babel.config.js
  packages/apps/dms/package.json
  packages/apps/dms/src/i18n/en.json
  packages/apps/dms/src/i18n/fr.json
  packages/apps/dms/src/index.ts
  packages/apps/dms/tsconfig.build.json
  packages/apps/dms/tsconfig.json
  src/App.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#796 feat: add management of M2M and M2O fields on custom fields form
  changelogs/unreleased/85710.json
  packages/core/src/components/pages/FormView/Custom/CustomTagList.tsx
  packages/core/src/components/pages/FormView/Custom/index.ts
  packages/core/src/forms/studio/api.helpers.ts
  packages/core/src/forms/studio/display.helpers.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#801 fix: remove add button on expense line form
  changelogs/unreleased/86812.json
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#800 fix: actions display issue on ActionCard
  changelogs/unreleased/86811.json
  packages/ui/src/components/organisms/ActionCard/ActionCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#805 fix: add missing exports for reducers on hr
  changelogs/unreleased/87053.json
  packages/apps/hr/src/features/asyncFunctions-index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#806 fix: issue on increment input on iOS
  changelogs/unreleased/86962.json
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/src/components/molecules/Increment/Increment.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#802 feat: authorize geolocation for webView
  android/app/src/main/AndroidManifest.xml
  changelogs/unreleased/86837.json
  ios/AosMobile/Info.plist
  packages/core/src/components/external/WebView/WebView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#809 fix: replace get by createStandardSearch
  changelogs/unreleased/87258.json
  packages/core/src/api/meta-module-api.ts
  packages/core/src/models/objectFields.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#804 fix: improve session refresh on input with unique mode
  changelogs/unreleased/87049.json
  packages/core/src/sessions/components/inputs/SessionInputs.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#811 fix: API path used for adding tracking number
  changelogs/unreleased/87305.json
  packages/apps/stock/src/api/tracking-number-api.js
Labels: 🐛 Bug, ✅ Done

#807 feat: add autoselect on focus
  changelogs/unreleased/86572.json
  packages/ui/src/components/molecules/Increment/Increment.tsx
  packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#810 fix: display issue on BranchCard
  changelogs/unreleased/87288.json
  packages/ui/src/components/templates/TreeView/BranchCard.tsx
Labels: 🐛 Bug, ✅ Done, Pair approved 🌟

#816 fix: reduce number of calls for print action
  changelogs/unreleased/87597.json
  packages/core/src/header/hooks.js
Labels: 🐛 Bug, ✅ Done

#803 feat: add Breadcrumb on SearchTreeView
  changelogs/unreleased/86490_Breadcrumb.json
  changelogs/unreleased/86490_SearchTreeView.json
  packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
  packages/ui/__tests__/components/molecules/Breadcrumb.test.js
  packages/ui/src/components/molecules/Breadcrumb/Breadcrumb.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/stories/molecules/Breadcrumb.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#815 feat: add possibility to define default value for parent filter on TreeView
  changelogs/unreleased/86491.json
  packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#812 fix: improve display of warning error
  changelogs/unreleased/87274.json
  changelogs/unreleased/87274_CardIndicator.json
  changelogs/unreleased/87274_InfoBubble.json
  packages/core/src/navigator/drawer/DrawerContent.js
  packages/core/src/navigator/drawer/MenuIconButton.js
  packages/ui/__tests__/components/molecules/CardIndicator.test.js
  packages/ui/__tests__/components/organisms/InfoBubble.test.js
  packages/ui/src/components/molecules/CardIndicator/CardIndicator.tsx
  packages/ui/src/components/organisms/InfoBubble/InfoBubble.tsx
  packages/ui/stories/molecules/CardIndicator.stories.tsx
  packages/ui/stories/organisms/InfoBubble.stories.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#814 refactor: manage format on blur/focus on the Increment input
  changelogs/unreleased/87393.json
  packages/ui/src/components/molecules/Increment/Increment.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟
