Repository axelor/axelor-mobile, pull requests merged in 2024-12, with the labels that each got.

#824 fix: manage margin bottom on AutoCompleteSearch when list is empty
  changelogs/unreleased/87262.json
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
Labels: 🐛 Bug, ✅ Done

#823 fix: issue on save for the Increment value on form
  changelogs/unreleased/87714.json
  packages/ui/src/components/molecules/Increment/Increment.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#822 feat: add possibility to use async functions on generic action
  changelogs/unreleased/87876.json
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/core/src/header/types.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#818 feat: create favorites files screen
  packages/apps/dms/src/api/document-api.js
  packages/apps/dms/src/features/documentSlice.js
  packages/apps/dms/src/i18n/en.json
  packages/apps/dms/src/i18n/fr.json
  packages/apps/dms/src/screens/MyFavoriteDocumentsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#827 fix: filter issue with chips on DocumentList
  packages/apps/dms/src/api/document-api.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#819 feat: add RequestListView
  packages/apps/purchase/src/api/index.ts
  packages/apps/purchase/src/api/purchase-request-api.js
  packages/apps/purchase/src/api/supplier-api.js
  packages/apps/purchase/src/components/atoms/RequestCard/RequestCard.tsx
  packages/apps/purchase/src/components/atoms/index.ts
  packages/apps/purchase/src/components/index.ts
  packages/apps/purchase/src/components/templates/SupplierSearchBar/SupplierSearchBar.tsx
  packages/apps/purchase/src/components/templates/index.ts
  packages/apps/purchase/src/features/asyncFunctions-index.ts
  packages/apps/purchase/src/features/index.js
  packages/apps/purchase/src/features/purchaseRequestSlice.js
  packages/apps/purchase/src/features/supplierSlice.js
  packages/apps/purchase/src/i18n/en.json
  packages/apps/purchase/src/i18n/fr.json
  packages/apps/purchase/src/index.ts
  packages/apps/purchase/src/models/index.ts
  packages/apps/purchase/src/models/objectFields.ts
  packages/apps/purchase/src/models/searchFields.ts
  packages/apps/purchase/src/models/sortFields.ts
  packages/apps/purchase/src/models/typeObjects.ts
  packages/apps/purchase/src/screens/RequestListScreen.tsx
  packages/apps/purchase/src/screens/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#830 feat: add action on leave request
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/api/leave-api.js
  packages/apps/hr/src/components/molecules/LeaveActionCard/LeaveActionCard.tsx
  packages/apps/hr/src/components/molecules/LeaveDetailsButtons/LeaveDetailsButtons.tsx
  packages/apps/hr/src/components/templates/LeaveRefusalPopup/LeaveRefusalPopup.tsx
  packages/apps/hr/src/components/templates/index.js
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/leaveSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx
  packages/apps/hr/src/screens/leaveRequests/LeaveListScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#833 feat: create generic criteria to manage company
  changelogs/unreleased/88234.json
  packages/core/src/apiProviders/Model/utils.ts
  packages/core/src/apiProviders/Standard/requests.helper.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#838 feat: add props isHideableParentSearch on SearchTreeView
  changelogs/unreleased/88276.json
  packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#845 fix: remove default domain
  packages/core/src/apiProviders/Standard/requests.helper.ts
Labels: 🐛 Bug, ✅ Done

#821 feat: manage attached files header action
  packages/apps/dms/src/api/document-api.js
  packages/apps/dms/src/api/index.ts
  packages/apps/dms/src/hooks/use-dms-header-actions.ts
  packages/apps/dms/src/i18n/en.json
  packages/apps/dms/src/i18n/fr.json
  packages/apps/dms/src/models/forms.ts
  packages/apps/dms/src/screens/AttachedFilesScreen.tsx
  packages/apps/dms/src/screens/DocumentFormScreen.tsx
  packages/apps/dms/src/screens/index.ts
  packages/apps/dms/src/utils/attachedFilesGenericAction.ts
  packages/apps/dms/src/utils/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#843 refactor: transform attachedFileScreenTitle into options in headerActionsProvider
  changelogs/unreleased/88563.json
  packages/apps/crm/src/hooks/use-crm-header-actions.ts
  packages/apps/helpdesk/src/hooks/use-helpdesk-header-actions.ts
  packages/apps/intervention/src/hooks/use-intervention-header-actions.ts
  packages/apps/project/src/hooks/use-project-header-actions.ts
  packages/apps/sale/src/hooks/use-sale-header-actions.ts
  packages/apps/stock/src/hooks/use-stock-header-actions.js
Labels: 🔧 Refactor, ✅ Done

#848 fix: issue on inventory line creation
  changelogs/unreleased/88623.json
  packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js
  packages/apps/stock/src/screens/inventories/InventoryLineDetailsScreen.js
Labels: 🐛 Bug, ✅ Done

#846 fix: refresh issue on calendar
  changelogs/unreleased/88597.json
  patches/react-native-calendars+1.1306.0.patch
Labels: 🐛 Bug, ✅ Done, Pair approved 🌟

#837 feat: add possibility to create an event from the planning view
  changelogs/unreleased/87524.json
  packages/apps/crm/src/features/eventSlice.js
  packages/apps/crm/src/screens/event/EventFormScreen.js
  packages/apps/crm/src/screens/event/EventPlanningScreen.js
  packages/apps/crm/src/screens/event/index.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#849 feat: impove attached files screen
  changelogs/unreleased/88612_SearchTreeView.json
  changelogs/unreleased/88612_TreeView.json
  packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
  packages/apps/dms/src/screens/AttachedFilesScreen.tsx
  packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
  packages/ui/__tests__/components/molecules/Breadcrumb.test.js
  packages/ui/src/components/molecules/Breadcrumb/Breadcrumb.tsx
  packages/ui/src/components/templates/TreeView/Branch.tsx
  packages/ui/src/components/templates/TreeView/BranchCard.tsx
  packages/ui/src/components/templates/TreeView/TreeView.tsx
  packages/ui/stories/molecules/Breadcrumb.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#836 fix: contact and partner mutually dependent
  changelogs/unreleased/88244.json
  packages/apps/crm/src/api/contact-api.js
  packages/apps/crm/src/components/templates/ContactSearchBar/ContactSearchBar.tsx
  packages/apps/crm/src/features/asyncFunctions-index.ts
  packages/apps/crm/src/features/partnerSlice.js
  packages/apps/crm/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#853 refactor: use props isHideableParentSearch on DocumentList
  packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#855 refactor: filter action should not be large on BranchCard
  packages/ui/src/components/templates/TreeView/BranchCard.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#842 feat: add split lines customer delivery
  changelogs/unreleased/88324.json
  packages/apps/stock/src/api/customer-delivery-line-api.js
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineActionCard/CustomerDeliveryLineActionCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js
  packages/apps/stock/src/components/templates/customerDelivery/index.js
  packages/apps/stock/src/features/asyncFunctions-index.ts
  packages/apps/stock/src/features/customerDeliveryLineSlice.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟
