Repository axelor/axelor-mobile, pull requests merged in 2024-09, with the labels that each got.

#690 fix: refresh issue
  packages/apps/project/src/components/templates/ActivityListView/ActivityListView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#682 feat: add CartLine details screen
  packages/apps/sale/src/api/cart-line-api.js
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/components/atoms/CartLineCard/CartLineCard.tsx
  packages/apps/sale/src/components/molecules/CartLineActionCard/CartLineActionCard.tsx
  packages/apps/sale/src/components/molecules/CartLinePriceDetails/CartLinePriceDetails.tsx
  packages/apps/sale/src/components/molecules/CartLineValidationButton/CartLineValidationButton.tsx
  packages/apps/sale/src/components/molecules/index.ts
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/cartLineSlice.js
  packages/apps/sale/src/hooks/use-sale-header-actions.ts
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/screens/cart/CartLineDetailsScreen.tsx
  packages/apps/sale/src/screens/cart/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#692 feat: improve TaskDetailsView
  packages/apps/project/src/components/atoms/TaskButton/TaskButton.tsx
  packages/apps/project/src/components/atoms/index.ts
  packages/apps/project/src/components/pages/TaskGeneralInformationView/TaskGeneralInformationView.tsx
  packages/apps/project/src/components/pages/index.ts
  packages/apps/project/src/screens/TaskDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#689 feat: add catalog screen
  packages/apps/sale/src/components/atoms/CartLineCard/CartLineCard.tsx
  packages/apps/sale/src/components/molecules/CatalogActionCard/CatalogActionCard.tsx
  packages/apps/sale/src/components/molecules/index.ts
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/index.ts
  packages/apps/sale/src/screens/cart/CatalogScreen.tsx
  packages/apps/sale/src/screens/cart/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#697 fix: border radius of content drodown card
  changelogs/unreleased/83949.json
  packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#698 fix: improve sale order line card
  packages/apps/sale/src/components/atoms/SaleOrderLineCard/SaleOrderLineCard.tsx
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#696 fix: hide timer depends on config
  changelogs/unreleased/83831.json
  packages/apps/hr/src/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#699 feat: add copy to clipboard on ComplementaryPriductCard
  packages/apps/sale/src/components/atoms/ComplementaryProductCard/ComplementaryProductCard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#700 feat: add new Item type for bottom bar
  changelogs/unreleased/83801.json
  packages/ui/src/components/templates/BottomBar/BottomBar.tsx
  packages/ui/src/components/templates/BottomBar/types.helper.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#703 feat: add placeHolder to picker with no title
  packages/apps/project/src/components/templates/ProjectListView/ProjectListView.tsx
  packages/apps/project/src/components/templates/TaskFilters/TaskFilters.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#701 feat: add pricelist inf in SaleOrder details
  packages/apps/sale/src/components/atoms/DropdownGeneralView/DropdownGeneralView.tsx
  packages/apps/sale/src/components/molecules/SaleOrderDropdownCards/SaleOrderDropdownCards.tsx
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/models/objectFields.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#705 feat: modify menu icon
  packages/apps/project/src/index.ts
Labels: 🌟 Feature, ✅ Done

#702 feat: improve project dates display
  packages/apps/project/src/components/atoms/DatesDisplay/DatesDisplay.tsx
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#706 feat: add new SingleSelectScrollList component
  changelogs/unreleased/83735.json
  packages/ui/__tests__/components/organisms/SingleSelectScrollList.test.js
  packages/ui/src/components/organisms/SingleSelectScrollList/SingleSelectScrollList.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/organisms/SingleSelectScrollList.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#707 feat: change trad validate cart
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
Labels: 🌟 Feature, ✅ Done

#691 feat: add customer alert on validation
  packages/apps/sale/src/api/cart-api.js
  packages/apps/sale/src/api/customer-api.js
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/components/molecules/CartHeader/CartHeader.tsx
  packages/apps/sale/src/components/molecules/ValidateCartPopup/ValidateCartPopup.tsx
  packages/apps/sale/src/components/molecules/index.ts
  packages/apps/sale/src/components/organisms/CustomerSearchBar/CustomerSearchBar.tsx
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/cartSlice.js
  packages/apps/sale/src/features/index.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#693 feat: add custom fields view on task
  changelogs/unreleased/83297_customFields.json
  changelogs/unreleased/83297_form.json
  changelogs/unreleased/83297_screen.json
  packages/apps/project/src/components/molecules/CustomFieldPopup/CustomFieldPopup.tsx
  packages/apps/project/src/components/molecules/SectionHeader/SectionHeader.tsx
  packages/apps/project/src/components/molecules/index.ts
  packages/apps/project/src/components/organisms/CustomSection/CustomSection.tsx
  packages/apps/project/src/components/organisms/index.ts
  packages/apps/project/src/components/pages/TaskCustomFieldsView/TaskCustomFieldsView.tsx
  packages/apps/project/src/components/pages/TaskGeneralInformationView/TaskGeneralInformationView.tsx
  packages/apps/project/src/components/pages/index.ts
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/screens/TaskDetailsScreen.tsx
  packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx
  packages/core/src/components/pages/FormView/Custom/CustomButton.tsx
  packages/core/src/components/pages/FormView/FormView.tsx
  packages/core/src/screens/JsonFieldScreen.tsx
  packages/ui/src/components/atoms/Screen/Screen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#717 feat: add API action on empty cart
  packages/apps/sale/src/api/cart-api.js
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/cartSlice.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#712 feat: add filters on products and services list view
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/api/product-api.js
  packages/apps/sale/src/components/organisms/ProductCategorySearchBar/ProductCategorySearchBar.tsx
  packages/apps/sale/src/components/organisms/index.ts
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/productSlice.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/models/objectFields.ts
  packages/apps/sale/src/models/searchFields.ts
  packages/apps/sale/src/screens/product/ProductSaleListScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#716 fix: hide tree view based on project config
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#715 fix: display issue on Sale order Adress
  packages/apps/sale/src/components/atoms/DropdownGeneralView/AdressLine.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#714 fix: Stopwatch use flewWrap to manage width issue
  changelogs/unrealesed/84375.json
  packages/core/src/components/external/Stopwatch/Stopwatch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#709 fix: put place holder for MultieValuePickerButton to one line
  changelogs/unreleased/84286.json
  packages/ui/src/components/molecules/MultiValuePickerButton/MultiValuePickerButton.tsx
  packages/ui/src/components/molecules/RightIconButton/RightIconButton.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#704 feat: add DropDownSaleOrderView
  changelogs/unreleased/83974.json
  packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js
  packages/apps/crm/src/components/organisms/DropdownOpportunityView/DropdownOpportunityView.tsx
  packages/apps/crm/src/utils/dateEvent.js
  packages/apps/crm/src/utils/index.ts
  packages/apps/crm/src/utils/list.js
  packages/apps/sale/src/components/organisms/DropDownSaleOrderView/DropDownSaleOrderView.tsx
  packages/apps/sale/src/components/organisms/index.ts
  packages/apps/sale/src/components/pages/SaleOrderListView/SaleOrderListView.tsx
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/screens/client/ClientSaleDetailsScreen.tsx
  packages/apps/sale/src/screens/saleOrder/SaleOrdersScreen.tsx
  packages/apps/sale/src/screens/saleOrder/SaleQuotationsScreen.tsx
  packages/core/src/utils/index.ts
  packages/core/src/utils/list.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#722 fix: camera issue on iOS
  changelogs/unreleased/84203.json
  packages/core/src/components/external/Camera/Camera.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#657 feat: add custom field for aop chart
  changelogs/unreleased/81372.json
  packages/core/src/components/pages/FormView/Custom/CustomPicker.tsx
  packages/core/src/components/pages/FormView/Custom/CustomSearchBar.tsx
  packages/core/src/dashboards/component/AOPChart/AOPChart.tsx
  packages/core/src/dashboards/component/AOPChart/DynamicSearchForm.tsx
  packages/core/src/forms/studio/api.helpers.ts
  packages/core/src/forms/studio/display.helpers.ts
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/src/utils/list.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#713 doc: add app customization
  docs/assets/en/android_app_icon.png
  docs/assets/en/android_configure_asset.png
  docs/assets/en/ios_app_icon.png
  docs/assets/fr/android_app_icon.png
  docs/assets/fr/android_configure_asset.png
  docs/assets/fr/ios_app_icon.png
  docs/doc/en/Application/buildCustomization.md
  docs/doc/fr/Application/buildCustomization.md
Labels: 📚 Documentation, ✅ Done

#723 refactor: improve badges display on SaleOrderDetails
  packages/apps/sale/src/components/molecules/SaleOrderHeader/SaleOrderHeader.tsx
Labels: 🔧 Refactor, ✅ Done, Pair approved 🌟

#727 feat: add component SingleSelectSearchListView
  changelogs/unreleased/83737.json
  packages/core/src/components/templates/SingleSelectSearchListView/SingleSelectSearchListView.tsx
  packages/core/src/components/templates/index.js
Labels: 🌟 Feature, ✅ Done

#720 feat: add possibility to display icon on Dropdown
  changelogs/unreleased/83854.json
  packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx
  packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#708 feat: add filter taskCategory in task filters
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/project-task-api.js
  packages/apps/project/src/components/pages/TaskView/TaskView.tsx
  packages/apps/project/src/components/templates/TaskFilters/TaskFilters.tsx
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/projectTaskSlice.js
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/screens/TaskListScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#719 feat: enable compsany update on Cart
  packages/apps/sale/src/api/cart-api.js
  packages/apps/sale/src/components/molecules/CartHeader/CartHeader.tsx
  packages/apps/sale/src/components/organisms/CustomerSearchBar/CustomerSearchBar.tsx
  packages/apps/sale/src/components/templates/CompanyPicker/CompanyPicker.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#729 fix: logout button out of card on user screen
  changelogs/unreleased/84677.json
  packages/core/src/auth/components/molecules/UserCard/UserCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#721 feat: enable line splitting on supplier arrival
  changelogs/unreleased/83875.json
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/api/supplier-arrival-line-api.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineActionCard/SupplierArrivalLineActionCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js
  packages/apps/stock/src/components/templates/supplierArrival/index.js
  packages/apps/stock/src/features/asyncFunctions-index.ts
  packages/apps/stock/src/features/supplierArrivalLineSlice.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#725 refactor: keep actions view open whenusing an action on CartLineActionCard
  packages/apps/sale/src/components/molecules/CartLineActionCard/CartLineActionCard.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#724 feat: add TaskLinkView
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/project-task-api.js
  packages/apps/project/src/components/atoms/TaskCard/TaskCard.tsx
  packages/apps/project/src/components/pages/TaskLinkView/TaskLinkView.tsx
  packages/apps/project/src/components/pages/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/projectTaskSlice.js
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/screens/TaskDetailsScreen.tsx
  packages/ui/src/components/organisms/GroupByScrollList/GroupByScrollList.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#733 fix: zIndex issue on CartHeader
  packages/apps/sale/src/components/molecules/CartHeader/CartHeader.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟
