Repository axelor/axelor-mobile, pull requests merged in 2024-02, with the labels that each got.

#386 feat: manage new mobile settings configurations for expenses
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.js
  packages/apps/hr/src/components/templates/ExpenseLineSwitchAdd/ExpenseLineSwitchAdd.tsx
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/hooks/use-hr-header-actions.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/expense/ExpenseDetailsScreen.js
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
  packages/apps/hr/src/screens/expense/index.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#388 feat: use Localization object for translations
  packages/core/src/auth/api/index.js
  packages/core/src/auth/api/localization-api.js
  packages/core/src/auth/features/asyncFunctionsIndex.js
  packages/core/src/auth/features/index.js
  packages/core/src/auth/features/localizationSlice.js
  packages/core/src/auth/i18n/en.json
  packages/core/src/auth/i18n/fr.json
  packages/core/src/auth/models/objectFields.ts
  packages/core/src/auth/screens/UserScreen.js
  packages/core/src/i18n/component/Translator.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#395 fix: hide delete button when TimesheetLine is linked to TSTimer
  packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#401 fix: number timesheet to validate refresh issue
  packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx
  packages/apps/hr/src/components/templates/TimesheetRefusalPopup/TimesheetRefusalPopup.tsx
  packages/apps/hr/src/features/timesheetSlice.js
  packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#400 fix: hide groundForRefusal when status is not refused on expenses and…
  packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx
  packages/apps/hr/src/components/templates/ExpenseHeader/ExpenseHeader.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#393 fix: return graph null when datalist is null
  packages/core/src/dashboards/view/DashboardScreen.tsx
  packages/ui/src/components/templates/Dashboard/Dashboard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#397 fix: replace delete button by cancel button and refactor code
  packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx
  packages/apps/hr/src/features/timesheetLineSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#398 fix: timesheet not refresh when modify
  packages/apps/hr/src/features/timesheetLineSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#394 fix: same start and end date on DatesInterval
  packages/apps/hr/src/components/atoms/DatesInterval/DatesInterval.tsx
  packages/core/src/utils/object.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#392 fix: change periodTotal to converted period in TimesheetDetailCard an…
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/api/timesheet-api.js
  packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#399 fix: can't re-open declare form after one declaration
  packages/apps/hr/src/components/templates/DraftTimesheetPicker/DraftTimesheetPicker.tsx
  packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx
  packages/apps/hr/src/features/timesheetSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#402 feat: add compatibility on Timesheet menus
  packages/apps/hr/src/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#396 feat: add manual creation of timesheet
  packages/apps/hr/src/components/molecules/TimesheetCreationAlert/TimesheetCreationAlert.tsx
  packages/apps/hr/src/components/molecules/TimesheetDetailsButtons/TimesheetDetailsButtons.tsx
  packages/apps/hr/src/components/molecules/index.js
  packages/apps/hr/src/features/timesheetSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js
  packages/apps/hr/src/screens/timesheet/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#403 fix: remove TouchableOpacity on control entry sample card
  packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#385 feat: add timer requests
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/components/molecules/TimerStopwatch/TimerStopwatch.tsx
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/timerSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
  packages/apps/hr/src/screens/timesheet/TimerListScreen.js
  packages/apps/hr/src/types/time.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#404 fix: filter only compatible menus for default module action
  packages/core/src/navigator/menu.helper.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#406 refactor: improve header action refresh management
  packages/core/src/header/HeaderActionsProvider.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#407 fix: add focusScreen on ControlEntryDetailsScreens
  packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx
  packages/apps/quality/src/screens/ControlEntryDetailsScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#412 feat: add refresh button header on ControlEntryDetails
  packages/apps/quality/src/components/molecules/ControlEntryDetailsHeader/ControlEntryDetailsHeader.tsx
  packages/apps/quality/src/hooks/use-quality-header-actions.ts
  packages/apps/quality/src/i18n/en.json
  packages/apps/quality/src/i18n/fr.json
  packages/apps/quality/src/screens/ControlEntryDetailsScreen.js
  packages/apps/quality/src/screens/index.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#405 fix: remove possibility to create control entry
  packages/apps/quality/src/hooks/use-quality-header-actions.ts
  packages/apps/quality/src/i18n/en.json
  packages/apps/quality/src/i18n/fr.json
  packages/apps/quality/src/screens/index.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#410 fix: update ControlEntryList when controlEntry is updated
  packages/apps/quality/src/api/control-entry-api.js
  packages/apps/quality/src/features/controlEntrySlice.js
  packages/apps/quality/src/screens/ControlEntryListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#411 feat: handleNext on validation button and pop when is last validation
  packages/apps/quality/src/screens/ControlEntryFormScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#415 fix: title props optional on DateInput
  packages/core/src/components/organisms/DateInput/DateInput.tsx
Labels: 🐛 Bug, ✅ Done, Pair approved 🌟

#417 refactor: remove isDefault on active timer screen
  packages/apps/hr/src/index.ts
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#413 feat: add status filter on list screen
  packages/apps/quality/src/api/control-entry-api.js
  packages/apps/quality/src/features/controlEntrySlice.js
  packages/apps/quality/src/screens/ControlEntryListScreen.js
  packages/apps/quality/src/types/controlEntry.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#414 feat: remove ToggleSwitch component and and enable props on planningView
  packages/apps/crm/src/screens/event/EventPlanningScreen.js
  packages/apps/crm/src/types/event-type.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#419 fix: remove style on DateInput and add width on ChipSelect on control…
  packages/apps/quality/src/screens/ControlEntryListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#421 feat: move component DatesInterval and rename it PeriodDisplay
  packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx
  packages/apps/hr/src/components/atoms/index.js
  packages/apps/hr/src/components/molecules/TimesheetHeader/TimesheetHeader.tsx
  packages/core/src/components/molecules/PeriodDisplay/PeriodDisplay.tsx
  packages/core/src/components/molecules/index.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#422 fix: inverse sort on list screen
  packages/apps/quality/src/models/sortFields.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#387 feat: add button to enable edit/read mode on studio form view
  packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx
  packages/core/src/components/pages/FormView/FormView.tsx
  packages/core/src/forms/types.ts
  packages/core/src/screens/JsonFieldScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#428 fix: add reset action on create ticket form
  packages/apps/helpdesk/src/screens/TicketFormScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#426 fix: issue with keyboard in mailMessage
  packages/core/src/components/templates/MailMessageView/MailMessageView.js
  packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#429 fix: change style EventCard
  packages/apps/crm/src/components/molecules/EventCard/EventCard.tsx
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#430 fix: losing header actions after navigation
  packages/core/src/header/HeaderActionsProvider.ts
  packages/core/src/navigator/drawer/Header.js
Labels: 🐛 Bug, 🚧 Doing

#432 fix: display issue on required error in FormView
  packages/core/src/components/pages/FormView/Components/Field.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#425 feat: add README and example for changelogs
  changelogs/README.md
  changelogs/changelog_example.json
Labels: 🌟 Feature, 🚧 Doing

#433 fix: change success to primary color on ToggleButton
  changelogs/unreleased/75640.json
  packages/apps/quality/src/screens/ControlEntryListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#436 fix: search shows too many results on list screens (crm and helpdesk)
  changelogs/unreleased/75492.json
  packages/apps/crm/src/components/templates/CatalogsSearchBar/CatalogsSearchBar.js
  packages/apps/crm/src/components/templates/ClientSearchBar/ClientSearchBar.js
  packages/apps/crm/src/components/templates/ContactSearchBar/ContactSearchBar.js
  packages/apps/crm/src/components/templates/LeadSearchBar/LeadSearchBar.js
  packages/apps/crm/src/components/templates/OpportunitySearchBar/OpportunitySearchBar.js
  packages/apps/crm/src/components/templates/ProspectSearchBar/ProspectSearchBar.js
  packages/apps/crm/src/screens/catalog/CatalogListScreen.js
  packages/apps/crm/src/screens/client/ClientsListScreen.js
  packages/apps/crm/src/screens/contact/ContactListScreen.js
  packages/apps/crm/src/screens/lead/LeadListScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js
  packages/apps/crm/src/screens/prospect/ProspectsListScreen.js
  packages/apps/helpdesk/src/components/templates/MyTeamTicketSearchBar/MyTeamTicketSearchBar.js
  packages/apps/helpdesk/src/components/templates/MyTicketSearchBar/MyTicketSearchBar.js
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#439 fix: conflict reducer name
  changelogs/unreleased/75733.json
  packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js
  packages/apps/helpdesk/src/components/templates/CustomerSearchBar/CustomerSearchBar.js
  packages/apps/helpdesk/src/components/templates/ProjectSearchBar/ProjectSearchBar.js
  packages/apps/helpdesk/src/components/templates/TicketStopwatch/TicketStopwatch.js
  packages/apps/helpdesk/src/features/customerSlice.js
  packages/apps/helpdesk/src/features/index.js
  packages/apps/helpdesk/src/features/projectSlice.js
  packages/apps/helpdesk/src/features/timerSlice.js
  packages/apps/hr/src/components/templates/ProductSearchBar/ProductSearchBar.tsx
  packages/apps/hr/src/components/templates/ProjectSearchBar/ProjectSearchBar.tsx
  packages/apps/hr/src/components/templates/ProjectTaskSearchBar/ProjectTaskSearchBar.tsx
  packages/apps/hr/src/features/index.js
  packages/apps/hr/src/features/projectSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#379 feat: add props on Loader to force user to leave screen
  packages/apps/stock/src/screens/loader/LoaderScreen.js
  packages/core/src/components/templates/Loader/LoaderPopup.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#390 feat: add loader header indicator
  packages/apps/stock/src/screens/loader/LoaderScreen.js
  packages/core/src/auth/hooks/use-auth-headers.js
  packages/core/src/components/templates/Loader/LoaderPopup.tsx
  packages/core/src/components/templates/Loader/ProcessProvider.ts
  packages/core/src/components/templates/Loader/index.ts
  packages/core/src/components/templates/Loader/use-loader-listener.ts
  packages/core/src/components/templates/Loader/use-process-register.ts
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#446 fix: rename chart.ts into chart-type.ts to allow mobile app to work on macOS
  changelogs/unreleased/76047.json
  packages/ui/src/components/templates/Dashboard/Chart/PieChart.tsx
  packages/ui/src/components/templates/Dashboard/Chart/chart.helper.ts
  packages/ui/src/components/templates/Dashboard/Dashboard.tsx
  packages/ui/src/components/templates/Dashboard/chart-type.ts
  packages/ui/stories/templates/Dashboard/Dashboard.stories.tsx
Labels: 🐛 Bug, ✅ Done, Pair approved 🌟
