Repository axelor/axelor-mobile, pull requests merged in 2024-06, with the labels that each got.

#517 chore: upgrade react-native project to 0.70.15
  .flowconfig
  .gitignore
  .node-version
  Gemfile
  android/app/build.gradle
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  ios/AosMobile.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  jest/setup-mocks.js
  package.json
  packages/apps/crm/README.md
  packages/apps/crm/package.json
  packages/apps/helpdesk/README.md
  packages/apps/helpdesk/package.json
  packages/apps/hr/README.md
  packages/apps/hr/package.json
  packages/apps/intervention/README.md
  packages/apps/intervention/package.json
  packages/apps/manufacturing/README.md
  packages/apps/manufacturing/package.json
  packages/apps/quality/README.md
  packages/apps/quality/package.json
  packages/apps/stock/README.md
  packages/apps/stock/package.json
  packages/core/README.md
  packages/core/package.json
  packages/core/src/app/ContextsProvider.tsx
  packages/core/src/sessions/components/alerts/PopupCreateSession.js
  packages/core/src/sessions/components/alerts/PopupSession.js
  packages/error/package.json
  packages/ui/README.md
  packages/ui/package.json
  patches/react-native+0.70.15.patch
  patches/react-native-gifted-charts+1.4.10.patch
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#579 feat: enable selection of a specific sample from detail list
  changelogs/unreleased/75625.json
  packages/apps/quality/src/components/atoms/ControlEntrySampleCard/ControlEntrySampleCard.tsx
  packages/apps/quality/src/components/molecules/ControlEntryDetailsHeader/ControlEntryDetailsHeader.tsx
  packages/apps/quality/src/components/molecules/FillingMethodAlert/FillingMethodAlert.tsx
  packages/apps/quality/src/screens/ControlEntryDetailsScreen.js
  packages/apps/quality/src/screens/ControlEntryFormScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#586 fix: make selectedItem not required on getCustomSelectionItems
  packages/core/src/selections/types.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#585 refactor: improve management of pages
  changelogs/unreleased/79421.json
  packages/core/src/apiProviders/Standard/requests.helper.ts
  packages/core/src/apiProviders/utils.ts
  packages/core/src/auth/components/molecules/UserCard/UserCard.tsx
  packages/core/src/auth/screens/UserScreen.js
  packages/ui/__tests__/components/organisms/AutoCompleteSearch.test.js
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/SearchDetailsPopUp.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#587 refactor: use AOS request for user permissions
  packages/core/src/permissions/api.helpers.ts
Labels: 🌟 Feature, ✅ Done

#580 feat: create SearchTreeView component and use it in CustomerParkScreen
  changelogs/unreleased/79175.json
  packages/apps/intervention/src/api/equipment-api.js
  packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx
  packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
  packages/core/src/components/templates/index.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/src/components/templates/TreeView/Branch.tsx
  packages/ui/src/components/templates/TreeView/BranchCard.tsx
  packages/ui/src/components/templates/TreeView/TreeView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#592 fix: manage when multiple timer is not enable
  packages/apps/hr/src/components/molecules/TimerStopwatch/TimerStopwatch.tsx
  packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx
  packages/apps/hr/src/features/timerSlice.js
  packages/apps/hr/src/hooks/use-hr-header-actions.js
  packages/apps/hr/src/index.ts
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
Labels: 🐛 Bug, ✅ Done

#600 fix: padding issue on CustomFieldForm
  changelogs/unreleased/80585.json
  packages/core/src/components/pages/CustomFieldForm/CustomFieldForm.tsx
  packages/core/src/components/pages/FormView/FormView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#598 fix: MultiValuePicker Item type
  changelogs/unreleased/80506.json
  packages/ui/src/components/organisms/MultiValuePicker/MultiValuePicker.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#567 feat: add SubProjectView in Project module
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/project-api.js
  packages/apps/project/src/components/atoms/ProjectCard/ProjectCard.tsx
  packages/apps/project/src/components/pages/SubProjectView/SubProjectView.tsx
  packages/apps/project/src/components/pages/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/projectSlice.js
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#607 fix: typing issue on SearchListView
  changelogs/unreleased/80843.json
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#613 fix: rename screen components
  packages/apps/sales/src/index.ts
  packages/apps/sales/src/screens/saleOrder/SaleOrdersScreen.tsx
  packages/apps/sales/src/screens/saleOrder/SaleQuotationsScreen.tsx
  packages/apps/sales/src/screens/saleOrder/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#609 fix: value of LabelText can't be on multiple lines in some containers
  changelogs/unreleased/80853.json
  packages/ui/src/components/molecules/LabelText/LabelText.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#612 fix: display issue on ProgressBar when progress is very low
  changelogs/unreleased/80812.json
  packages/ui/src/components/organisms/ProgressBar/ProgressBar.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#615 fix: clear scanner value after use
  changelogs/unreleased/71032_scanner.json
  changelogs/unreleased/71032_searchFocus.json
  packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
Labels: 🐛 Bug, ✅ Done

#617 chore: patch packages for sdk 34
  patches/react-native-blob-util+0.17.3.patch
  patches/react-native-datawedge-intents+0.1.8.patch
  patches/react-native-device-info+10.14.0.patch
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#614 fix: BottomBar is cut on iOS due to HeaderBand fix
  changelogs/unreleased/80956.json
  packages/ui/src/components/templates/BottomBar/BottomBar.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#611 fix: manage small screens on intervention
  changelogs/unreleased/80726.json
  changelogs/unreleased/80726_timer.json
  packages/apps/intervention/src/components/pages/GeneralInformationView/GeneralInformationView.tsx
  packages/core/src/components/external/Timer/Timer.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#610 fix: manage long title header and scrollView in OperationOrderDetailsScreen
  changelogs/unreleased/80717.json
  changelogs/unreleased/80717_header.json
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderDetailsScreen.js
  packages/core/src/navigator/drawer/Header.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#619 fix: issue when merging configuration
  changelogs/unreleased/81081.json
  packages/core/src/app/context.helper.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟
