Repository axelor/axelor-mobile, pull requests merged in 2024-08, with the labels that each got.

#662 fix: add scrollview style to enable scrollview for CRM
  changelogs/unreleased/80721.json
  packages/apps/crm/src/screens/client/ClientDetailsScreen.js
  packages/apps/crm/src/screens/contact/ContactDetailsScreen.js
  packages/apps/crm/src/screens/lead/LeadDetailsScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityDetailsScreen.js
  packages/apps/crm/src/screens/prospect/ProspectDetailsScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#668 fix: null issue on product details
  changelogs/unreleased/82727.json
  packages/apps/stock/src/hooks/use-stock-header-actions.js
  packages/apps/stock/src/screens/products/ProductStockDetailsScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#663 feat: add Indicator chart in ChartRender
  changelogs/unreleased/80402.json
  packages/ui/src/components/templates/Dashboard/Chart/ChartRender.tsx
  packages/ui/src/components/templates/Dashboard/chart-type.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#631 refactor: use model and action api providers
  changelogs/unreleased/offline.json
  packages/apps/crm/src/api/catalog-api.js
  packages/apps/crm/src/api/client-api.js
  packages/apps/crm/src/api/company-api.js
  packages/apps/crm/src/api/contact-api.js
  packages/apps/crm/src/api/event-api.js
  packages/apps/crm/src/api/function-api.js
  packages/apps/crm/src/api/leads-api.js
  packages/apps/crm/src/api/opportunities-api.js
  packages/apps/crm/src/api/partner-api.js
  packages/apps/crm/src/api/prospect-api.js
  packages/apps/crm/src/models/objectFields.ts
  packages/apps/helpdesk/src/api/customer-api.js
  packages/apps/helpdesk/src/api/project-api.js
  packages/apps/helpdesk/src/api/ticket-api.js
  packages/apps/helpdesk/src/api/timer-api.js
  packages/apps/hr/src/api/currency-api.js
  packages/apps/hr/src/api/distance-api.js
  packages/apps/hr/src/api/employee-api.js
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/expense-line-api.js
  packages/apps/hr/src/api/expense-type-api.js
  packages/apps/hr/src/api/kilometric-allow-param-api.js
  packages/apps/hr/src/api/manuf-order-api.js
  packages/apps/hr/src/api/project-api.js
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/api/timesheet-api.js
  packages/apps/hr/src/api/timesheet-line-api.js
  packages/apps/manufacturing/src/api/machine-api.js
  packages/apps/manufacturing/src/api/manufacturing-order-api.js
  packages/apps/manufacturing/src/api/operation-order-api.js
  packages/apps/manufacturing/src/api/prod-product-api.js
  packages/apps/manufacturing/src/api/production-file-api.js
  packages/apps/manufacturing/src/api/waste-product-api.js
  packages/apps/manufacturing/src/api/work-center-api.js
  packages/apps/quality/src/api/control-entry-api.js
  packages/apps/quality/src/api/control-entry-sample-api.js
  packages/apps/quality/src/api/control-entry-sample-line-api.js
  packages/apps/quality/src/api/control-plan-api.js
  packages/apps/stock/src/api/customer-delivery-api.js
  packages/apps/stock/src/api/customer-delivery-line-api.js
  packages/apps/stock/src/api/internal-move-api.js
  packages/apps/stock/src/api/internal-move-line-api.js
  packages/apps/stock/src/api/inventory-api.js
  packages/apps/stock/src/api/inventory-line-api.js
  packages/apps/stock/src/api/partner-api.js
  packages/apps/stock/src/api/product-api.js
  packages/apps/stock/src/api/stock-correction-api.js
  packages/apps/stock/src/api/stock-correction-reason-api.js
  packages/apps/stock/src/api/stock-location-api.js
  packages/apps/stock/src/api/stock-location-line-api.js
  packages/apps/stock/src/api/supplier-arrival-api.js
  packages/apps/stock/src/api/supplier-arrival-line-api.js
  packages/apps/stock/src/api/supplier-catalog-api.js
  packages/apps/stock/src/api/tracking-number-api.js
  packages/apps/stock/src/api/unit-api.js
  packages/apps/stock/src/models/objectFields.ts
  packages/core/src/apiProviders/Standard/requests.helper.ts
  packages/core/src/utils/formatters.ts
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#664 feat: add default interval on period Input
  changelogs/unreleased/80473.json
  packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
  packages/core/src/utils/index.ts
  packages/core/src/utils/time.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#666 fix: enable tracking number creation without verification
  changelogs/unreleased/82115.json
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalTrackingNumberSelect/SupplierArrivalTrackingNumberSelect.js
  packages/apps/stock/src/features/trackingNumberSlice.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectTrackingScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#669 feat: add a more results indicator on search bar
  changelogs/unreleased/82748.json
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#670 feat: clean process storage to keep only recent calls
  packages/core/src/app/ContextsProvider.tsx
  packages/core/src/loader/ProcessProvider.ts
  packages/core/src/loader/ProcessStorage.ts
  packages/core/src/screens/index.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#672 feat: add a badge to get information about linked StockMove status on consumed products
  changelogs/unreleased/80472.json
  packages/apps/manufacturing/src/api/prod-product-api.js
  packages/apps/manufacturing/src/components/organisms/ConsumedProductCard/ConsumedProductCard.tsx
  packages/apps/manufacturing/src/components/organisms/ConsumedProductGlobalCard/ConsumedProductGlobalCard.tsx
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderHeader/ManufacturingOrderHeader.tsx
  packages/apps/manufacturing/src/models/objectFields.ts
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#676 feat: add story for TreeView
  packages/ui/stories/templates/TreeView.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#687 refactor: default edit mode on Task
  packages/apps/project/src/screens/TaskFormScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#685 refactor: show minimum value on ProgressBar
  changelogs/83264.json
  packages/ui/src/components/organisms/ProgressBar/ProgressBar.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#684 feat: move InternalMoveCreationViewAll and InternalMoveCreationAlert to UI
  changelogs/unreleased/83330.json
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationViewAll/InternalMoveCreationViewAll.tsx
  packages/apps/stock/src/components/templates/internalMove/index.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/screens/internalMoves/InternalMoveCreationScreen.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/__tests__/components/organisms/ViewAllEditList.test.js
  packages/ui/src/components/organisms/ViewAllEditList/AllLinesAlert.tsx
  packages/ui/src/components/organisms/ViewAllEditList/LineComponent.tsx
  packages/ui/src/components/organisms/ViewAllEditList/ViewAllEditList.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/organisms/ViewAllEditList.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#686 refactor: add message when no activities
  packages/apps/project/src/components/templates/ActivityListView/ActivityListView.tsx
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#688 feat: move QuantityCard to ui
  changelogs/unreleased/83389.json
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductDetailsScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductDetailsScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductDetailsScreen.js
  packages/apps/stock/src/components/organisms/index.js
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineQuantityCard/CustomerDeliveryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationQuantityCard/InternalMoveCreationQuantityCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineQuantityCard/InternalMoveLineQuantityCard.js
  packages/apps/stock/src/components/templates/inventory/InventoryLineQuantityCard/InventoryLineQuantityCard.tsx
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionQuantityCard/StockCorrectionQuantityCard.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineQuantityCard/SupplierArrivalLineQuantityCard.tsx
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalAddTrackingScreen.js
  packages/ui/__tests__/components/organisms/QuantityCard.test.js
  packages/ui/src/components/organisms/QuantityCard/QuantityCard.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/organisms/QuantityCard.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟
