Repository axelor/axelor-mobile, pull requests merged in 2024-04, with the labels that each got.

#477 feat: add EquipmentInterventionListScrren
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/api/intervention-api.js
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/interventionSlice.js
  packages/apps/intervention/src/hooks/use-intervention-header-actions.ts
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/screens/equipment/EquipmentInterventionListScreen.tsx
  packages/apps/intervention/src/screens/equipment/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#480 feat: creation of NoteFormScreen
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/api/intervention-note-api.js
  packages/apps/intervention/src/components/molecules/NoteDetailCard/NoteDetailCard.tsx
  packages/apps/intervention/src/components/organisms/InterventionNoteTypePicker/InterventionNoteTypePicker.tsx
  packages/apps/intervention/src/components/pages/NoteView/NoteView.tsx
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/interventionNoteSlice.js
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/models/forms.ts
  packages/apps/intervention/src/models/objectFields.ts
  packages/apps/intervention/src/models/sortFields.ts
  packages/apps/intervention/src/screens/intervention/InterventionNoteFormScreen.tsx
  packages/apps/intervention/src/screens/intervention/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#456 feat: add animation on scale button
  .storybook/main.js
  jest/setup-mocks.js
  packages/ui/src/components/templates/BottomBar/BarItem.tsx
  packages/ui/src/components/templates/BottomBar/BottomBar.tsx
  packages/ui/stories/templates/BottomBar.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#485 fix: improve design of DropdownCard
  changelogs/unreleased/77358.json
  packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx
  packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#487 feat: move TextUnit to ui package
  changelogs/unreleased/77290.json
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/atoms/TimeCard/TimeCard.tsx
  packages/apps/hr/src/components/atoms/TimesheetCard/TimesheetCard.tsx
  packages/apps/hr/src/components/atoms/index.js
  packages/ui/__tests__/components/molecules/TextUnit.test.js
  packages/ui/src/components/molecules/TextUnit/TextUnit.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/stories/molecules/TextUnit.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#475 feat: creation of EquipmentView
  packages/apps/intervention/src/api/equipment-api.js
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/components/atoms/EquipmentCard/EquipmentCard.tsx
  packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx
  packages/apps/intervention/src/components/molecules/InterventionHeader/InterventionHeader.tsx
  packages/apps/intervention/src/components/organisms/EquipmentModeSwitch/EquipmentModeSwitch.tsx
  packages/apps/intervention/src/components/organisms/index.ts
  packages/apps/intervention/src/components/pages/EquipmentView/EquipmentView.tsx
  packages/apps/intervention/src/components/pages/index.ts
  packages/apps/intervention/src/components/templates/SurveyRangeNavigation/SurveyRangeNavigation.tsx
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/equipmentSlice.js
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/models/objectFields.ts
  packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx
  packages/apps/intervention/src/types/equipment.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#481 feat: creation of InterventionQuestionFormScreen
  changelogs/unreleased/77355.json
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/api/question-api.js
  packages/apps/intervention/src/components/molecules/QuestionAdvancedMonitoring/QuestionAdvancedMonitoring.tsx
  packages/apps/intervention/src/components/molecules/QuestionCheckbox/QuestionCheckbox.tsx
  packages/apps/intervention/src/components/molecules/QuestionList/QuestionList.tsx
  packages/apps/intervention/src/components/molecules/QuestionMeasure/QuestionMeasure.tsx
  packages/apps/intervention/src/components/molecules/index.ts
  packages/apps/intervention/src/components/pages/SurveyView/SurveyView.tsx
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/questionSlice.js
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/models/forms.ts
  packages/apps/intervention/src/models/objectFields.ts
  packages/apps/intervention/src/screens/intervention/InterventionQuestionFormScreen.tsx
  packages/apps/intervention/src/screens/intervention/index.ts
  packages/apps/intervention/src/types/question.ts
  packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx
  packages/core/src/components/organisms/DateInput/DateInput.tsx
  packages/ui/src/components/molecules/FormInput/FormInput.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#462 feat: add refresh chart on dashboard
  changelogs/unreleased/74138.json
  packages/core/src/dashboards/api.helpers.ts
  packages/core/src/dashboards/component/RefreshChart/RefreshChart.tsx
  packages/core/src/dashboards/component/index.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#489 fix: ignore error when user does not have an employee
  changelogs/unreleased/76870.json
  packages/apps/hr/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#484 feat: improve range management on survey view
  packages/apps/intervention/src/components/pages/SurveyView/SurveyView.tsx
  packages/apps/intervention/src/components/templates/SurveyRangeNavigation/SurveyRangeNavigation.tsx
  packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx
  packages/ui/src/components/organisms/Picker/Picker.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#493 fix: avoid error on SearchBar when no onChange function is provided
  changelogs/unreleased/77315.json
  packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
Labels: 🐛 Bug, ✅ Done

#496 feat: add new GridView component
  changelogs/unreleased/77314.json
  packages/ui/__tests__/components/organisms/GridView.test.js
  packages/ui/src/components/organisms/GridView/CellView.tsx
  packages/ui/src/components/organisms/GridView/GridView.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/organisms/GridView.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#497 fix: enable limit with more than one digit
  changelogs/unreleased/74061.json
  packages/ui/src/components/molecules/NumberChevronInput/NumberChevronInput.tsx
Labels: 🐛 Bug, ✅ Done

#503 feat: change icon of intervention module
  packages/apps/intervention/src/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#490 feat: improve DropdownCardSwitch logic
  changelogs/unreleased/77359.json
  packages/ui/__tests__/components/organisms/DropdownCardSwitch.test.js
  packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
  packages/ui/stories/organisms/DropdownCardSwitch.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#441 feat: improve user screen display
  changelogs/unreleased/75461_Dashboard.json
  changelogs/unreleased/75641_Pickers.json
  changelogs/unreleased/75641_UserScreen.json
  packages/apps/stock/src/screens/auth/UserScreen.js
  packages/core/src/auth/components/molecules/DashboardsCard/DashboardsCard.tsx
  packages/core/src/auth/components/molecules/NavigationToolsButton/NavigationToolsButton.tsx
  packages/core/src/auth/components/molecules/ShortcutsCard/ShortcutsCard.tsx
  packages/core/src/auth/components/molecules/TranslationsButton/TranslationsButton.tsx
  packages/core/src/auth/components/molecules/UserCard/UserCard.tsx
  packages/core/src/auth/components/molecules/index.js
  packages/core/src/auth/models/objectFields.ts
  packages/core/src/auth/screens/SettingsScreen.js
  packages/core/src/auth/screens/UserScreen.js
  packages/core/src/dashboards/index.js
  packages/core/src/dashboards/view/DashboardScreen.tsx
  packages/core/src/dashboards/view/DashboardView.tsx
  packages/core/src/dashboards/view/index.ts
  packages/ui/src/components/templates/Dashboard/Dashboard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#492 refactor: use SeachListView on Crm list view
  changelogs/unreleased/76220.json
  packages/apps/crm/src/api/catalog-api.js
  packages/apps/crm/src/api/client-api.js
  packages/apps/crm/src/api/contact-api.js
  packages/apps/crm/src/api/leads-api.js
  packages/apps/crm/src/api/opportunities-api.js
  packages/apps/crm/src/api/prospect-api.js
  packages/apps/crm/src/components/templates/CatalogsSearchBar/CatalogsSearchBar.js
  packages/apps/crm/src/components/templates/ClientSearchBar/ClientSearchBar.js
  packages/apps/crm/src/components/templates/OpportunitySearchBar/OpportunitySearchBar.js
  packages/apps/crm/src/components/templates/ProspectSearchBar/ProspectSearchBar.js
  packages/apps/crm/src/components/templates/index.js
  packages/apps/crm/src/screens/catalog/CatalogListScreen.js
  packages/apps/crm/src/screens/client/ClientsListScreen.js
  packages/apps/crm/src/screens/contact/ContactListScreen.js
  packages/apps/crm/src/screens/lead/LeadListScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js
  packages/apps/crm/src/screens/prospect/ProspectsListScreen.js
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#509 feat: manage shortcut config on user screen
  packages/core/src/auth/screens/UserScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#505 fix: add default value for currency
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#501 refactor: use SearchListView component on helpdesk
  changelogs/unreleased/76222.json
  packages/apps/helpdesk/src/api/ticket-api.js
  packages/apps/helpdesk/src/components/templates/MyTeamTicketSearchBar/MyTeamTicketSearchBar.js
  packages/apps/helpdesk/src/components/templates/MyTicketSearchBar/MyTicketSearchBar.js
  packages/apps/helpdesk/src/components/templates/index.js
  packages/apps/helpdesk/src/screens/MyTeamTicketListScreen.js
  packages/apps/helpdesk/src/screens/MyTicketListScreen.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#508 refactor: use SearchListView component on manufacturing
  changelogs/unreleased/76223.json
  packages/apps/manufacturing/src/api/manufacturing-order-api.js
  packages/apps/manufacturing/src/api/operation-order-api.js
  packages/apps/manufacturing/src/api/waste-product-api.js
  packages/apps/manufacturing/src/models/searchFields.ts
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/wasteProduct/WasteProductListScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#511 fix: add maxHeight on Alert component
  packages/ui/src/components/molecules/Alert/Alert.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#486 feat: add openGoogleMapsDirections function
  changelogs/unreleased/73971.json
  packages/core/src/tools/LinkingProvider.ts
  packages/core/src/tools/linking.helper.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#495 refactor: use SearchListView component on stock
  changelogs/unreleased/76224.json
  packages/apps/stock/src/api/customer-delivery-api.js
  packages/apps/stock/src/api/internal-move-api.js
  packages/apps/stock/src/api/inventory-api.js
  packages/apps/stock/src/api/stock-correction-api.js
  packages/apps/stock/src/api/supplier-arrival-api.js
  packages/apps/stock/src/features/stockCorrectionSlice.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineListScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryListScreen.js
  packages/apps/stock/src/screens/products/ProductListScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js
  packages/apps/stock/src/types/stock-corrrection.tsx
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#502 feat: add archive,copy and create APIs for equipments
  packages/apps/intervention/src/api/equipment-api.js
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx
  packages/apps/intervention/src/components/pages/EquipmentView/EquipmentView.tsx
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/equipmentSlice.js
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx
  packages/apps/intervention/src/screens/equipment/EquipmentFormView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#498 feat: add API on intervention stopwatch
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/api/intervention-api.js
  packages/apps/intervention/src/components/pages/GeneralInformationView/GeneralInformationView.tsx
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/interventionSlice.js
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#500 feat: add link/unlink equipment functions
  packages/apps/intervention/src/api/equipment-api.js
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/api/intervention-api.js
  packages/apps/intervention/src/components/molecules/EquipmentActionCard/EquipmentActionCard.tsx
  packages/apps/intervention/src/components/pages/EquipmentView/EquipmentView.tsx
  packages/apps/intervention/src/components/templates/LinkEquipmentPopup/LinkEquipmentPopup.tsx
  packages/apps/intervention/src/components/templates/index.ts
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/equipmentSlice.js
  packages/apps/intervention/src/features/interventionSlice.js
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/screens/equipment/EquipmentFormView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#515 fix: refresh issue on Event form view search bars
  changelogs/unreleased/78020.json
  packages/apps/crm/src/components/templates/ContactSearchBar/ContactSearchBar.tsx
  packages/apps/crm/src/components/templates/LeadSearchBar/LeadSearchBar.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#513 fix: add header action on line details stock screens
  changelogs/unreleased/77825.json
  packages/apps/stock/src/hooks/use-stock-header-actions.js
  packages/apps/stock/src/screens/customerDeliveries/index.js
  packages/apps/stock/src/screens/internalMoves/index.js
  packages/apps/stock/src/screens/inventories/index.js
  packages/apps/stock/src/screens/supplierArrivals/index.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#514 feat: add new button to see itinerary on Tour details
  changelogs/unreleased/77940.json
  packages/apps/crm/src/components/organisms/TourItineraryButton/TourItineraryButton.tsx
  packages/apps/crm/src/components/organisms/index.js
  packages/apps/crm/src/screens/tour/TourDetailsScreen.js
  packages/apps/crm/src/types/tourLine.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#512 feat: enable edit mode when creating an internal move
  changelogs/unreleased/74084.json
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationAlert/InternalMoveCreationAlert.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationButtons/InternalMoveCreationButtons.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationViewAll/InternalMoveCreationViewAll.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveCreationViewAll/LineComponent.tsx
  packages/apps/stock/src/screens/internalMoves/InternalMoveCreationScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#467 chore: upgrade project to react-native 0.69
  .eslintrc.js
  .flowconfig
  .gitignore
  .prettierrc.js
  .ruby-version
  Gemfile
  Gemfile.lock
  android/app/build.gradle
  android/app/src/main/java/com/aosmobile/MainActivity.java
  android/app/src/main/java/com/aosmobile/MainApplication.java
  android/app/src/main/java/com/aosmobile/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/jni/Android.mk
  android/build.gradle
  android/settings.gradle
  axelor-module-name-mapper.js
  babel.config.js
  ios/.xcode.env
  ios/AosMobile.xcodeproj/project.pbxproj
  ios/AosMobile/AppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  jest/setup-mocks.js
  nx.json
  package.json
  packages/apps/crm/i18n.json
  packages/apps/crm/package.json
  packages/apps/helpdesk/i18n.json
  packages/apps/helpdesk/package.json
  packages/apps/hr/i18n.json
  packages/apps/hr/package.json
  packages/apps/intervention/i18n.json
  packages/apps/intervention/package.json
  packages/apps/manufacturing/i18n.json
  packages/apps/manufacturing/package.json
  packages/apps/quality/i18n.json
  packages/apps/quality/package.json
  packages/apps/stock/i18n.json
  packages/apps/stock/package.json
  packages/core/i18n.json
  packages/core/package.json
  packages/core/src/api/metafile-api.ts
  packages/core/src/redux/hooks.ts
  packages/error/package.json
  packages/ui/package.json
  patches/react-native+0.68.1.patch
  patches/react-native+0.69.12.patch
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#507 fix: add scrollview on drawer to manage small screen
  changelogs/unreleased/77769.json
  packages/core/src/navigator/drawer/DrawerContent.js
  packages/core/src/navigator/drawer/Menu.js
  packages/core/src/navigator/drawer/MenuTitle.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#519 fix: question mark when dark mode
  changelogs/unreleased/77717.json
  packages/ui/src/components/atoms/BootstrapIcon/BootstrapIcon.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#521 fix: menu list doesn't appear
  changelogs/unreleased/drawer.json
  packages/core/src/navigator/drawer/DrawerContent.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#524 fix: width issue on dropdown on opportunity details screen
  changelogs/unreleased/78311.json
  packages/apps/crm/src/components/organisms/Opportunity/OpportunityDropdownInfo/OpportunityDropdownInfo.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#526 fix: hide header actions on equipment creation
  packages/apps/intervention/src/features/equipmentSlice.js
  packages/apps/intervention/src/hooks/use-intervention-header-actions.ts
  packages/apps/intervention/src/screens/equipment/EquipmentFormView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#530 fix: inconsistency issues on Timers list view
  changelogs/unreleased/78337.json
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/models/sortFields.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#527 fix: hide field depending on equipment type
  packages/apps/intervention/src/components/organisms/ContractSearchBar/ContractSearchBar.tsx
  packages/apps/intervention/src/components/organisms/EquipmentFamilySearchBar/EquipmentFamilySearchBar.tsx
  packages/apps/intervention/src/hooks/use-intervention-header-actions.ts
  packages/apps/intervention/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#534 fix: remove useless onChangeSearchValue
  changelogs/unreleased/77872.json
  packages/apps/crm/src/screens/catalog/CatalogListScreen.js
  packages/apps/crm/src/screens/client/ClientsListScreen.js
  packages/apps/crm/src/screens/contact/ContactListScreen.js
  packages/apps/crm/src/screens/lead/LeadListScreen.js
  packages/apps/crm/src/screens/opportunity/OpportunityListScreen.js
  packages/apps/crm/src/screens/prospect/ProspectsListScreen.js
  packages/apps/intervention/src/screens/equipment/CustomerParkScreen.tsx
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ConsumedProductListScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/producedProduct/ProducedProductListScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#523 feat: add TagList to display list of tags
  changelogs/unreleased/77952.json
  packages/ui/__tests__/components/organisms/TagList.test.js
  packages/ui/src/components/organisms/TagList/TagList.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/organisms/TagList.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#538 fix: remove comptability comments in intervention config
  packages/apps/intervention/src/index.ts
Labels: 🐛 Bug, 🌟 Feature, Approved 🌟

#529 fix: refresh issue on active intervention screen
  packages/apps/intervention/src/screens/intervention/ActiveInterventionScreen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#539 fix: max height issue on login popup
  changelogs/unreleased/78348.json
  packages/core/src/sessions/components/alerts/PopupCreateSession.js
  packages/core/src/sessions/components/alerts/PopupEditSession.js
  packages/core/src/sessions/components/alerts/PopupSession.js
  packages/core/src/sessions/components/inputs/SessionInputs.js
  packages/core/src/sessions/components/inputs/UrlInput.js
  packages/core/src/sessions/components/inputs/UsernameInput.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#540 feat: update maxParallel to include project module to yarn dev
  package.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#528 feat: add question status on form view
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/screens/intervention/InterventionQuestionFormScreen.tsx
  packages/apps/intervention/src/types/question.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#536 fix: modify filters on timesheet lines and timers
  changelogs/unreleased/78441.json
  packages/apps/hr/src/api/project-api.js
  packages/apps/hr/src/components/templates/ProjectTaskSearchBar/ProjectTaskSearchBar.tsx
  packages/apps/hr/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#531 feat: add project task on expense line
  changelogs/unreleased/78184.json
  packages/apps/hr/src/api/project-api.js
  packages/apps/hr/src/components/atoms/ExpenseLineCard/ExpenseLineCard.tsx
  packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx
  packages/apps/hr/src/components/templates/ProjectTaskSearchBar/ProjectTaskSearchBar.tsx
  packages/apps/hr/src/models/forms.ts
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#542 fix: crash when change language
  packages/core/src/auth/screens/SettingsScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟
