Repository axelor/axelor-mobile, pull requests merged in 2024-03, with the labels that each got.

#427 feat: create web view component
  changelogs/unreleased/75354.json
  package.json
  packages/core/package.json
  packages/core/src/components/external/WebView/WebView.tsx
  packages/core/src/components/external/index.js
  packages/ui/package.json
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#440 feat: creation of SearchListScreen to search and scroll
  changelogs/unreleased/75762.json
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
  packages/core/src/components/templates/index.js
  packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#444 feat: give process response to Loader callbacks
  packages/apps/stock/src/screens/loader/LoaderScreen.js
  packages/core/src/components/templates/Loader/ProcessProvider.ts
  packages/core/src/components/templates/Loader/types.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#450 fix: use new request to update an ExpenseLine
  changelogs/unreleased/74584.json
  packages/apps/hr/src/api/expense-line-api.js
  packages/apps/hr/src/components/templates/ExpenseLineTypeDisplay/ExpenseLineTypeDisplay.tsx
  packages/apps/hr/src/features/expenseLineSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
Labels: 🐛 Bug, ✅ Done

#457 fix: improve display on login screen
  changelogs/unreleased/75763.json
  packages/core/src/screens/SessionManagementScreen.js
  packages/core/src/sessions/components/display/SessionListCard.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#443 feat: display label when clicking on PieChart
  packages/ui/__tests__/components/templates/PieChart.test.js
  packages/ui/src/components/templates/Dashboard/Chart/PieChart/ChartLegend.tsx
  packages/ui/src/components/templates/Dashboard/Chart/PieChart/LabelView.tsx
  packages/ui/src/components/templates/Dashboard/Chart/PieChart/PieChart.tsx
  packages/ui/src/components/templates/Dashboard/Chart/index.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#453 feat: add Aop chart on Dashboard
  packages/core/src/dashboards/component/AOPChart/AOPChart.tsx
  packages/core/src/dashboards/view/DashboardScreen.tsx
  packages/ui/src/components/templates/Dashboard/Dashboard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#451 fix: correction of build issues to launch app on iOS
  ios/AosMobile.xcodeproj/project.pbxproj
  ios/AosMobile/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/react-native+0.68.1.patch
  patches/react-native-vision-camera+2.15.6.patch
  yarn.lock
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#449 feat: add InfoButton component
  changelogs/unreleased/76104.json
  packages/apps/hr/src/components/molecules/ExpenseLineDetailCard/ExpenseLineDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimeDetailCard/TimeDetailCard.tsx
  packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx
  packages/apps/manufacturing/src/components/organisms/ConsumedProductGlobalCard/ConsumedProductGlobalCard.tsx
  packages/ui/__tests__/components/molecules/CardIndicator.test.js
  packages/ui/__tests__/components/organisms/InfoBubble.test.js
  packages/ui/__tests__/components/organisms/InfoButton.test.js
  packages/ui/src/components/molecules/CardIconButton/CardIconButton.tsx
  packages/ui/src/components/molecules/CardIndicator/CardIndicator.tsx
  packages/ui/src/components/molecules/InfoBubble/InfoBubble.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/src/components/organisms/GroupByScrollList/TopSeparator.tsx
  packages/ui/src/components/organisms/InfoBubble/InfoBubble.tsx
  packages/ui/src/components/organisms/InfoButton/InfoButton.tsx
  packages/ui/src/components/organisms/index.tsx
  packages/ui/stories/molecules/CardIndicator.stories.tsx
  packages/ui/stories/organisms/InfoBubble.stories.tsx
  packages/ui/stories/organisms/InfoButton.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#454 feat: add PeriodInput component
  changelogs/unreleased/74400.json
  packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
  packages/core/src/components/templates/index.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#460 feat: add props to hide Card in Dashboard
  changelogs/unreleased/75937.json
  packages/core/src/dashboards/view/DashboardScreen.tsx
  packages/ui/src/components/templates/Dashboard/Chart/BarChart.tsx
  packages/ui/src/components/templates/Dashboard/Chart/LineChart.tsx
  packages/ui/src/components/templates/Dashboard/Dashboard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#465 refactor: add props to SearchListView
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#461 feat: add last update date when refresh
  changelogs/unreleased/72197.json
  packages/core/src/dashboards/view/DashboardScreen.tsx
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/ui/src/components/templates/Dashboard/Dashboard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#470 feat: creation of SurveyView
  packages/apps/intervention/src/api/index.ts
  packages/apps/intervention/src/api/question-api.js
  packages/apps/intervention/src/components/atoms/QuestionCard/QuestionCard.tsx
  packages/apps/intervention/src/components/atoms/index.ts
  packages/apps/intervention/src/components/molecules/InterventionHeader/InterventionHeader.tsx
  packages/apps/intervention/src/components/pages/SurveyView/SurveyView.tsx
  packages/apps/intervention/src/components/pages/index.ts
  packages/apps/intervention/src/components/templates/SurveyRangeNavigation/SurveyRangeNavigation.tsx
  packages/apps/intervention/src/components/templates/index.ts
  packages/apps/intervention/src/features/asyncFunctions-index.ts
  packages/apps/intervention/src/features/index.js
  packages/apps/intervention/src/features/questionSlice.js
  packages/apps/intervention/src/i18n/en.json
  packages/apps/intervention/src/i18n/fr.json
  packages/apps/intervention/src/models/objectFields.ts
  packages/apps/intervention/src/models/sortFields.ts
  packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx
  packages/apps/intervention/src/types/index.ts
  packages/apps/intervention/src/types/question.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#472 feat: creation of HistoryView
  packages/apps/intervention/src/api/intervention-api.js
  packages/apps/intervention/src/components/atoms/InterventionCard/InterventionCard.tsx
  packages/apps/intervention/src/components/molecules/InterventionDetailCard/InterventionDetailCard.tsx
  packages/apps/intervention/src/components/pages/HistoryView/HistoryView.tsx
  packages/apps/intervention/src/components/pages/index.ts
  packages/apps/intervention/src/components/templates/InterventionsListView/InterventionsListView.tsx
  packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#458 feat: add SignatureInput component
  changelogs/unreleased/76449.json
  changelogs/unreleased/76449_form.json
  docs/doc/en/Application/Creation_d_un_ecran.md
  docs/doc/fr/Application/Creation_d_un_ecran.md
  jest/setup-mocks.js
  packages/core/package.json
  packages/core/src/components/organisms/SignatureInput/PictureIcon.tsx
  packages/core/src/components/organisms/SignatureInput/SignatureInput.tsx
  packages/core/src/components/organisms/index.js
  packages/core/src/components/pages/FormView/Components/Field.tsx
  packages/core/src/forms/display.helpers.ts
  packages/core/src/forms/types.ts
  packages/core/src/tools/FilePicker.ts
  packages/core/src/tools/index.js
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#479 fix: display actions even when ScrollList data is empty
  packages/ui/__tests__/components/organisms/ScrollList.test.js
  packages/ui/src/components/organisms/ScrollList/ScrollList.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟
