Repository axelor/axelor-mobile, pull requests merged in 2024-10, with the labels that each got.

#710 feat: add new module registration system
  changelogs/unreleased/83311.json
  changelogs/unreleased/83311_dashboard.json
  changelogs/unreleased/83311_webview.json
  docs/doc/en/Application/Creation_d_un_module.md
  docs/doc/fr/Application/Creation_d_un_module.md
  packages/core/src/app/Application.tsx
  packages/core/src/app/ContextedApplication.tsx
  packages/core/src/app/ContextsProvider.tsx
  packages/core/src/app/RootNavigator.js
  packages/core/src/app/modules/ModuleProvider.ts
  packages/core/src/app/modules/hooks.ts
  packages/core/src/app/modules/index.ts
  packages/core/src/app/modules/types.ts
  packages/core/src/auth/index.ts
  packages/core/src/config/RouterProvider.ts
  packages/core/src/dashboards/menu.helpers.ts
  packages/core/src/features/authSlice.js
  packages/core/src/features/index.js
  packages/core/src/features/mobileDashboardSlice.js
  packages/core/src/features/mobileWebViewSlice.js
  packages/core/src/hooks/use-header-registers.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/navigator/Navigator.js
  packages/core/src/navigator/menu.helper.js
  packages/core/src/webViews/menu.helper.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#726 feat: add edition link on Task BottomBar
  packages/apps/project/src/components/organisms/EditTaskButton/EditTaskButton.tsx
  packages/apps/project/src/components/organisms/index.ts
  packages/apps/project/src/screens/TaskDetailsScreen.tsx
  packages/apps/project/src/screens/TaskFormScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#728 feat: take web sale configs into account
  packages/apps/sale/src/api/product-api.js
  packages/apps/sale/src/screens/cart/CatalogScreen.tsx
  packages/apps/sale/src/screens/product/ProductSaleListScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#737 feat: add active project management
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/index.ts
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/screens/ActiveProjectScreen.tsx
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
  packages/apps/project/src/screens/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#739 refactor: restrict DraggableWrapper to avoid sending it out of screen
  packages/ui/src/components/organisms/DraggableWrapper/DraggableWrapper.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#735 feat: add reporting view depends on mobileSettings config
  packages/apps/project/src/components/pages/ReportingView/ReportingView.tsx
  packages/apps/project/src/hooks/index.ts
  packages/apps/project/src/hooks/use-reporting-configuration.ts
  packages/apps/project/src/index.ts
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
  packages/apps/project/src/types/index.ts
  packages/apps/project/src/types/reporting-type.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#741 feat: add possibility to changeSaleOrder
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/api/sale-order-api.js
  packages/apps/sale/src/components/atoms/SaleOrderBottomButton/SaleOrderBottomButton.tsx
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/saleOrderSlice.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/index.ts
  packages/apps/sale/src/utils/index.ts
  packages/apps/sale/src/utils/sale-order.helpers.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#743 feat: add cart tool
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#746 feat: improve multiple quantities display
  packages/apps/sale/src/components/molecules/DropdownMultipleQuantities/DropdownMultipleQuantities.tsx
  packages/apps/sale/src/components/organisms/ProductDropdownCard/ProductDropdownCard.tsx
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#747 fix: manage app activation for tool display
  packages/core/src/components/templates/GlobalToolBox/GlobalToolBox.tsx
  packages/core/src/components/templates/GlobalToolBox/tool.helpers.ts
  packages/core/src/navigator/ActiveScreenProvider.ts
  packages/core/src/navigator/Navigator.js
  packages/core/src/navigator/module.helper.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#748 fix: change product input to not required on TimesheetLine form
  changelogs/unreleased/85434.json
  packages/apps/hr/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#752 fix: error when clicking of product indicator
  changelogs/unreleased/85476.json
  packages/apps/stock/src/components/templates/product/ProductCardStockIndicatorList/ProductCardStockIndicatorList.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#740 fix: prevent fixedItems from being cut on Screen
  changelogs/unreleased/84414.json
  packages/ui/src/components/atoms/KeyboardAvoidingScrollView/KeyboardAvoidingScrollView.tsx
  packages/ui/src/components/atoms/Screen/Screen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#754 fix: make form tools always visible in edition mode
  changelogs/unreleased/85478.json
  packages/ui/src/components/organisms/FloatingButton/FloatingButton.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#755 refactor: add edition mode by default on form views when user navigates to create or modify an object
  changelogs/unreleased/85480.json
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
  packages/apps/intervention/src/screens/intervention/InterventionQuestionFormScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#758 fix: add trackingnumber managment on stock correction
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/api/stock-correction-api.js
  packages/apps/stock/src/components/templates/stockCorrection/StockCorrectionTrackingNumberSelect/StockCorrectionTrackingNumberSelect.tsx
  packages/apps/stock/src/components/templates/stockCorrection/index.js
  packages/apps/stock/src/features/asyncFunctions-index.ts
  packages/apps/stock/src/features/stockCorrectionSlice.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionCreationScreen.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionDetailsScreen.js
Labels: 🌟 Feature, ✅ Done

#749 feat: add configuration to activate/desactivate toolbox
  changelogs/unreleased/85325.json
  packages/core/src/auth/i18n/en.json
  packages/core/src/auth/i18n/fr.json
  packages/core/src/auth/screens/SettingsScreen.js
  packages/core/src/components/templates/GlobalToolBox/GlobalToolBox.tsx
  packages/ui/src/config/ConfigContext.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#759 feat: enable cart line creation
  packages/apps/sale/src/api/cart-line-api.js
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/components/molecules/CartLineValidationButton/CartLineValidationButton.tsx
  packages/apps/sale/src/components/organisms/ProductSearchBar/ProductSearchBar.tsx
  packages/apps/sale/src/components/organisms/index.ts
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/cartLineSlice.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/models/objectFields.ts
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
  packages/apps/sale/src/screens/cart/CartLineDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#757 feat: add Slider component
  changelogs/unreleased/85158_formSlider.json
  changelogs/unreleased/85158_slider.json
  jest/setup-mocks.js
  package.json
  packages/ui/__tests__/components/atoms/Slider.test.js
  packages/ui/__tests__/components/molecules/FormSlider.test.js
  packages/ui/package.json
  packages/ui/src/components/atoms/Slider/Slider.tsx
  packages/ui/src/components/atoms/index.tsx
  packages/ui/src/components/molecules/FormSlider/FormSlider.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/stories/atoms/Slider.stories.tsx
  packages/ui/stories/molecules/FormSlider.stories.tsx
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#750 fix: remove useless criteria and add filter on business projects
  packages/apps/hr/src/api/project-api.js
  packages/apps/hr/src/components/templates/ProjectSearchBar/ProjectSearchBar.tsx
  packages/apps/hr/src/models/forms.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#751 feat: improve status management
  packages/apps/project/src/components/pages/TaskView/TaskView.tsx
  packages/apps/project/src/components/templates/TaskFilters/TaskFilters.tsx
  packages/apps/project/src/components/templates/TaskStatusSearchBar/TaskStatusSearchBar.tsx
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/projectTaskSlice.js
  packages/apps/project/src/models/forms.ts
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/models/typeObjects.ts
  packages/apps/project/src/screens/TaskFormScreen.tsx
  packages/apps/project/src/screens/TaskListScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#761 fix: keyboard issue on iOS when using html input
  changelogs/unreleased/85783.json
  packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#738 feat: add variant select popup
  packages/apps/sale/src/api/cart-line-api.js
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/api/product-api.js
  packages/apps/sale/src/components/atoms/VariantPopup/VariantPopup.tsx
  packages/apps/sale/src/components/atoms/index.ts
  packages/apps/sale/src/components/molecules/CartLineActionCard/CartLineActionCard.tsx
  packages/apps/sale/src/components/molecules/CatalogActionCard/CatalogActionCard.tsx
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/cartLineSlice.js
  packages/apps/sale/src/features/productSlice.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/models/objectFields.ts
  packages/apps/sale/src/screens/cart/CatalogScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#760 feat: enable quotation creation
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/api/sale-order-api.js
  packages/apps/sale/src/components/organisms/ProductSearchBar/ProductSearchBar.tsx
  packages/apps/sale/src/components/organisms/SaleQuotationCreationButtons/SaleQuotationCreationButtons.tsx
  packages/apps/sale/src/components/organisms/SaleQuotationCreationQuantityCard/SaleQuotationCreationQuantityCard.tsx
  packages/apps/sale/src/components/organisms/index.ts
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/saleOrderSlice.js
  packages/apps/sale/src/hooks/use-sale-header-actions.ts
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/screens/saleOrder/SaleQuotationCreationScreen.tsx
  packages/apps/sale/src/screens/saleOrder/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#762 feat: register add product cart tool in module
  packages/apps/sale/src/api/cart-api.js
  packages/apps/sale/src/api/index.ts
  packages/apps/sale/src/features/asyncFunctions-index.ts
  packages/apps/sale/src/features/cartSlice.js
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/index.ts
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
  packages/apps/sale/src/screens/product/ProductSaleDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#756 feat: manage time log on project and task
  packages/apps/hr/src/features/timesheetLineSlice.js
  packages/apps/project/src/components/organisms/LogTimeButton/LogTimeButton.tsx
  packages/apps/project/src/components/pages/TimeView/TimeView.tsx
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/timesheetLinesSlice.js
  packages/apps/project/src/models/forms.ts
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
  packages/apps/project/src/screens/TaskDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#766 fix: add export scan hook
  changelogs/unreleased/85927.json
  packages/core/src/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#769 fix: display issue when opening FloatingButton
  changelogs/unreleased/83948.json
  packages/ui/src/components/organisms/FloatingButton/FloatingActionButton.tsx
  packages/ui/src/components/organisms/FloatingButton/Indicator.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#763 feat: add possibility to define active item from outside on BottomBar
  changelogs/unreleased/85850.json
  changelogs/unreleased/85850_type.json
  packages/apps/intervention/src/screens/intervention/InterventionDetailsScreen.tsx
  packages/ui/src/components/templates/BottomBar/BottomBar.tsx
  packages/ui/src/components/templates/BottomBar/types.helper.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#773 chore: add Podfile.lock
  ios/Podfile.lock
Labels: ✅ Done

#772 feat: add region support on translations
  changelogs/unreleased/85153.json
  packages/core/src/auth/components/molecules/TranslationsButton/TranslationsButton.tsx
  packages/core/src/auth/models/objectFields.ts
  packages/core/src/i18n/component/Translator.js
  packages/core/src/i18n/helpers/langages.ts
  packages/core/src/i18n/hooks/use-translator.ts
  packages/core/src/i18n/i18n.ts
Labels: 🌟 Feature, ✅ Done

#771 feat: manage shortcut to log time on task
  packages/apps/project/src/components/molecules/TaskActionCard/TaskActionCard.tsx
  packages/apps/project/src/screens/TaskDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#774 feat: add ui config into storage with hooks
  changelogs/unreleased/86024.json
  packages/core/src/app/RootNavigator.js
  packages/core/src/auth/screens/SettingsScreen.js
  packages/core/src/hooks/use-storage-config.ts
  packages/core/src/index.ts
  packages/ui/src/config/ConfigContext.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#770 feat: use model and action api providers
  packages/apps/manufacturing/src/api/prod-product-api.js
  packages/apps/manufacturing/src/api/product-indicators-api.js
  packages/apps/project/src/api/project-api.js
  packages/apps/project/src/api/project-task-api.js
  packages/apps/project/src/api/reporting-api.js
  packages/apps/project/src/api/timesheet-lines-api.js
  packages/apps/sale/src/api/cart-api.js
  packages/apps/sale/src/api/cart-line-api.js
  packages/apps/sale/src/api/complementary-product-api.js
  packages/apps/sale/src/api/customer-api.js
  packages/apps/sale/src/api/customer-delivery-api.js
  packages/apps/sale/src/api/price-list-line-api.js
  packages/apps/sale/src/api/product-api.js
  packages/apps/sale/src/api/sale-config-api.js
  packages/apps/sale/src/api/sale-order-api.js
  packages/apps/sale/src/api/sale-order-line-api.js
  packages/apps/stock/src/api/product-indicators-api.js
  packages/apps/stock/src/api/tracking-number-api.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#775 fix: export useCameraScanner hook
  changelogs/unreleased/86102/json
  packages/core/src/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#776 fix: add new type for scan
  changelogs/unreleased/86107.json
  packages/core/src/components/external/Camera/Camera.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#778 feat: add possibility to manage active title globally on BottomBar
  changelogs/unreleased/86177.json
  packages/ui/src/components/templates/BottomBar/BarItem.tsx
  packages/ui/src/components/templates/BottomBar/BottomBar.tsx
  packages/ui/src/components/templates/BottomBar/ItemTitle.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#779 docs: update 8.0 to new format
  docs/doc/en/Application/Creation_d_un_ecran.md
  docs/doc/en/Application/Creation_d_un_menu.md
  docs/doc/en/Application/Creation_d_un_module.md
  docs/doc/en/Application/Creations_d_un_appel_API.md
  docs/doc/en/Application/Gestion_des_composants.md
  docs/doc/en/Application/Index.md
  docs/doc/en/Application/_category_.json
  docs/doc/en/Application/buildCustomization.md
  docs/doc/en/Architecture.md
  docs/doc/en/GettingStarted.md
  docs/doc/en/Introduction.md
  docs/doc/en/Outil/Gestion_des_headers.md
  docs/doc/en/Outil/Gestion_du_theme.md
  docs/doc/en/Outil/Gestions_de_camera.md
  docs/doc/en/Outil/Gestions_de_traductions.md
  docs/doc/en/Outil/Gestions_des_API_providers.md
  docs/doc/en/Outil/_category_.json
  docs/doc/en/Outil/gestion_des_erreurs.md
  docs/doc/en/Outil/gestions_de_store.md
  docs/doc/en/Outil/index.md
  docs/doc/en/pratique.md
  docs/doc/fr/Application/Creation_d_un_ecran.md
  docs/doc/fr/Application/Creation_d_un_menu.md
  docs/doc/fr/Application/Creation_d_un_module.md
  docs/doc/fr/Application/Creations_d_un_appel_API.md
  docs/doc/fr/Application/Gestion_des_composants.md
  docs/doc/fr/Application/Index.md
  docs/doc/fr/Application/_category_.json
  docs/doc/fr/Application/buildCustomization.md
  docs/doc/fr/Architecture.md
  docs/doc/fr/GettingStarted.md
  docs/doc/fr/Introduction.md
  docs/doc/fr/Outil/Gestion_des_headers.md
  docs/doc/fr/Outil/Gestion_du_theme.md
  docs/doc/fr/Outil/Gestions_de_camera.md
  docs/doc/fr/Outil/Gestions_de_traductions.md
  docs/doc/fr/Outil/Gestions_des_API_providers.md
  docs/doc/fr/Outil/_category_.json
  docs/doc/fr/Outil/gestion_des_erreurs.md
  docs/doc/fr/Outil/gestions_de_store.md
  docs/doc/fr/Outil/index.md
  docs/doc/fr/pratique.md
Labels: 📚 Documentation, ✅ Done, Approved 🌟

#780 docs: update 8.1 to new format
  docs/doc/en/Application/Creation_d_un_ecran.md
  docs/doc/en/Application/Creation_d_un_menu.md
  docs/doc/en/Application/Creation_d_un_module.md
  docs/doc/en/Application/Creations_d_un_appel_API.md
  docs/doc/en/Application/Gestion_des_composants.md
  docs/doc/en/Application/Index.md
  docs/doc/en/Application/_category_.json
  docs/doc/en/Application/buildCustomization.md
  docs/doc/en/Architecture.md
  docs/doc/en/GettingStarted.md
  docs/doc/en/Introduction.md
  docs/doc/en/Outil/Gestion_des_headers.md
  docs/doc/en/Outil/Gestion_du_theme.md
  docs/doc/en/Outil/Gestions_de_camera.md
  docs/doc/en/Outil/Gestions_de_traductions.md
  docs/doc/en/Outil/Gestions_des_API_providers.md
  docs/doc/en/Outil/_category_.json
  docs/doc/en/Outil/gestion_des_erreurs.md
  docs/doc/en/Outil/gestions_de_store.md
  docs/doc/en/Outil/index.md
  docs/doc/en/Outil/permissionManagement.md
  docs/doc/en/Outil/selectionManagement.md
  docs/doc/en/pratique.md
  docs/doc/fr/Application/Creation_d_un_ecran.md
  docs/doc/fr/Application/Creation_d_un_menu.md
  docs/doc/fr/Application/Creation_d_un_module.md
  docs/doc/fr/Application/Creations_d_un_appel_API.md
  docs/doc/fr/Application/Gestion_des_composants.md
  docs/doc/fr/Application/Index.md
  docs/doc/fr/Application/_category_.json
  docs/doc/fr/Application/buildCustomization.md
  docs/doc/fr/Architecture.md
  docs/doc/fr/GettingStarted.md
  docs/doc/fr/Introduction.md
  docs/doc/fr/Outil/Gestion_des_headers.md
  docs/doc/fr/Outil/Gestion_du_theme.md
  docs/doc/fr/Outil/Gestions_de_camera.md
  docs/doc/fr/Outil/Gestions_de_traductions.md
  docs/doc/fr/Outil/Gestions_des_API_providers.md
  docs/doc/fr/Outil/_category_.json
  docs/doc/fr/Outil/gestion_des_erreurs.md
  docs/doc/fr/Outil/gestions_de_store.md
  docs/doc/fr/Outil/index.md
  docs/doc/fr/Outil/permissionManagement.md
  docs/doc/fr/Outil/selectionManagement.md
  docs/doc/fr/pratique.md
Labels: 📚 Documentation, ✅ Done, Approved 🌟

#777 feat: enable login page override
  changelogs/unreleased/86091.json
  docs/doc/en/GettingStarted.md
  docs/doc/fr/GettingStarted.md
  packages/core/src/app/Application.tsx
  packages/core/src/app/ContextedApplication.tsx
  packages/core/src/app/RootNavigator.js
  packages/core/src/features/authSlice.js
  packages/core/src/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#782 fix: disable pressable area on IndicatorChart in stock
  changelogs/unreleased/86381.json
  packages/apps/stock/src/components/templates/product/ProductCardStockIndicatorList/ProductCardStockIndicatorList.js
Labels: 🐛 Bug, ✅ Done
