Repository axelor/axelor-mobile, pull requests merged in 2025-07, with the labels that each got.

#1014 fix: resolve issue on variant selection popup
  changelogs/unreleased/97314.json
  packages/apps/sale/src/api/product-api.js
  packages/apps/sale/src/components/molecules/CatalogActionCard/CatalogActionCard.tsx
Labels: 🐛 Bug, ✅ Done

#1009 feat: add quick access to QI creation
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderDetailsScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderDetailsScreen.js
  packages/apps/quality/src/api/index.ts
  packages/apps/quality/src/api/manuf-order-api.js
  packages/apps/quality/src/api/operation-order-api.js
  packages/apps/quality/src/api/purchase-order-api.js
  packages/apps/quality/src/api/qi-detection-api.js
  packages/apps/quality/src/api/sale-order-api.js
  packages/apps/quality/src/api/stock-move-api.js
  packages/apps/quality/src/components/templates/CustomerOrderSearchBar/CustomerOrderSearchBar.tsx
  packages/apps/quality/src/components/templates/QIDetectionSearchBar/QIDetectionSearchBar.tsx
  packages/apps/quality/src/components/templates/SupplierOrderSearchBar/SupplierOrderSearchBar.tsx
  packages/apps/quality/src/features/asyncFunctions-index.ts
  packages/apps/quality/src/features/index.js
  packages/apps/quality/src/features/manufOrderSlice.js
  packages/apps/quality/src/features/operationOrderSlice.js
  packages/apps/quality/src/features/stockMoveSlice.js
  packages/apps/quality/src/i18n/en.json
  packages/apps/quality/src/i18n/fr.json
  packages/apps/quality/src/index.ts
  packages/apps/quality/src/models/forms.ts
  packages/apps/quality/src/models/objectFields.ts
  packages/apps/quality/src/screens/QualityImprovement/QualityImprovementFormScreen.tsx
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalDetailsScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#1013 feat: use request to create/update a QI
  packages/apps/quality/src/api/index.ts
  packages/apps/quality/src/api/quality-improvement-api.js
  packages/apps/quality/src/components/molecules/QIFormButton/QIFormButton.tsx
  packages/apps/quality/src/components/templates/DefectViewAllList/DefectViewAllList.tsx
  packages/apps/quality/src/features/asyncFunctions-index.ts
  packages/apps/quality/src/features/qualityImprovementSlice.js
  packages/apps/quality/src/i18n/en.json
  packages/apps/quality/src/i18n/fr.json
  packages/apps/quality/src/screens/QualityImprovement/QualityImprovementFormScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#1021 refactor: use rntl test for Input component
  packages/ui/__tests__/components/atoms/Input.test.js
Labels: 🪄 Test, ✅ Done, Approved 🌟

#1026 refactor: use rntl for Icon component
  packages/ui/__tests__/components/atoms/Icon.test.js
  packages/ui/src/components/atoms/Icon/Icon.tsx
Labels: 🪄 Test, ✅ Done

#1027 fix: resolve issue on InternalMove notes from line details
  changelogs/release/97544.json
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#1033 refactor: use rntl test for Switch component
  packages/ui/__tests__/components/atoms/Switch.test.js
  packages/ui/src/components/atoms/Switch/Switch.tsx
Labels: 🪄 Test, ✅ Done, Approved 🌟

#1034 fix: add click outside management on HtmlInput
  changelogs/unreleased/98006.json
  packages/ui/src/components/atoms/HtmlInput/HtmlInput.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#1039 feat: add CheckListView component
  packages/apps/project/src/api/check-list-api.ts
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/components/atoms/CheckListItemCard/CheckListItemCard.tsx
  packages/apps/project/src/components/atoms/ParentCheckListItemCard/ParentCheckListItemCard.tsx
  packages/apps/project/src/components/atoms/index.ts
  packages/apps/project/src/components/molecules/CheckListItemActionCard/CheckListItemActionCard.tsx
  packages/apps/project/src/components/molecules/index.ts
  packages/apps/project/src/components/templates/CheckListView/CheckListView.tsx
  packages/apps/project/src/components/templates/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/checkListSlice.js
  packages/apps/project/src/features/index.js
  packages/apps/project/src/hooks/index.ts
  packages/apps/project/src/hooks/use-check-list-item-actions.ts
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/models/searchFields.ts
  packages/apps/project/src/models/sortFields.ts
  packages/apps/project/src/types/check-list-item-status.ts
  packages/apps/project/src/types/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#1043 refactor: improve StockMoveLine cards display
  changelogs/unreleased/97720.json
  changelogs/unreleased/97720_objectCard.json
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx
  packages/ui/__tests__/components/atoms/BootstrapIcon.test.js
  packages/ui/__tests__/components/atoms/Icon.test.js
  packages/ui/__tests__/components/molecules/Button.test.js
  packages/ui/__tests__/components/templates/ObjectCard.test.js
  packages/ui/src/components/atoms/BootstrapIcon/BootstrapIcon.tsx
  packages/ui/src/components/molecules/Image/Image.tsx
  packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#1044 feat: add maintenance request list screen
  changelogs/unreleased/97551_machine.json
  packages/apps/maintenance/package.json
  packages/apps/maintenance/src/api/index.ts
  packages/apps/maintenance/src/api/maintenance-request-api.ts
  packages/apps/maintenance/src/components/atoms/MaintenanceRequestCard/MaintenanceRequestCard.tsx
  packages/apps/maintenance/src/components/atoms/index.ts
  packages/apps/maintenance/src/components/index.ts
  packages/apps/maintenance/src/components/molecules/ActionTypePicker/ActionTypePicker.tsx
  packages/apps/maintenance/src/components/molecules/index.ts
  packages/apps/maintenance/src/components/organisms/MaintenanceRequestFilters/MaintenanceRequestFilters.tsx
  packages/apps/maintenance/src/components/organisms/index.ts
  packages/apps/maintenance/src/features/asyncFunctions-index.ts
  packages/apps/maintenance/src/features/index.ts
  packages/apps/maintenance/src/features/maintenanceRequestSlice.js
  packages/apps/maintenance/src/hooks/use-maintenance-header-actions.ts
  packages/apps/maintenance/src/i18n/en.json
  packages/apps/maintenance/src/i18n/fr.json
  packages/apps/maintenance/src/index.ts
  packages/apps/maintenance/src/models/index.ts
  packages/apps/maintenance/src/models/objectFields.ts
  packages/apps/maintenance/src/models/searchFields.ts
  packages/apps/maintenance/src/models/sortFields.ts
  packages/apps/maintenance/src/models/typeObjects.ts
  packages/apps/maintenance/src/screens/MaintenanceRequestListScreen.tsx
  packages/apps/maintenance/src/screens/index.ts
  packages/apps/manufacturing/src/components/templates/MachineSearchBar/MachineSearchBar.tsx
Labels: 🌟 Feature, ✅ Done

#1045 feat: add maintenance request form view
  changelogs/unreleased/97552_navigation.json
  changelogs/unreleased/97552_radioSelect.json
  packages/apps/maintenance/src/api/equipement-maintenance-api.ts
  packages/apps/maintenance/src/api/index.ts
  packages/apps/maintenance/src/api/maintenance-request-api.ts
  packages/apps/maintenance/src/components/atoms/EquipementMaintenanceCard/EquipementMaintenanceCard.tsx
  packages/apps/maintenance/src/components/atoms/index.ts
  packages/apps/maintenance/src/components/molecules/ActionRadioSelect/ActionRadioSelect.tsx
  packages/apps/maintenance/src/components/molecules/EquipementMaintenanceActionCard/EquipementMaintenanceActionCard.tsx
  packages/apps/maintenance/src/components/molecules/index.ts
  packages/apps/maintenance/src/components/organisms/EquipementMaintenanceSearchBar/EquipementMaintenanceSearchBar.tsx
  packages/apps/maintenance/src/components/organisms/index.ts
  packages/apps/maintenance/src/features/asyncFunctions-index.ts
  packages/apps/maintenance/src/features/equipementMaintenanceSlice.ts
  packages/apps/maintenance/src/features/index.ts
  packages/apps/maintenance/src/features/maintenanceRequestSlice.ts
  packages/apps/maintenance/src/i18n/en.json
  packages/apps/maintenance/src/i18n/fr.json
  packages/apps/maintenance/src/index.ts
  packages/apps/maintenance/src/models/forms.ts
  packages/apps/maintenance/src/models/index.ts
  packages/apps/maintenance/src/models/objectFields.ts
  packages/apps/maintenance/src/models/searchFields.ts
  packages/apps/maintenance/src/models/sortFields.ts
  packages/apps/maintenance/src/screens/MaintenanceRequestFormScreen.tsx
  packages/apps/maintenance/src/screens/index.ts
  packages/core/src/hooks/index.ts
  packages/core/src/hooks/use-navigation.ts
  packages/ui/__tests__/components/molecules/RadioSelect.test.js
  packages/ui/src/components/molecules/RadioSelect/RadioSelect.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#1048 feat: add management of default qiDetection value
  changelogs/unreleased/97411.json
  packages/apps/quality/src/api/index.ts
  packages/apps/quality/src/api/qi-detection-api.js
  packages/apps/quality/src/features/asyncFunctions-index.ts
  packages/apps/quality/src/features/qiDetectionSlice.js
  packages/apps/quality/src/i18n/en.json
  packages/apps/quality/src/i18n/fr.json
  packages/apps/quality/src/models/objectFields.ts
  packages/apps/quality/src/screens/QualityImprovement/QualityImprovementFormScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#1052 refactor: improve date display on event form
  changelogs/unreleased/97179.json
  changelogs/unreleased/97179_periodInput.json
  packages/apps/crm/src/components/organisms/EventPeriodInput/EventPeriodInput.tsx
  packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
Labels: 🐛 Bug, ✅ Done

#1051 feat: add disponibility display on SaleOrderLine
  changelogs/unreleased/97321.json
  changelogs/unreleased/97321_cardProduct.json
  changelogs/unreleased/97321_priceListCard.json
  packages/apps/sale/src/components/atoms/PriceDetails/PriceDetails.tsx
  packages/apps/sale/src/components/atoms/ProductCard/ProductCard.tsx
  packages/apps/sale/src/components/atoms/SaleOrderLineCard/SaleOrderLineCard.tsx
  packages/apps/sale/src/components/molecules/SaleOrderLineAvailabilityBadges/SaleOrderLineAvailabilityBadges.tsx
  packages/apps/sale/src/components/molecules/SaleOrderLinePriceDetails/SaleOrderLinePriceDetails.tsx
  packages/apps/sale/src/components/molecules/index.ts
  packages/apps/sale/src/hooks/index.ts
  packages/apps/sale/src/hooks/use-sale-order-line-availability.ts
  packages/apps/sale/src/i18n/en.json
  packages/apps/sale/src/i18n/fr.json
  packages/apps/sale/src/index.ts
  packages/apps/sale/src/models/objectFields.ts
  packages/apps/sale/src/models/typeObjects.ts
  packages/apps/sale/src/screens/saleOrder/SaleOrderLineDetailsScreen.tsx
  packages/apps/sale/src/screens/saleOrder/SaleOrderLineListScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#1055 fix: resolve key and format issues with camera scanner
  changelogs/unreleased/98571.json
  changelogs/unreleased/98571_cameraKey.json
  packages/core/src/features/cameraScannerSlice.ts
  packages/core/src/utils/formatters.ts
Labels: 🐛 Bug, ✅ Done

#1057 fix: improve formatting on increment input
  changelogs/unreleased/98824.json
  packages/ui/__tests__/components/molecules/Increment.test.js
  packages/ui/src/components/molecules/Increment/Increment.tsx
  packages/ui/src/utils/formatters.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟
