Repository axelor/axelor-mobile, pull requests merged in 2025-04, with the labels that each got.

#931 feat: add FilterContainer component
  packages/core/src/components/organisms/FilterContainer/FilterContainer.tsx
  packages/core/src/components/organisms/PopupFilters/PopupFilters.tsx
  packages/core/src/components/organisms/index.js
  packages/core/src/header/FilterProvider.tsx
  packages/core/src/header/hooks.js
Labels: 🌟 Feature, ✅ Done, Pair approved 🌟

#951 refactor: use generic action for default model actions
  changelogs/unreleased/92521.json
  docs/doc/en/tools/60_headers.md
  docs/doc/fr/tools/60_headers.md
  packages/apps/dms/src/utils/attachedFilesGenericAction.ts
  packages/apps/message/src/utils/mailMessagesGenericAction.ts
  packages/core/src/api/index.ts
  packages/core/src/api/print-template-api.js
  packages/core/src/components/organisms/FilterContainer/FilterContainer.tsx
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/core/src/components/organisms/PopupFilters/PopupFilters.tsx
  packages/core/src/components/organisms/PopupPrintTemplate/PopupPrintTemplate.tsx
  packages/core/src/features/asyncFunctions-index.ts
  packages/core/src/forms/studio/api.helpers.ts
  packages/core/src/header/FilterProvider.tsx
  packages/core/src/header/hooks.js
  packages/core/src/header/hooks.tsx
  packages/core/src/header/types.ts
  packages/core/src/hooks/index.ts
  packages/core/src/hooks/use-header-registers.js
  packages/core/src/index.ts
  packages/core/src/models/objectFields.ts
  packages/core/src/navigator/drawer/Header.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#952 feat: remove unused dependencies on header hooks
  docs/doc/en/tools/60_headers.md
  docs/doc/fr/tools/60_headers.md
  packages/apps/crm/src/hooks/use-crm-header-actions.ts
  packages/apps/helpdesk/src/hooks/use-helpdesk-header-actions.ts
  packages/apps/hr/src/hooks/use-hr-header-actions.js
  packages/apps/hr/src/screens/expense/ExpenseLineFormScreen.js
  packages/apps/hr/src/screens/timesheet/TimerFormScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js
  packages/apps/intervention/src/hooks/use-intervention-header-actions.ts
  packages/apps/manufacturing/src/hooks/use-manufacturing-headers.js
  packages/apps/project/src/hooks/use-project-header-actions.ts
  packages/apps/purchase/src/hooks/use-purchase-header-actions.ts
  packages/apps/sale/src/hooks/use-sale-header-actions.ts
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
  packages/apps/stock/src/hooks/use-stock-header-actions.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#944 feat: add quickAction to access product availability on stock
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineActionCard/CustomerDeliveryLineActionCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineActionCard/InternalMoveLineActionCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineCard/InternalMoveLineCard.tsx
  packages/apps/stock/src/components/templates/internalMove/InternalMoveSearchLineContainer/InternalMoveSearchLineContainer.js
  packages/apps/stock/src/components/templates/internalMove/index.js
  packages/apps/stock/src/components/templates/inventory/InventoryLineActionCard/InventoryLineActionCard.tsx
  packages/apps/stock/src/components/templates/inventory/InventoryLineCard/InventoryLineCard.tsx
  packages/apps/stock/src/components/templates/inventory/InventorySearchLineContainer/InventorySearchLineContainer.js
  packages/apps/stock/src/components/templates/inventory/index.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryStartedDetailsScreen.js
Labels: 🌟 Feature, ✅ Done, Pair approved 🌟

#954 fix: modify dms extension filter management
  changelogs/unreleased/92917.json
  packages/apps/dms/src/api/document-api.js
  packages/apps/dms/src/components/atoms/DocumentCard/DocumentCard.tsx
Labels: 🐛 Bug, ✅ Done

#955 fix: remove illegal characters before downloading
  changelogs/unreleased/92918.json
  packages/core/src/tools/FileDownloader.ts
Labels: 🐛 Bug, ✅ Done

#956 refactor: improve compatibility error messages
  changelogs/unreleased/92598.json
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/navigator/drawer/Menu.js
  packages/core/src/navigator/drawer/MenuIconButton.js
  packages/core/src/navigator/drawer/MenuItemEntry.js
  packages/core/src/navigator/drawer/MenuTitle.js
  packages/core/src/navigator/menu.helper.js
Labels: 🐛 Bug, ✅ Done

#961 fix: add null check on webConfig
  changelogs/unreleased/93630.json
  packages/apps/hr/src/components/molecules/TimesheetDetailCard/TimesheetDetailCard.tsx
  packages/apps/hr/src/components/templates/TimesheetFilters/TimesheetFilters.js
  packages/apps/hr/src/models/forms.ts
  packages/apps/hr/src/screens/timesheet/TimesheetDetailsScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js
  packages/apps/stock/src/components/templates/AvailableProductsSearchBar/AvailableProductsSearchBar.js
  packages/apps/stock/src/components/templates/ProductSearchBar/ProductSearchBar.js
  packages/apps/stock/src/components/templates/ProductTrackingNumberSearchBar/ProductTrackingNumberSearchBar.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineCreationScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/apps/stock/src/screens/products/ProductListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineCreationScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#965 fix: correctly create datawedge profile
  changelogs/unreleased/93663.json
  packages/core/src/components/external/Scanner/Scanner.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#950 feat: add messenger header action on user screen
  packages/apps/message/src/api/index.ts
  packages/apps/message/src/api/mail-message-api.ts
  packages/apps/message/src/components/atoms/ReadIcon/ReadIcon.tsx
  packages/apps/message/src/components/molecules/CommentCard/CommentCard.tsx
  packages/apps/message/src/components/molecules/NotificationCard/NotificationCard.tsx
  packages/apps/message/src/components/organisms/MailMessageCard/MailMessageCard.tsx
  packages/apps/message/src/components/templates/MailMessageView/MailMessageView.tsx
  packages/apps/message/src/features/asyncFunctions-index.ts
  packages/apps/message/src/features/mailMessageSlice.js
  packages/apps/message/src/hooks/use-message-header-actions.tsx
  packages/apps/message/src/i18n/en.json
  packages/apps/message/src/i18n/fr.json
  packages/apps/message/src/screens/InboxScreen.tsx
  packages/apps/message/src/screens/index.ts
  packages/apps/project/src/components/molecules/ActivityCard/ActivityCard.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#957 feat: improve header action with unread messages count
  packages/apps/message/src/hooks/use-message-header-actions.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#958 refactor: use AOP filter on Helpedsk list views
  changelogs/unreleased/92480.json
  packages/apps/helpdesk/src/api/ticket-api.js
  packages/apps/helpdesk/src/hooks/use-helpdesk-header-actions.ts
  packages/apps/helpdesk/src/screens/index.js
Labels: 🔧 Refactor, ✅ Done, Pair approved 🌟

#966 refactor: use AOP filter on Purchase list views
  changelogs/unreleased/92486.json
  packages/apps/purchase/src/api/purchase-request-api.js
  packages/apps/purchase/src/hooks/use-purchase-header-actions.ts
  packages/apps/purchase/src/screens/index.ts
Labels: 🔧 Refactor, ✅ Done, Pair approved 🌟

#968 refactor: use AOP filter on Sale list Views
  changelogs/unreleased/92488.json
  packages/apps/sale/src/api/customer-api.js
  packages/apps/sale/src/api/product-api.js
  packages/apps/sale/src/api/sale-order-api.js
  packages/apps/sale/src/hooks/use-sale-header-actions.ts
  packages/apps/sale/src/screens/cart/index.ts
  packages/apps/sale/src/screens/client/index.ts
  packages/apps/sale/src/screens/product/index.ts
  packages/apps/sale/src/screens/saleOrder/index.ts
Labels: 🔧 Refactor, ✅ Done, Pair approved 🌟

#962 refactor: use AOP filter on Intervention list views
  changelogs/unreleased/92482.json
  packages/apps/intervention/src/api/intervention-api.js
  packages/apps/intervention/src/hooks/use-intervention-header-actions.ts
  packages/apps/intervention/src/screens/intervention/index.ts
  packages/core/src/header/hooks.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#969 feat: add AOP filter on Stock list Views
  changelogs/unreleased/92489.json
  packages/apps/stock/src/api/customer-delivery-api.js
  packages/apps/stock/src/api/internal-move-api.js
  packages/apps/stock/src/api/inventory-api.js
  packages/apps/stock/src/api/product-api.js
  packages/apps/stock/src/api/stock-correction-api.js
  packages/apps/stock/src/api/supplier-arrival-api.js
  packages/apps/stock/src/hooks/use-stock-header-actions.js
  packages/apps/stock/src/screens/customerDeliveries/index.js
  packages/apps/stock/src/screens/inventories/index.js
  packages/apps/stock/src/screens/products/index.js
  packages/apps/stock/src/screens/stockCorrections/StockCorrectionListScreen.js
  packages/apps/stock/src/screens/supplierArrivals/index.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#963 refactor: use AOP filter on Manufacturing list views
  changelogs/unreleased/92483.json
  packages/apps/manufacturing/src/api/manufacturing-order-api.js
  packages/apps/manufacturing/src/api/operation-order-api.js
  packages/apps/manufacturing/src/hooks/use-manufacturing-headers.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/index.js
  packages/apps/manufacturing/src/screens/operationOrder/index.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#964 refactor: use AOPfilter on Project list views
  changelogs/unreleased/92485.json
  packages/apps/project/src/api/project-api.js
  packages/apps/project/src/api/project-task-api.js
  packages/apps/project/src/hooks/use-project-header-actions.ts
  packages/apps/project/src/screens/index.ts
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#959 refactor: use AOP filter on Hr list views
  changelogs/unreleased/92481.json
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/leave-api.js
  packages/apps/hr/src/api/timer-api.js
  packages/apps/hr/src/api/timesheet-api.js
  packages/apps/hr/src/hooks/use-hr-header-actions.js
  packages/apps/hr/src/screens/expense/ExpenseListScreen.js
  packages/apps/hr/src/screens/leaveRequests/LeaveListScreen.tsx
  packages/apps/hr/src/screens/leaveRequests/index.ts
  packages/apps/hr/src/screens/timesheet/TimerListScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#974 fix: remove section field management in project task
  changelogs/unreleased/93961.json
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/project-task-api.js
  packages/apps/project/src/components/molecules/DropdownTaskCharacteristics/DropdownTaskCharacteristics.tsx
  packages/apps/project/src/components/organisms/ProjectTaskDropdownCards/ProjectTaskDropdownCards.tsx
  packages/apps/project/src/components/templates/SectionSearchBar/SectionSearchBar.tsx
  packages/apps/project/src/components/templates/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/projectTaskSlice.js
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/forms.ts
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/models/searchFields.ts
Labels: 🔧 Refactor, ✅ Done

#975 feat: add config management for inbox access
  packages/apps/message/src/hooks/use-message-header-actions.tsx
Labels: 🌟 Feature, ✅ Done

#972 refactor: migrate lib for document selection
  changelogs/unreleased/92237.json
  changelogs/unreleased/92237_lib.json
  ios/Podfile.lock
  package.json
  packages/core/package.json
  packages/core/src/api/metafile-api.ts
  packages/core/src/components/molecules/UploadFileInput/UploadFileInput.tsx
  packages/core/src/tools/FilePicker.ts
  patches/react-native+0.74.6.patch
  yarn.lock
Labels: 🔧 Refactor, ✅ Done

#973 refactor: remove font awesome support
  .storybook/preview.tsx
  __mocks__/react-native-vector-icons/FontAwesome.js
  __mocks__/react-native-vector-icons/FontAwesome5.js
  changelogs/unreleased/93869.json
  docs/doc/en/application/10_components.md
  docs/doc/fr/application/10_components.md
  ios/AosMobile.xcodeproj/project.pbxproj
  ios/AosMobile/Info.plist
  ios/Podfile.lock
  jest.config.js
  package.json
  packages/ui/__tests__/components/atoms/Icon.test.js
  packages/ui/package.json
  packages/ui/src/components/atoms/Icon/Icon.tsx
  packages/ui/stories/atoms/Icon.stories.tsx
  yarn.lock
Labels: 🔧 Refactor, ✅ Done

#979 refactor: use new tool to format totals with currency in sale
  changelogs/unreleased/93017.json
  packages/apps/sale/src/components/atoms/SaleOrderCard/SaleOrderCard.tsx
  packages/apps/sale/src/components/atoms/SaleOrderLineCard/SaleOrderLineCard.tsx
  packages/apps/sale/src/components/molecules/SaleOrderLinePriceDetails/SaleOrderLinePriceDetails.tsx
  packages/apps/sale/src/components/molecules/SaleOrderPriceDetails/SaleOrderPriceDetails.tsx
  packages/apps/sale/src/components/organisms/DropDownSaleOrderView/DropDownSaleOrderView.tsx
  packages/apps/sale/src/components/pages/SaleOrderListView/SaleOrderListView.tsx
  packages/apps/sale/src/screens/saleOrder/SaleOrderLineListScreen.tsx
Labels: 🔧 Refactor, ✅ Done

#980 fix: remove illegal characters from filename before uploading
  changelogs/unreleased/93996.json
  packages/core/src/api/metafile-api.ts
  packages/core/src/tools/FileDownloader.ts
  packages/core/src/utils/file.ts
  packages/core/src/utils/index.ts
Labels: 🐛 Bug, ✅ Done

#960 feat: manage attached files through dms package
  changelogs/unreleased/92656_AttachmentCard.json
  changelogs/unreleased/92656_DocumentActionCard.json
  changelogs/unreleased/92656_searchDocument.json
  packages/apps/dms/src/api/document-api.js
  packages/apps/dms/src/components/molecules/DocumentActionCard/DocumentActionCard.tsx
  packages/apps/manufacturing/src/i18n/en.json
  packages/apps/manufacturing/src/i18n/fr.json
  packages/apps/message/package.json
  packages/apps/message/src/screens/MailMessageAttachedFilesScreen.tsx
  packages/apps/message/src/screens/index.ts
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/core/src/features/asyncFunctions-index.ts
  packages/core/src/features/attachedFilesSlice.js
  packages/core/src/features/index.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/screens/MailMessageAttachedFilesScreen.tsx
  packages/core/src/screens/index.js
  packages/core/src/tools/FileDownloader.ts
  packages/ui/__tests__/components/molecules/AttachmentCard.test.js
  packages/ui/src/components/molecules/AttachmentCard/AttachmentCard.tsx
  packages/ui/src/components/molecules/index.tsx
  packages/ui/src/types/file.js
  packages/ui/src/types/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#982 fix: can't upload file with accents in name
  packages/core/src/utils/file.ts
Labels: 🐛 Bug, ✅ Done, Pair approved 🌟

#981 feat: manage timesheet line duration unit
  changelogs/unreleased/91293.json
  packages/apps/hr/src/components/templates/DurationTimeSheetLine/DurationTimeSheetLine.tsx
  packages/apps/hr/src/components/templates/index.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/models/forms.ts
  packages/apps/hr/src/models/typeObjects.ts
  packages/apps/hr/src/screens/timesheet/TimesheetLineFormScreen.js
  packages/apps/project/src/components/organisms/LogTimeButton/LogTimeButton.tsx
  packages/apps/project/src/components/pages/TimeView/TimeView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#986 fix: use the correct product Api import
  changelogs/unreleased/94447.json
  packages/apps/manufacturing/src/features/prodProductSlice.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟
