Repository axelor/axelor-mobile, pull requests merged in 2025-05, with the labels that each got.

#991 fix: resolve null issue on intervention contact
  changelogs/unreleased/94849.json
  packages/apps/intervention/src/components/organisms/DropdownCards/DropdownCards.tsx
Labels: 🐛 Bug, ✅ Done

#992 fix: remove duplicated screen name on inventory line navigation
  changelogs/unreleased/94850.json
  packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js
Labels: 🐛 Bug, ✅ Done

#984 feat: add responses management
  packages/apps/message/src/api/index.ts
  packages/apps/message/src/api/mail-message-api.ts
  packages/apps/message/src/components/atoms/Avatar/Avatar.tsx
  packages/apps/message/src/components/atoms/ReadIcon/ReadIcon.tsx
  packages/apps/message/src/components/atoms/index.ts
  packages/apps/message/src/components/molecules/CommentCard/CommentCard.tsx
  packages/apps/message/src/components/molecules/NotificationCard/NotificationCard.tsx
  packages/apps/message/src/components/organisms/MailMessageCard/MailMessageCard.tsx
  packages/apps/message/src/screens/InboxScreen.tsx
Labels: 🌟 Feature, ✅ Done, Pair approved 🌟

#987 feat: test migrate tests from enzyme to RNTL
  jest.config.js
  package.json
  packages/ui/__tests__/components/atoms/Text.test.js
  packages/ui/__tests__/components/molecules/Button.test.js
  packages/ui/src/components/atoms/BootstrapIcon/BootstrapIcon.tsx
  packages/ui/src/components/molecules/Button/Button.tsx
  yarn.lock
Labels: 🪄 Test, ✅ Done, Approved 🌟

#994 fix: address is not automatically filled when clicking on map widget
  changelogs/unreleased/94928.json
  packages/core/src/tools/linking.helper.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#948 feat: add MassScanner component
  changelogs/unreleased/92726.json
  docs/doc/en/tools/80_cameraScanner.md
  docs/doc/fr/tools/80_cameraScanner.md
  packages/core/src/components/organisms/MassScannerButton/MassScannerButton.tsx
  packages/core/src/components/organisms/index.js
  packages/core/src/features/cameraScannerSlice.ts
  packages/core/src/hooks/index.ts
  packages/core/src/hooks/use-mass-scanner.ts
  packages/core/src/hooks/use-scan-activator.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟
