Repository axelor/axelor-mobile, pull requests merged in 2025-09, with the labels that each got.

#1080 refactor: move business menu entry to enterprise package
  packages/apps/project/src/api/project-api.js
  packages/apps/project/src/components/templates/ProjectListView/ProjectListView.tsx
  packages/apps/project/src/components/templates/ProjectSearchBar/ProjectSearchBar.tsx
  packages/apps/project/src/components/templates/TaskFilters/TaskFilters.tsx
  packages/apps/project/src/hooks/use-project-header-actions.ts
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/index.ts
  packages/apps/project/src/models/forms.ts
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/screens/Project/ActiveProjectScreen.tsx
  packages/apps/project/src/screens/Project/ProjectDetailsScreen.tsx
  packages/apps/project/src/screens/Project/ProjectListScreen.tsx
  packages/apps/project/src/screens/Project/index.ts
  packages/apps/project/src/screens/Task/TaskDetailsScreen.tsx
  packages/apps/project/src/screens/Task/TaskFormScreen.tsx
  packages/apps/project/src/screens/Task/TaskListScreen.tsx
  packages/apps/project/src/screens/Task/index.ts
  packages/apps/project/src/screens/index.ts
Labels: 🔧 Refactor, ✅ Done

#1077 feat: add checklist item deletion management
  packages/apps/project/src/api/check-list-api.ts
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/checkListSlice.js
  packages/apps/project/src/hooks/use-check-list-item-actions.ts
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done

#1084 refactor: remove reporting and invoicing from project details view
  packages/apps/project/src/api/index.ts
  packages/apps/project/src/api/reporting-api.js
  packages/apps/project/src/components/molecules/DropdownInvoicing/DropdownInvoicing.tsx
  packages/apps/project/src/components/molecules/ProjectHeader/ProjectHeader.tsx
  packages/apps/project/src/components/molecules/index.ts
  packages/apps/project/src/components/organisms/ProjectDropdownCards/ProjectDropdownCards.tsx
  packages/apps/project/src/components/pages/GeneralInformationView/GeneralInformationView.tsx
  packages/apps/project/src/components/pages/ReportingView/ReportingView.tsx
  packages/apps/project/src/components/templates/ReportingDetailsView/IndicatorCategory.tsx
  packages/apps/project/src/components/templates/ReportingDetailsView/ReportingDetailsView.tsx
  packages/apps/project/src/components/templates/index.ts
  packages/apps/project/src/features/asyncFunctions-index.ts
  packages/apps/project/src/features/index.js
  packages/apps/project/src/features/reportingSlice.js
  packages/apps/project/src/hooks/use-reporting-configuration.ts
  packages/apps/project/src/i18n/en.json
  packages/apps/project/src/i18n/fr.json
  packages/apps/project/src/models/objectFields.ts
  packages/apps/project/src/models/typeObjects.ts
  packages/apps/project/src/screens/Project/ProjectDetailsScreen.tsx
  packages/apps/project/src/types/index.ts
  packages/apps/project/src/types/reporting-type.ts
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#1083 feat: add LogisticalFormCarrierDetailsView
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/api/logistical-form-api.ts
  packages/apps/stock/src/components/atoms/CarrierCard/CarrierCard.tsx
  packages/apps/stock/src/components/atoms/LogisticalFormDropdownGeneralView/LogisticalFormDropdownGeneralView.tsx
  packages/apps/stock/src/components/atoms/index.ts
  packages/apps/stock/src/components/molecules/CarrierActionCard/CarrierActionCard.tsx
  packages/apps/stock/src/components/molecules/LogisticalFormDropdownCards/LogisticalFormDropdownCards.tsx
  packages/apps/stock/src/components/molecules/index.js
  packages/apps/stock/src/components/templates/logisticalForm/LogisticalFormGeneralInformationView/LogisticalFormGeneralInformationView.tsx
  packages/apps/stock/src/components/templates/logisticalForm/LogisticalFormHeader/LogisticalFormHeader.tsx
  packages/apps/stock/src/components/templates/logisticalForm/index.ts
  packages/apps/stock/src/features/asyncFunctions-index.ts
  packages/apps/stock/src/features/logisticalFormSlice.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/models/typeObjects.ts
  packages/apps/stock/src/screens/logisticalForms/LogisticalFormDetailsScreen.tsx
  packages/apps/stock/src/screens/logisticalForms/LogisticalFormListScreen.tsx
  packages/apps/stock/src/screens/logisticalForms/index.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#1085 feat: add logistical form creation management
  changelogs/unreleased/100985_stock-location-search-bar.json
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/api/logistical-form-api.ts
  packages/apps/stock/src/components/templates/PartnerSearchBar/PartnerSearchBar.tsx
  packages/apps/stock/src/components/templates/StockLocationSearchBar/StockLocationSearchBar.tsx
  packages/apps/stock/src/components/templates/logisticalForm/LogisticalFormFilter/LogisticalFormFilter.tsx
  packages/apps/stock/src/features/asyncFunctions-index.ts
  packages/apps/stock/src/features/logisticalFormSlice.js
  packages/apps/stock/src/hooks/use-stock-header-actions.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/index.ts
  packages/apps/stock/src/models/forms.ts
  packages/apps/stock/src/models/index.ts
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryLineDetailScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveLineDetailsScreen.js
  packages/apps/stock/src/screens/logisticalForms/LogisticalFormDetailsScreen.tsx
  packages/apps/stock/src/screens/logisticalForms/LogisticalFormFormScreen.tsx
  packages/apps/stock/src/screens/logisticalForms/index.ts
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalLineDetailScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟
