Repository axelor/axelor-mobile, pull requests merged in 2025-06, with the labels that each got.

#998 refactor: improve sale & purchase order qty indicator card
  changelogs/unreleased/96018.json
  changelogs/unreleased/96018_badges.json
  changelogs/unreleased/96018_date.json
  packages/apps/stock/src/components/atoms/OrderQtyIndicatorCard/OrderQtyIndicatorCard.tsx
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/models/objectFields.ts
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#999 refactor: improve search fields on stock move
  changelogs/unreleased/96016.json
  packages/apps/stock/src/models/searchFields.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#1000 fix: add missing information on line verification
  changelogs/unreleased/95900.json
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectProductScreen.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliverySelectTrackingScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveSelectProductScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveSelectTrackingScreen.js
  packages/apps/stock/src/screens/inventories/InventorySelectProductScreen.js
  packages/apps/stock/src/screens/inventories/InventorySelectTrackingScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectProductScreen.js
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalSelectTrackingScreen.js
  packages/apps/stock/src/utils/line-navigation.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#1002 refactor: display time instead of date time information
  changelogs/unreleased/95510.json
  packages/apps/message/src/components/atoms/AuthorText/AuthorText.tsx
  packages/apps/message/src/components/atoms/index.ts
  packages/apps/message/src/components/organisms/MailMessageCard/MailMessageCard.tsx
  packages/core/src/utils/date.ts
  packages/core/src/utils/index.ts
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#1005 feat: add mass scan widget on stock move lines
  changelogs/unreleased/91166.json
  changelogs/unreleased/91166_toast.json
  docs/doc/en/tools/80_cameraScanner.md
  docs/doc/fr/tools/80_cameraScanner.md
  packages/apps/stock/src/api/index.ts
  packages/apps/stock/src/api/stock-move-line-api.js
  packages/apps/stock/src/api/stock-move-line-api.ts
  packages/apps/stock/src/components/molecules/MassScannerButton/MassScannerButton.tsx
  packages/apps/stock/src/components/molecules/index.js
  packages/apps/stock/src/components/organisms/StockMovePickingWidget/StockMovePickingWidget.tsx
  packages/apps/stock/src/components/organisms/index.js
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliverySearchLineContainer/CustomerDeliverySearchLineContainer.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveSearchLineContainer/InternalMoveSearchLineContainer.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalSearchLineContainer/SupplierArrivalSearchLineContainer.js
  packages/apps/stock/src/i18n/en.json
  packages/apps/stock/src/i18n/fr.json
  packages/apps/stock/src/models/objectFields.ts
  packages/apps/stock/src/models/searchFields.ts
  packages/core/src/components/external/Camera/Camera.tsx
  packages/core/src/components/external/Toast/Toast.tsx
  packages/core/src/components/external/Toast/ToastDisplay.tsx
  packages/core/src/components/organisms/MassScannerButton/MassScannerButton.tsx
  packages/core/src/components/organisms/index.js
  packages/core/src/hooks/use-mass-scanner.ts
  packages/core/src/hooks/use-scan-activator.ts
  packages/ui/__tests__/components/atoms/ProgressCircle.test.js
  packages/ui/src/components/atoms/ProgressCircle/ProgressCircle.tsx
  packages/ui/src/components/molecules/Stepper/Stepper.tsx
  packages/ui/stories/atoms/ProgressCircle.stories.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#1008 fix: avoid selecting wrong product when scanning a line
  changelogs/unreleased/96989.json
  changelogs/unreleased/96989_error-message.json
  packages/apps/stock/src/components/organisms/SearchLineContainer/SearchLineContainer.tsx
  packages/ui/__tests__/components/organisms/AutoCompleteSearch.test.js
  packages/ui/src/components/organisms/AutoCompleteSearch/AutoCompleteSearch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟
