Repository axelor/axelor-mobile, pull requests merged in 2025-03, with the labels that each got.

#912 fix: update address model structure
  changelogs/unreleased/91564_crm.json
  changelogs/unreleased/91564_project.json
  packages/apps/crm/src/hooks/use-crm-header-actions.ts
  packages/apps/crm/src/models/objectFields.ts
  packages/apps/project/src/models/objectFields.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#910 refactor: check permission access on sale package
  changelogs/unreleased/91562.json
  packages/apps/sale/src/components/atoms/SaleOrderBottomButton/SaleOrderBottomButton.tsx
  packages/apps/sale/src/components/molecules/CartHeader/CartHeader.tsx
  packages/apps/sale/src/components/molecules/CartLineActionCard/CartLineActionCard.tsx
  packages/apps/sale/src/components/molecules/CartLineValidationButton/CartLineValidationButton.tsx
  packages/apps/sale/src/components/molecules/CatalogActionCard/CatalogActionCard.tsx
  packages/apps/sale/src/hooks/use-sale-header-actions.ts
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
  packages/apps/sale/src/screens/cart/CartLineDetailsScreen.tsx
  packages/apps/sale/src/screens/saleOrder/SaleQuotationCreationScreen.tsx
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#911 refactor: check permission access on project package
  changelogs/unreleased/91563.json
  packages/apps/project/src/components/molecules/TaskActionCard/TaskActionCard.tsx
  packages/apps/project/src/components/organisms/CustomSection/CustomSection.tsx
  packages/apps/project/src/components/pages/TaskView/TaskView.tsx
  packages/apps/project/src/screens/ProjectDetailsScreen.tsx
  packages/apps/project/src/screens/TaskDetailsScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#917 refactor: check perm in leave button
  packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx
  packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#915 refactor: manage company in leave api
  packages/apps/hr/src/api/leave-api.js
  packages/apps/hr/src/components/molecules/LeaveDetailsButtons/LeaveDetailsButtons.tsx
  packages/apps/hr/src/components/templates/LeaveFilters/LeaveFilters.tsx
  packages/apps/hr/src/components/templates/LeaveRefusalPopup/LeaveRefusalPopup.tsx
  packages/apps/hr/src/components/templates/LeaveWaitingValidationSearchBar/LeaveWaitingValidationSearchBar.tsx
  packages/apps/hr/src/features/leaveSlice.js
  packages/apps/hr/src/screens/leaveRequests/LeaveFormScreen.tsx
  packages/apps/hr/src/screens/leaveRequests/LeaveListScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#914 refactor: manage company in purchase
  packages/apps/purchase/src/api/purchase-request-api.js
  packages/apps/purchase/src/api/supplier-api.js
  packages/apps/purchase/src/components/templates/SupplierSearchBar/SupplierSearchBar.tsx
  packages/apps/purchase/src/screens/RequestListScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#918 fix: manage dynamic selection on crm
  changelogs/unreleased/91804.json
  packages/apps/crm/src/models/typeObjects.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#919 fix: user fetch for dashboards and webview menus generation
  changelogs/unreleased/91916.json
  packages/core/src/auth/index.ts
Labels: 🐛 Bug, ✅ Done

#921 fix: change description title on purchase creation form
  packages/apps/purchase/src/i18n/en.json
  packages/apps/purchase/src/i18n/fr.json
  packages/apps/purchase/src/screens/RequestCreationScreen.tsx
Labels: 🐛 Bug, ✅ Done, Pair approved 🌟

#923 fix: improve logic on translations upload
  changelogs/unreleased/92162.json
  packages/core/src/auth/components/molecules/TranslationsButton/TranslationsButton.tsx
  packages/core/src/auth/features/configSlice.js
  packages/core/src/auth/i18n/en.json
  packages/core/src/auth/i18n/fr.json
  packages/core/src/i18n/api/translation.js
  packages/core/src/i18n/component/Translator.js
Labels: 🐛 Bug, ✅ Done

#922 fix: add showClearButton on DMS chipSelect
  packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
  packages/apps/dms/src/screens/MyFavoriteDocumentsScreen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#925 fix: add default unit for purchase request
  packages/apps/purchase/src/index.ts
  packages/apps/purchase/src/screens/RequestCreationScreen.tsx
  packages/core/src/config/routes.js
Labels: 🐛 Bug, ✅ Done

#927 feat: add tool to get all roles of user
  changelogs/unreleased/91930.json
  packages/core/src/dashboards/menu.helpers.ts
  packages/core/src/forms/studio/permission.helpers.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/role.ts
  packages/core/src/webViews/menu.helper.ts
Labels: 🌟 Feature, ✅ Done

#920 feat: create package @axelor/aos-mobile-message
  package.json
  packages/apps/message/.eslintrc.js
  packages/apps/message/.prettierrc.js
  packages/apps/message/README.md
  packages/apps/message/babel.config.js
  packages/apps/message/package.json
  packages/apps/message/src/i18n/en.json
  packages/apps/message/src/i18n/fr.json
  packages/apps/message/src/index.ts
  packages/apps/message/tsconfig.build.json
  packages/apps/message/tsconfig.json
  src/App.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#926 feat: create generic header action for AOP filter
  packages/core/src/api/aop-filter-api.ts
  packages/core/src/components/organisms/HeaderOptionsMenu/HeaderOptionsMenu.js
  packages/core/src/components/organisms/PopupFilters/PopupFilters.tsx
  packages/core/src/components/organisms/index.js
  packages/core/src/header/hooks.js
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#937 fix: add missing header action to create attached file
  changelogs/unreleased/92414_AttachedFiles.json
  changelogs/unreleased/92414_DocumentForm.json
  packages/apps/dms/src/components/atoms/SwitchDocumentType/SwitchDocumentType.tsx
  packages/apps/dms/src/screens/AttachedFilesScreen.tsx
  packages/apps/dms/src/screens/DocumentFormScreen.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#938 fix: date not save on click outside on DateInput
  changelogs/unreleased/92548.json
  packages/core/src/components/organisms/DateInput/DateInput.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#939 fix: crash when trying to add an event from the planning
  changelogs/unreleased/92549.json
  packages/apps/crm/src/screens/event/EventFormScreen.js
  packages/apps/crm/src/screens/event/EventPlanningScreen.js
Labels: 🐛 Bug, Approved 🌟, Pair approved 🌟

#940 fix: period error when creating an event
  changelogs/unreleased/92628.json
  packages/apps/crm/src/screens/event/EventFormScreen.js
Labels: 🐛 Bug, ✅ Done, Pair approved 🌟

#934 fix: display issue line card
  changelogs/unreleased/92436_LabelText.json
  changelogs/unreleased/92436_LineCard.json
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineCard/CustomerDeliveryLineCard.tsx
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineCard/SupplierArrivalLineCard.tsx
  packages/ui/__tests__/components/molecules/LabelText.test.js
  packages/ui/src/components/molecules/LabelText/LabelText.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#943 fix: handle scan focus when going back to a screen on ScannerAutocompleteSearch
  changelogs/unreleased/92505.json
  packages/core/src/components/organisms/ScannerAutocompleteSearch/ScannerAutocompleteSearch.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#942 fix: improve navigation after line validation
  changelogs/unreleased/92404.json
  packages/apps/stock/src/components/templates/customerDelivery/CustomerDeliveryLineButtons/CustomerDeliveryLineButtons.js
  packages/apps/stock/src/components/templates/internalMove/InternalMoveLineButtons/InternalMoveLineButtons.js
  packages/apps/stock/src/components/templates/inventory/InventoryLineButtons/InventoryLineButtons.js
  packages/apps/stock/src/components/templates/supplierArrival/SupplierArrivalLineButtons/SupplierArrivalLineButtons.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#930 feat: add AOP filters management
  packages/core/src/components/organisms/PopupFilters/PopupFilters.tsx
  packages/core/src/header/FilterProvider.tsx
  packages/core/src/header/hooks.js
  packages/core/src/hooks/use-active-filter.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#945 fix: add configuration for iPad
  changelogs/unreleased/92881.json
  ios/AosMobile.xcodeproj/project.pbxproj
  ios/AosMobile/Info.plist
Labels: 🐛 Bug, ✅ Done

#947 fix: add missing export
  packages/core/src/apiProviders/index.js
  packages/core/src/auth/index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟
