Repository axelor/axelor-mobile, pull requests merged in 2025-01, with the labels that each got.

#862 fix: add missing export of updateStockMoveLineTrackingNumber from trackingNumberSlice
  changelogs/unreleased/89190.json
  packages/apps/stock/src/features/asyncFunctions-index.ts
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#860 feat: add option to ignore action api
  changelogs/unreleased/86533.json
  packages/core/src/apiProviders/Action/utils.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#861 refactor: stack not reset on navigation
  changelogs/unreleased/69728.json
  packages/core/src/navigator/Navigator.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#852 refactor: manage company in data fetching in helpdesk
  changelogs/unreleased/88457.json
  packages/apps/helpdesk/src/api/customer-api.js
  packages/apps/helpdesk/src/api/project-api.js
  packages/apps/helpdesk/src/components/templates/ContactPartnerSearchBar/ContactPartnerSearchBar.js
  packages/apps/helpdesk/src/components/templates/CustomerSearchBar/CustomerSearchBar.js
  packages/apps/helpdesk/src/components/templates/ProjectSearchBar/ProjectSearchBar.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#857 refactor: manage company in data fetching in sale
  changelogs/unreleased/88462.json
  changelogs/unreleased/cart.json
  packages/apps/sale/src/api/cart-api.js
  packages/apps/sale/src/api/customer-api.js
  packages/apps/sale/src/api/customer-delivery-api.js
  packages/apps/sale/src/api/product-api.js
  packages/apps/sale/src/api/sale-config-api.js
  packages/apps/sale/src/api/sale-order-api.js
  packages/apps/sale/src/components/atoms/SaleOrderBottomButton/SaleOrderBottomButton.tsx
  packages/apps/sale/src/components/organisms/CustomerSearchBar/CustomerSearchBar.tsx
  packages/apps/sale/src/components/organisms/DropDownSaleOrderView/DropDownSaleOrderView.tsx
  packages/apps/sale/src/components/pages/SaleOrderListView/SaleOrderListView.tsx
  packages/apps/sale/src/index.ts
  packages/apps/sale/src/screens/cart/ActiveCartScreen.tsx
  packages/apps/sale/src/screens/cart/CatalogScreen.tsx
  packages/apps/sale/src/screens/client/ClientSaleListScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#850 refactor: manage company in data fetching in manufacturing
  changelogs/unreleased/88459.json
  packages/apps/manufacturing/src/api/machine-api.js
  packages/apps/manufacturing/src/api/manufacturing-order-api.js
  packages/apps/manufacturing/src/api/operation-order-api.js
  packages/apps/manufacturing/src/api/product-indicators-api.js
  packages/apps/manufacturing/src/components/organisms/ManufacturingOrderProductionOrderSetView/ManufacturingOrderProductionOrderSetView.js
  packages/apps/manufacturing/src/components/templates/MachineSearchBar/MachineSearchBar.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/ManufacturingOrderListProductionOrderScreen.js
  packages/apps/manufacturing/src/screens/manufactoringOrder/consumedProduct/ChildrenManufOrderListScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderListScreen.js
  packages/apps/manufacturing/src/screens/operationOrder/OperationOrderPlanningScreen.js
  packages/apps/manufacturing/src/screens/stock/products/ProductManufacturingIndicatorDetails.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#851 refactor: manage company in data fetching in stock
  changelogs/unreleased/88463.json
  packages/apps/stock/src/api/customer-delivery-api.js
  packages/apps/stock/src/api/internal-move-api.js
  packages/apps/stock/src/api/inventory-api.js
  packages/apps/stock/src/api/partner-api.js
  packages/apps/stock/src/api/product-indicators-api.js
  packages/apps/stock/src/api/stock-location-api.js
  packages/apps/stock/src/api/stock-location-line-api.js
  packages/apps/stock/src/api/supplier-arrival-api.js
  packages/apps/stock/src/components/templates/PartnerSearchBar/PartnerSearchBar.js
  packages/apps/stock/src/features/internalMoveSlice.js
  packages/apps/stock/src/screens/customerDeliveries/CustomerDeliveryListScreen.js
  packages/apps/stock/src/screens/internalMoves/InternalMoveListScreen.js
  packages/apps/stock/src/screens/inventories/InventoryListScreen.js
  packages/apps/stock/src/screens/products/ProductStockIndicatorDetails.tsx
  packages/apps/stock/src/screens/supplierArrivals/SupplierArrivalListScreen.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#868 feat: add props to hide message box and filter messages by date on MailMessageView
  changelogs/unreleased/89626_date.json
  changelogs/unreleased/89626_messagebox.json
  packages/core/src/api/mail-message-api.ts
  packages/core/src/components/templates/MailMessageView/MailMessageView.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#858 refactor: manage company in data fetching in project
  changelogs/unreleased/88460.json
  packages/apps/project/src/api/project-api.js
  packages/apps/project/src/api/project-task-api.js
  packages/apps/project/src/components/pages/SubProjectView/SubProjectView.tsx
  packages/apps/project/src/components/pages/TaskView/TaskView.tsx
  packages/apps/project/src/components/templates/ProjectListView/ProjectListView.tsx
  packages/apps/project/src/components/templates/ProjectSearchBar/ProjectSearchBar.tsx
  packages/apps/project/src/screens/TaskListScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Pair approved 🌟

#872 feat: add API actions on status buttons
  packages/apps/purchase/src/api/index.ts
  packages/apps/purchase/src/api/purchase-request-api.js
  packages/apps/purchase/src/components/organisms/RequestButtons/RequestButtons.tsx
  packages/apps/purchase/src/features/asyncFunctions-index.ts
  packages/apps/purchase/src/features/purchaseRequestSlice.js
  packages/apps/purchase/src/i18n/en.json
  packages/apps/purchase/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟, Pair approved 🌟

#873 feat: renane Address to Main Adress Clients and Prospects
  changelogs/unreleased/89400.json
  packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js
  packages/apps/crm/src/components/organisms/DropdownContactView/DropdownContactView.tsx
  packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#867 feat: use address object for lead address
  changelogs/unreleased/89399.json
  packages/apps/crm/src/components/organisms/Event/EventLeadCard/EventLeadCard.js
  packages/apps/crm/src/components/organisms/Lead/LeadDropdownCards/LeadDropdownCards.js
  packages/apps/crm/src/hooks/use-crm-header-actions.ts
  packages/apps/crm/src/models/forms.ts
  packages/apps/crm/src/models/objectFields.ts
  packages/apps/crm/src/models/searchFields.ts
  packages/apps/crm/src/screens/lead/LeadListScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#874 feat: add API on leave request creation assistant
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/api/leave-api.js
  packages/apps/hr/src/components/atoms/LeaveStartEndOn/LeaveStartEndOn.tsx
  packages/apps/hr/src/components/templates/CompleteRequestButtons/CompleteRequestButtons.tsx
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/leaveSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#871 refactor: show leave reason available quantity only on managed reason
  packages/apps/hr/src/components/atoms/LeaveAvailableDuractionCard/LeaveAvailableDuractionCard.tsx
  packages/apps/hr/src/components/templates/CompleteRequestQuantityCard/CompleteRequestQuantityCard.tsx
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx
  packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx
Labels: 🔧 Refactor, ✅ Done, Approved 🌟

#847 feat: improve management of root element creation
  changelogs/unreleased/88573.json
  packages/apps/dms/src/components/organisms/ParentDirectorySearchBar/ParentDirectorySearchBar.tsx
  packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
  packages/apps/dms/src/hooks/use-dms-header-actions.ts
  packages/apps/dms/src/i18n/en.json
  packages/apps/dms/src/i18n/fr.json
  packages/apps/dms/src/models/forms.ts
  packages/apps/dms/src/screens/DocumentFormScreen.tsx
  packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#865 refactor: manage company data in hr
  changelogs/unreleased/88455.json
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/manuf-order-api.js
  packages/apps/hr/src/api/project-api.js
  packages/apps/hr/src/api/timesheet-api.js
  packages/apps/hr/src/components/templates/DraftExpensePicker/DraftExpensePicker.js
  packages/apps/hr/src/components/templates/DraftTimesheetPicker/DraftTimesheetPicker.tsx
  packages/apps/hr/src/components/templates/ExpenseWaitingValidationSearchBar/ExpenseWaitingValidationSearchBar.js
  packages/apps/hr/src/components/templates/OperationOrderSearchBar/OperationOrderSearchBar.tsx
  packages/apps/hr/src/components/templates/ProjectTaskSearchBar/ProjectTaskSearchBar.tsx
  packages/apps/hr/src/components/templates/TimerListAlert/TimerListAlert.tsx
  packages/apps/hr/src/components/templates/TimesheetFilters/TimesheetFilters.js
  packages/apps/hr/src/components/templates/TimesheetWaitingValidationSearchBar/TimesheetWaitingValidationSearchBar.js
  packages/apps/hr/src/screens/expense/ExpenseListScreen.js
  packages/apps/hr/src/screens/timesheet/TimesheetListScreen.js
Labels: 🔧 Refactor, ✅ Done, Approved 🌟, Pair approved 🌟

#869 feat: add DropdownAddressView
  changelogs/unreleased/89402.json
  changelogs/unreleased/89402_dropdown.json
  packages/apps/crm/src/api/index.ts
  packages/apps/crm/src/api/partner-api.js
  packages/apps/crm/src/components/organisms/Client/ClientDropdownCards/ClientDropdownCards.js
  packages/apps/crm/src/components/organisms/DropdownAddressesView/DropdownAddressesView.tsx
  packages/apps/crm/src/components/organisms/Prospect/ProspectDropdownCards/ProspectDropdownCards.js
  packages/apps/crm/src/components/organisms/index.js
  packages/apps/crm/src/features/asyncFunctions-index.ts
  packages/apps/crm/src/features/partnerSlice.js
  packages/apps/crm/src/i18n/en.json
  packages/apps/crm/src/i18n/fr.json
  packages/apps/crm/src/models/objectFields.ts
  packages/ui/src/components/molecules/DropdownCard/DropdownCard.tsx
  packages/ui/src/components/organisms/DropdownCardSwitch/DropdownCardSwitch.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#876 fix: wrong export of UserScreen
  changelogs/unreleased/89993.json
  packages/apps/stock/src/index.ts
  packages/apps/stock/src/screens/auth/index.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#879 fix: add missing sortKey on search functions in stock
  changelogs/unreleased/90186.json
  packages/apps/stock/src/api/customer-delivery-line-api.js
  packages/apps/stock/src/api/internal-move-line-api.js
  packages/apps/stock/src/api/inventory-line-api.js
  packages/apps/stock/src/api/partner-api.js
  packages/apps/stock/src/api/product-api.js
  packages/apps/stock/src/api/product-indicators-api.js
  packages/apps/stock/src/api/stock-correction-reason-api.js
  packages/apps/stock/src/api/stock-location-api.js
  packages/apps/stock/src/api/stock-location-line-api.js
  packages/apps/stock/src/api/supplier-arrival-line-api.js
  packages/apps/stock/src/api/supplier-catalog-api.js
  packages/apps/stock/src/api/unit-api.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟, Pair approved 🌟

#866 feat: add tool to manage search on hierarchical objects
  changelogs/unreleased/87444.json
  changelogs/unreleased/87444_stock.json
  packages/apps/stock/src/api/stock-location-api.js
  packages/core/src/apiProviders/Model/utils.ts
  packages/core/src/apiProviders/Standard/index.ts
  packages/core/src/apiProviders/Standard/requests.helper.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟
