Repository axelor/axelor-mobile, pull requests merged in 2025-02, with the labels that each got.

#883 feat: use AOS API to check consistency on leave request
  packages/apps/hr/src/api/leave-api.js
  packages/apps/hr/src/components/templates/CompleteRequestButtons/CompleteRequestButtons.tsx
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#881 feat: add download on DMS file
  android/app/src/main/AndroidManifest.xml
  changelogs/unreleased/89765_core.json
  ios/Podfile.lock
  jest/setup-mocks.js
  package.json
  packages/apps/dms/src/components/molecules/DocumentActionCard/DocumentActionCard.tsx
  packages/core/package.json
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/tools/FileDownloader.ts
  packages/core/src/tools/index.js
  yarn.lock
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#884 feat: add PeriodInput on event form on crm
  changelogs/unreleased/90595.json
  changelogs/unreleased/90595_PeriodInput_DateConfig.json
  changelogs/unreleased/90595_PeriodInput_Error.json
  packages/apps/crm/src/components/organisms/EventPeriodInput/EventPeriodInput.tsx
  packages/apps/crm/src/components/organisms/index.js
  packages/apps/crm/src/models/forms.ts
  packages/apps/crm/src/screens/event/EventFormScreen.js
  packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#886 fix: add spacer translations and callback for useless refresh
  changelogs/unreleased/90855_formincrement.json
  changelogs/unreleased/90855_spacer.json
  packages/apps/hr/src/components/templates/DistanceIncrement/DistanceIncrement.js
  packages/ui/src/components/molecules/FormIncrementInput/FormIncrementInput.tsx
Labels: 🐛 Bug, ✅ Done

#887 feat: add APK download management for version update
  changelogs/unreleased/89763.json
  packages/core/src/components/templates/PopupMinimalRequiredVersion/PopupMinimalRequiredVersion.js
  packages/core/src/components/templates/PopupMinimalRequiredVersion/PopupMinimalRequiredVersion.tsx
  packages/core/src/i18n/translations/en.json
  packages/core/src/i18n/translations/fr.json
  packages/core/src/tools/FileDownloader.ts
Labels: 🌟 Feature, ✅ Done, Pair approved 🌟

#891 feat: add API on availability check
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/api/leave-api.js
  packages/apps/hr/src/components/atoms/LeaveAvailableDuractionCard/LeaveAvailableDuractionCard.tsx
  packages/apps/hr/src/components/templates/CompleteRequestQuantityCard/CompleteRequestQuantityCard.tsx
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
  packages/apps/hr/src/models/objectFields.ts
  packages/apps/hr/src/screens/leaveRequests/CompleteRequestScreen.tsx
  packages/apps/hr/src/screens/leaveRequests/LeaveDetailsScreen.tsx
Labels: 🌟 Feature, ✅ Done

#888 feat: add more action on expense workflow
  changelogs/unreleased/86726.json
  packages/apps/hr/src/api/expense-api.js
  packages/apps/hr/src/api/index.ts
  packages/apps/hr/src/components/molecules/ExpenseDetailsValidationButton/ExpenseDetailsValidationButton.tsx
  packages/apps/hr/src/features/asyncFunctions-index.ts
  packages/apps/hr/src/features/expenseSlice.js
  packages/apps/hr/src/i18n/en.json
  packages/apps/hr/src/i18n/fr.json
Labels: 🌟 Feature, ✅ Done

#894 doc: add enterprise module management
  docs/doc/en/GettingStarted.md
  docs/doc/fr/GettingStarted.md
Labels: 📚 Documentation, ✅ Done

#892 feat: add API action on request creation
  packages/apps/purchase/src/api/index.ts
  packages/apps/purchase/src/api/purchase-request-api.js
  packages/apps/purchase/src/components/templates/RequestCreationButtons/RequestCreationButtons.tsx
  packages/apps/purchase/src/features/asyncFunctions-index.ts
  packages/apps/purchase/src/features/purchaseRequestSlice.js
  packages/apps/purchase/src/i18n/en.json
  packages/apps/purchase/src/i18n/fr.json
  packages/apps/purchase/src/screens/RequestCreationScreen.tsx
  packages/apps/purchase/src/types/request-creation.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#897 fix: error when onPeriodErrorChange not provided on PeriodInput
  changelogs/unreleased/91359.json
  packages/core/src/components/templates/PeriodInput/PeriodInput.tsx
Labels: 🐛 Bug, ✅ Done

#898 fix: modify intervention user filter
  changelogs/unreleased/91463.json
  packages/apps/intervention/src/api/intervention-api.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#899 fix: issue on control entry completion
  changelogs/unreleased/90996.json
  packages/apps/quality/src/screens/ControlEntryFormScreen.js
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#901 fix: display issue on control entry line with long title
  changelogs/unreleased/90998.json
  packages/apps/quality/src/components/atoms/ControlEntrySampleLineHeader/ControlEntrySampleLineHeader.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#902 feat: add possibility to define a custom search bar on SearchListView
  changelogs/unreleased/91544.json
  packages/apps/stock/src/screens/products/ProductListScreen.js
  packages/core/src/components/templates/DoubleScannerSearchBar/DoubleScannerSearchBar.tsx
  packages/core/src/components/templates/SearchListView/SearchListView.tsx
Labels: 🌟 Feature, ✅ Done

#905 fix: progress bar always display a progress even when value is 0
  changelogs/unreleased/91566.json
  packages/ui/src/components/organisms/ProgressBar/ProgressBar.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#906 fix: crash when no management of parent from outside of tree view
  packages/core/src/components/templates/SearchTreeView/SearchTreeView.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟

#903 feat: add contact information addition management
  packages/apps/crm/src/api/contact-info-api.js
  packages/apps/crm/src/api/index.ts
  packages/apps/crm/src/components/molecules/ContactInfoCard/ContactInfoCard.tsx
  packages/apps/crm/src/components/molecules/SocialNetworksInfoCard/SocialNetworksInfoCard.tsx
  packages/apps/crm/src/components/organisms/DropdownAddressesView/DropdownAddressesView.tsx
  packages/apps/crm/src/components/organisms/DropdownContactView/DropdownContactView.tsx
  packages/apps/crm/src/screens/client/ClientDetailsScreen.js
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#907 feat: add current request path in the traceback to make it more readable
  changelogs/unreleased/91002.json
  packages/core/src/apiProviders/utils.ts
Labels: 🌟 Feature, ✅ Done, Approved 🌟

#909 fix: add access control on dms package
  packages/apps/dms/src/components/atoms/DirectoryCard/DirectoryCard.tsx
  packages/apps/dms/src/components/molecules/DocumentActionCard/DocumentActionCard.tsx
  packages/apps/dms/src/components/templates/DocumentList/DocumentList.tsx
Labels: 🐛 Bug, ✅ Done, Approved 🌟
